check for both prudynt and imp-control running

diff --git a/package/ingenic-libimp-control/src/S96impconfig b/package/ingenic-libimp-control/src/S96impconfig
--- a/package/ingenic-libimp-control/src/S96impconfig
+++ b/package/ingenic-libimp-control/src/S96impconfig
@@ -2,27 +2,29 @@
 
 config="/etc/imp.conf"
 
-start() {
+check_imp() {
 	echo -n "Establishing connection ..."
 	i=0
-	while ! grep -q running /proc/jz/isp/isp-fs; do
-		echo -n '.'
+	while :; do
+		grep -q running /proc/jz/isp/isp-fs &&
+			imp-control getdeviceid > /dev/null &&
+			echo " OK" && return
+		echo -n "."
 		i=$((i + 1))
-		if [ "$i" -gt 10 ]; then
-			echo " FAIL (timeout)"
-			exit
-		fi
 		sleep 1
+		[ $i -gt 10 ] && echo " FAIL (timeout)" && exit 1
 	done
-	echo " OK"
+}
 
+start() {
+	check_imp
 	echo -n "Restoring IMP Configuration:"
 	if [ -f "$config" ]; then
 		echo
 		while read -r line; do
 			echo -e " * $line"
-			imp-control $line >/dev/null
-		done <$config
+			imp-control $line > /dev/null
+		done < $config
 		echo "Done"
 	else
 		echo "DISABLED"
