restore IMP configuration on boot

diff --git a/package/ingenic-libimp-control/src/S96impconfig b/package/ingenic-libimp-control/src/S96impconfig
--- a/package/ingenic-libimp-control/src/S96impconfig
+++ b/package/ingenic-libimp-control/src/S96impconfig
@@ -1,34 +1,46 @@
 #!/bin/sh
 
+config="/etc/imp.conf"
+
 start() {
-	[ ! -f "/etc/imp.conf" ] && return
+	echo -n "Establishing connection ..."
+	i=0
+	while ! grep -q running /proc/jz/isp/isp-fs; do
+		echo -n '.'
+		i=$((i + 1))
+		if [ "$i" -gt 10 ]; then
+			echo " FAIL (timeout)"
+			exit
+		fi
+		sleep 1
+	done
+	echo " OK"
 
 	echo -n "Restoring IMP Configuration: "
-	while read -r line; do
-		imp-control $line
-	done < /etc/imp.conf
-	echo "OK"
-}
-
-stop() {
-	:
-}
-
-restart() {
-	start
-}
-
-reload() {
-	start
+	if [ -f "$config" ]; then
+		echo
+		while read -r line; do
+			echo -e " * $line"
+			imp-control $line >/dev/null
+		done <$config
+		echo "Done"
+	else
+		echo "DISABLED"
+		return
+	fi
 }
 
 case "$1" in
-	start|stop|restart|reload)
-		"$1"
-		;;
-	*)
-		echo "Usage: $0 {start|restart|reload}"
-		exit 1
+start | restart | reload)
+	start
+	;;
+stop)
+	:
+	;;
+*)
+	echo "Usage: $0 {start|restart|reload}"
+	exit 1
+	;;
 esac
 
 exit 0
