refactor and colorize scripts

diff --git a/overlay/lower/etc/init.d/rcS b/overlay/lower/etc/init.d/rcS
--- a/overlay/lower/etc/init.d/rcS
+++ b/overlay/lower/etc/init.d/rcS
@@ -1,7 +1,9 @@
 #!/bin/sh
 
+. /etc/init.d/rc.common
+
 export SENSOR=$(cat /etc/sensor/model)
-export SOC=$(/usr/sbin/soc -f)
+export SOC=$(soc -f)
 export TZ=$(cat /etc/TZ)
 
 # Seritificates for curl in non-interactive shell
@@ -20,17 +22,15 @@ execute_and_log() {
 
 	logger_pid=$!
 
-	if /bin/sh -c "$script start" > /tmp/initlogpipe 2>&1; then
-		: # Success
-	else
-		: # Failure
-	fi
+	/bin/sh -c "$script start" > /tmp/initlogpipe 2>&1
+	# && ok || fail
 
 	rm -f /tmp/initlogpipe
 }
 
 for i in /etc/init.d/S??*; do
-	[ ! -f "$i" ] && continue
+	[ -f "$i" ] || continue
+
 	execute_and_log "$i" &
 	wait
 done
diff --git a/overlay/lower/usr/sbin/envfromcard b/overlay/lower/usr/sbin/envfromcard
--- a/overlay/lower/usr/sbin/envfromcard
+++ b/overlay/lower/usr/sbin/envfromcard
@@ -2,10 +2,7 @@
 
 uenv="/mnt/mmcblk0p1/uEnv.txt"
 
-if [ ! -f "$uenv" ]; then
-	echo "File $uenv not found"
-	exit 1
-fi
+[ -f "$uenv" ] || die 1 "File $uenv not found"
 
 tmp=$(mktemp)
 sed 's/=/ /' $uenv > $tmp
diff --git a/overlay/lower/usr/sbin/sysupgrade b/overlay/lower/usr/sbin/sysupgrade
--- a/overlay/lower/usr/sbin/sysupgrade
+++ b/overlay/lower/usr/sbin/sysupgrade
@@ -4,11 +4,6 @@ KERNEL_MAGIC="27051956"
 U_BOOT_MAGIC="06050403"
 ROOTFS_MAGIC="68737173"
 
-die() {
-	echo "$1"
-	exit ${2:-99}
-}
-
 show_help() {
 	echo "Usage: $0 <filename> | [-f | -p] | <URL>
 Where:
@@ -39,21 +34,17 @@ if [ -z "$upgrade" ]; then
 else
 	data=/etc/os-release
 	profile=$(awk -F '=' '/^IMAGE_ID=/ {print $2}' $data)
-	if [ -z "$profile" ]; then
-		die "Building profile is not set in $data"
-	fi
+	[ -z "$profile" ] && die 99 "Building profile is not set in $data"
 	binary_file=$(mktemp -u)
 fi
 
 if echo "$1" | grep -qE '^https?://'; then
 	binary_file=$(mktemp)  # Create a temporary file
 	echo "Downloading firmware from $1."
-	curl -# -L -f -o $binary_file $1 || die "Failed to download firmware from $1. Exiting."
+	curl -# -L -f -o $binary_file $1 || die 99 "Failed to download firmware from $1. Exiting."
 fi
 
-if ! grep -q -e "mtd6" -e "mtd5" /proc/mtd; then
-	die "Please run 'fw_setenv enable_updates true' then reboot the camera. Re-run upgrade after reboot."
-fi
+grep -q -e "mtd6" -e "mtd5" /proc/mtd || die 99 "Please run 'fw_setenv enable_updates true' then reboot the camera. Re-run upgrade after reboot."
 
 case "$upgrade" in
 	local) ;;
@@ -66,13 +57,11 @@ case "$upgrade" in
 			fw_file="/thingino-${profile}.bin"
 		fi
 		echo "Downloading firmware from ${url}${fw_file}."
-		if ! curl -# -L -f -o $binary_file ${url}${fw_file}; then
-			die "Failed to download firmware from $url. Exiting."
-		fi
+		curl -# -L -f -o $binary_file ${url}${fw_file} || die 99 "Failed to download firmware from $url. Exiting."
 		;;
 esac
 
-[ ! -f "$binary_file" ] && die "File $1 not found"
+[ ! -f "$binary_file" ] && die 99 "File $1 not found"
 
 magic=$(xxd -l 4 -p $binary_file)
 case "$magic" in
@@ -88,10 +77,10 @@ case "$magic" in
 		mtd_dev="mtd5"
 		;;
 	$ROOTFS_MAGIC)
-		die "We cannot flash only rootfs"
+		die 99 "We cannot flash only rootfs"
 		;;
 	*)
-		die "Unknown file"
+		die 99 "Unknown file"
 esac
 
 echo "Stopping services"
@@ -112,8 +101,7 @@ if flashcp -v $binary_file /dev/$mtd_dev; then
 	echo "Rebooting..."
 	reboot -f
 else
-	echo "Upgrade failed!"
-	die "You have to perform a recovery flashing before rebooting the camera!"
+	die 99 "Upgrade failed! You have to perform a recovery flashing before rebooting the camera!"
 fi
 
 exit 0
