init: less dependencies

diff --git a/overlay/lower/etc/init.d/S02sysctl b/overlay/lower/etc/init.d/S02sysctl
--- a/overlay/lower/etc/init.d/S02sysctl
+++ b/overlay/lower/etc/init.d/S02sysctl
@@ -1,11 +1,14 @@
 #!/bin/sh
 
-. /etc/init.d/rc.common
-
 start() {
-	starting
-	sysctl -q -p || die "Failed to apply sysctl settings"
-	check_result
+	echo "Applying sysctl settings..."
+
+	if sysctl -q -p; then
+		echo "Sysctl settings applied"
+	else
+		echo "Failed to apply sysctl settings"
+		exit 1
+	fi
 }
 
 case "$1" in
