refactor and utilize die()

diff --git a/overlay/lower/etc/init.d/S05gpio b/overlay/lower/etc/init.d/S05gpio
--- a/overlay/lower/etc/init.d/S05gpio
+++ b/overlay/lower/etc/init.d/S05gpio
@@ -43,10 +43,7 @@ process_config_file() {
 	success=1
 
 	# Check if the configuration file exists
-	if [ ! -f "$CONFIG_FILE" ]; then
-		echo "GPIO configuration file not found!"
-		exit 1
-	fi
+	[ -f "$CONFIG_FILE" ] || die "GPIO configuration file not found!"
 
 	# Read the configuration file line by line
 	while IFS= read -r line || [ -n "$line" ]; do
@@ -86,8 +83,7 @@ case "$1" in
 		true
 		;;
 	*)
-		echo "Usage: $0 {start}"
-		exit 1
+		die "Usage: $0 {start}"
 		;;
 esac
 
diff --git a/package/wifi/files/S36wireless b/package/wifi/files/S36wireless
--- a/package/wifi/files/S36wireless
+++ b/package/wifi/files/S36wireless
@@ -9,7 +9,7 @@ start() {
 	gpionum="$(fw_printenv -n gpio_wlan)"
 	mac_address=$(fw_printenv -n wlanmac)
 
-	wlandev_check || { echo "Disabled"; exit 1; }
+	wlandev_check || die "Disabled"
 
 	if [ -n "$gpionum" ]; then
 		num=${gpionum%[oO]}
@@ -25,12 +25,7 @@ start() {
 		esac
 
 		echo -en "\n Set GPIO $num $gpio_cmd... "
-		if gpio $gpio_cmd $num 2>&1 | logger -p daemon.info -t $0; then
-			echo "OK"
-		else
-			echo "FAIL"
-			exit 1
-		fi
+		gpio $gpio_cmd $num 2>&1 | logger -p daemon.info -t $0 && echo "OK" || die "FAIL"
 	fi
 
 	#FIXME Assume that we are SDIO, and we need to insert
@@ -65,8 +60,7 @@ case "$1" in
 		true
 		;;
 	*)
-		echo "Usage: $0 {start}"
-		exit 1
+		die "Usage: $0 {start}"
 		;;
 esac
 
