init: less abstractions

diff --git a/overlay/lower/etc/init.d/S05usb b/overlay/lower/etc/init.d/S05usb
--- a/overlay/lower/etc/init.d/S05usb
+++ b/overlay/lower/etc/init.d/S05usb
@@ -1,18 +1,38 @@
 #!/bin/sh
 
-. /etc/init.d/rc.common
+ENV_DUMP_FILE="/tmp/environment"
+[ -f "$ENV_DUMP_FILE" ] && . "$ENV_DUMP_FILE"
+
+die() {
+	echo "$1"
+	exit 1
+}
+
+start() {
+	echo "Configuring USB..."
+
+	if [ -z "$gpio_usb_en" ]; then
+		echo "USB power GPIO is not set"
+		exit 0
+	fi
+
+	if [ "$gpio_usb_en" = "${gpio_usb_en//[^0-9]/}" ]; then
+		gpio_usb_en="${gpio_usb_en}O"
+	fi
+
+	pin="${gpio_usb_en:0:-1}"
+	case "${gpio_usb_en#$pin}" in
+		o) gpio set $pin 0 || die "Failed to set USB power GPIO $pin to $state" ;;
+		O) gpio set $pin 1 || die "Failed to set USB power GPIO $pin to $state" ;;
+		*) die "Invalid state $state" ;;
+	esac
+
+	echo "Set USB power GPIO $pin to $state"
+}
 
 case "$1" in
 	start)
-		starting
-		gpio_control "gpio_usb_en"
-		case "$?" in
-			0) ok ;;
-			1) quit "GPIO power is not set" ;;
-			2) die "GPIO is in invalid state" ;;
-			3) die "GPIO command failed" ;;
-			*) die "Unknown exit code $?" ;;
-		esac
+		start
 		;;
 	stop)
 		true
diff --git a/overlay/lower/usr/sbin/formatsd b/overlay/lower/usr/sbin/formatsd
--- a/overlay/lower/usr/sbin/formatsd
+++ b/overlay/lower/usr/sbin/formatsd
@@ -1,27 +1,36 @@
 #!/bin/sh
 
-die() { printf "\e[38;5;160m%s\e[0m\n" "$1" >&2; exit 1; }
-info() { printf "\e[38;5;46m%s\e[0m\n" "$1" >&2; }
-
-pidof -o %PPID $(basename $0) > /dev/null && die "is already running"
+if pidof -o %PPID $(basename $0) > /dev/null; then
+	echo "is already running"
+	exit 1
+fi
 
 format_partition() {
 	unmount_partition $1
-	info "Format partition"
-	$MKFS -n thingino $1 2>&1 || die "Cannot format $1 to $POST_fstype"
+	echo "Format partition"
+	if ! $MKFS -n thingino $1 2>&1; then
+		echo "Cannot format $1 to $POST_fstype"
+		exit 1
+	fi
 }
 
 mount_partitions() {
-	info "Mount partition"
+	echo "Mount partition"
 	echo /sbin/mdev > /proc/sys/kernel/hotplug
-	mdev -s || die "Cannot re-mount SD card"
+	if ! mdev -s; then
+		echo "Cannot re-mount SD card"
+		exit 1
+	fi
 }
 
 unmount_partition() {
-	info "Unmount partition"
+	echo "Unmount partition"
 	local limit=5
 	while mountpoint -q $1; do
-		[ "$limit" -gt 0 ] || die "Cannot unmount $1"
+		if [ "$limit" -le 0 ]; then
+			echo "Cannot unmount $1"
+			exit 1
+		fi
 		umount -l $1 2>&1
 		sleep 0.5
 		limit=$((limit-1))
@@ -29,7 +38,7 @@ unmount_partition() {
 }
 
 reinsert_sdcard() {
-	info "Reinsert card"
+	echo "Reinsert card"
 	echo "" > /proc/sys/kernel/hotplug
 	mmc 0 -r
 	sleep 1
@@ -38,8 +47,11 @@ reinsert_sdcard() {
 }
 
 repartition_sdcard() {
-	info "Repartition card"
-	echo -e "o\nn\np\n1\n\n\nt\n$FSTYPE\nw" | fdisk $1 2>&1 || die "Cannot create a partition on $1"
+	echo "Repartition card"
+	if ! echo -e "o\nn\np\n1\n\n\nt\n$FSTYPE\nw" | fdisk $1 2>&1; then
+		echo "Cannot create a partition on $1"
+		exit 1
+	fi
 }
 
 case "$1" in
@@ -54,7 +66,10 @@ case "$1" in
 esac
 
 device_name="$(awk -F= '/DEVNAME/{print $2}' /sys/bus/mmc/devices/*/block/*/uevent)"
-[ -z "$device_name" ] && die "No SD card device found"
+if [ -z "$device_name" ]; then
+	echo "No SD card device found"
+	exit 1
+fi
 
 unmount_partition  "/mnt/${device_name}p1"
 repartition_sdcard "/dev/${device_name}"
