refactor init scripts

diff --git a/overlay/lower/etc/init.d/S09mmc b/overlay/lower/etc/init.d/S09mmc
--- a/overlay/lower/etc/init.d/S09mmc
+++ b/overlay/lower/etc/init.d/S09mmc
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+. /etc/init.d/rc.common
+
 SOC_FAMILY=$(/usr/sbin/soc -f)
 SOC_MODEL=$(/usr/sbin/soc -m)
 
@@ -22,23 +24,30 @@ set_gpios() {
 	fi
 }
 
+load_module() {
+	grep -q "$MMC_MODULE" /proc/modules && die 1 "$MMC_MODULE is already loaded"
+
+	modprobe $MMC_MODULE ${MMC_PARAM} || die 1 "FAIL"
+
+	echo "OK"
+	set_gpios
+}
+
 start() {
-	echo -n "Starting MMC: "
+	starting
 
 	MMC_PARAM="cd_gpio_pin=$MMC_GPIO_CD"
 
 	# Check if MDIO directory exists
 	if [ -d /proc/jz/mdio ]; then
 		echo -n "/proc/jz/mdio directory exists, MSC1 disabled... "
-		load_module
 	else
 		case "$SOC_FAMILY" in
 			t10 | t20 | t21 | t30 | t40 | t41)
 				# do nothing
 				;;
 			t23)
-				echo "Unsupported: T23"
-				exit 1
+				die 1 "Unsupported: T23"
 				;;
 			t31)
 				if [ "$SOC_MODEL" = "t31a" ] || [ "$SOC_MODEL" = "t31al" ]; then
@@ -54,27 +63,11 @@ start() {
 				fi
 				;;
 			*)
-				echo "Unsupported SOC type: $SOC_FAMILY"
-				exit 1
+				die 1 "Unsupported SOC type: $SOC_FAMILY"
 				;;
 		esac
+	fi
 	load_module
-	fi
-}
-
-load_module() {
-	if grep -q "$MMC_MODULE" /proc/modules; then
-		echo "$MMC_MODULE is already loaded"
-		exit 1
-	else
-		if modprobe $MMC_MODULE ${MMC_PARAM}; then
-			echo "OK"
-			set_gpios
-		else
-			echo "FAIL"
-			exit 1
-		fi
-	fi
 }
 
 case "$1" in
@@ -88,6 +81,9 @@ case "$1" in
 		stop
 		sleep 1
 		start
+		;;
+	*)
+		die 1 "Usage: $0 {start}"
 		;;
 esac
 
diff --git a/overlay/lower/etc/init.d/S10modules b/overlay/lower/etc/init.d/S10modules
--- a/overlay/lower/etc/init.d/S10modules
+++ b/overlay/lower/etc/init.d/S10modules
@@ -1,29 +1,32 @@
 #!/bin/sh
 
+. /etc/init.d/rc.common
+
 load_modules() {
-	local file="$1"
-	[ -r "${file}" ] || return 0
+	local file=$1
+	[ -r "$file" ] || return 0
+
 	while read -r module args; do
 		case "$module" in
 			"" | "#"*)
 				continue
 				;;
 		esac
-		eval "args=\"${args}\""
-		echo -n " ${module}... "
-		modprobe ${module} ${args} && echo "OK" || echo "FAIL"
-	done < "${file}"
+		eval "args=\"$args\""
+		echo -n " $module ... "
+		modprobe $module $args && echo "OK" || echo "FAIL"
+	done < $file
 }
 
 case "$1" in
 	start)
 		echo "Loading modules: "
 
-		load_modules "/etc/modules"
+		load_modules /etc/modules
 
-		if [ -d "/etc/modules.d" ]; then
+		if [ -d /etc/modules.d ]; then
 			for conf in /etc/modules.d/*; do
-				load_modules "${conf}"
+				load_modules $conf
 			done
 		fi
 		;;
