extract load_module, refactor for brevity

diff --git a/overlay/lower/etc/init.d/S09mmc b/overlay/lower/etc/init.d/S09mmc
--- a/overlay/lower/etc/init.d/S09mmc
+++ b/overlay/lower/etc/init.d/S09mmc
@@ -24,6 +24,12 @@ set_gpios() {
 	fi
 }
 
+load_module() {
+	grep -q "$MMC_MODULE" /proc/modules && die "$MMC_MODULE is already loaded"
+	modprobe $MMC_MODULE $MMC_PARAM && echo "OK" || die "FAIL"
+	set_gpios
+}
+
 start() {
 	starting
 
@@ -32,7 +38,6 @@ start() {
 	# Check if MDIO directory exists
 	if [ -d /proc/jz/mdio ]; then
 		echo -n "/proc/jz/mdio directory exists, MSC1 disabled... "
-		load_module
 	else
 		case "$SOC_FAMILY" in
 			t10 | t20 | t21 | t30 | t40 | t41)
@@ -58,23 +63,8 @@ start() {
 				die "Unsupported SOC type: $SOC_FAMILY"
 				;;
 		esac
+	fi
 	load_module
-	fi
-}
-
-load_module() {
-	if grep -q "$MMC_MODULE" /proc/modules; then
-		echo "$MMC_MODULE is already loaded"
-		exit 1
-	else
-		if modprobe $MMC_MODULE ${MMC_PARAM}; then
-			echo "OK"
-			set_gpios
-		else
-			echo "FAIL"
-			exit 1
-		fi
-	fi
 }
 
 case "$1" in
