ISP config init

diff --git a/overlay/lower/etc/init.d/S10modules b/overlay/lower/etc/init.d/S10modules
--- a/overlay/lower/etc/init.d/S10modules
+++ b/overlay/lower/etc/init.d/S10modules
@@ -1,23 +1,30 @@
 #!/bin/sh
 
+load_modules() {
+	local file="$1"
+	[ -r "${file}" ] || return 0
+	while read module args; do
+		case "$module" in
+			"" | "#"*)
+				continue
+				;;
+		esac
+		echo -n "Load module ${module}... "
+		modprobe ${module} ${args} && echo "OK" || echo "FAIL"
+	done < "${file}"
+}
+
 case "$1" in
 	start)
 		echo -n "Loading modules: "
-		# load modules for detected devices
-		# find /sys/ -name modalias -print0 | xargs -0 sort -u -z | xargs -0 modprobe -abq
 
-		# load modules from /etc/modules
-		[ -r /etc/modules ] || exit 0
-		while read module args; do
-			case "$module" in
-				"" | "#"*)
-					continue
-					;;
-			esac
+		load_modules "/etc/modules"
 
-			echo -n "Load module ${module} ... "
-			modprobe ${module} ${args} && echo "OK" || echo "FAIL"
-		done < /etc/modules
+		if [ -d "/etc/init.d/modules.d" ]; then
+			for conf in /etc/init.d/modules.d/*; do
+				load_modules "${conf}"
+			done
+		fi
 		;;
 esac
 
