shell scripts clean up and formatting (#874)

diff --git a/general/overlay/etc/init.d/S01syslogd b/general/overlay/etc/init.d/S01syslogd
--- a/general/overlay/etc/init.d/S01syslogd
+++ b/general/overlay/etc/init.d/S01syslogd
@@ -11,44 +11,44 @@ SYSLOGD_ARGS="-C64 -t"
 # BusyBox' syslogd does not create a pidfile, so pass "-n" in the command line
 # and use "-m" to instruct start-stop-daemon to create one.
 start() {
-  printf 'Starting %s: ' "$DAEMON"
-  # shellcheck disable=SC2086 # we need the word splitting
-  start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "/sbin/$DAEMON" -- -n $SYSLOGD_ARGS
-  status=$?
-  if [ "$status" -eq 0 ]; then
-    echo "OK"
-  else
-    echo "FAIL"
-  fi
-  return "$status"
+	printf 'Starting %s: ' "$DAEMON"
+	# shellcheck disable=SC2086 # we need the word splitting
+	start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "/sbin/$DAEMON" -- -n $SYSLOGD_ARGS
+	status=$?
+	if [ "$status" -eq 0 ]; then
+		echo "OK"
+	else
+		echo "FAIL"
+	fi
+	return "$status"
 }
 
 stop() {
-  printf 'Stopping %s: ' "$DAEMON"
-  start-stop-daemon -K -q -p "$PIDFILE"
-  status=$?
-  if [ "$status" -eq 0 ]; then
-    rm -f "$PIDFILE"
-    echo "OK"
-  else
-    echo "FAIL"
-  fi
-  return "$status"
-}
-
-restart() {
-  stop
-  sleep 1
-  start
+	printf 'Stopping %s: ' "$DAEMON"
+	start-stop-daemon -K -q -p "$PIDFILE"
+	status=$?
+	if [ "$status" -eq 0 ]; then
+		rm -f "$PIDFILE"
+		echo "OK"
+	else
+		echo "FAIL"
+	fi
+	return "$status"
 }
 
 case "$1" in
-  start|stop|restart)
-    "$1" ;;
-  reload)
-    # Restart, since there is no true "reload" feature.
-    restart ;;
-  *)
-    echo "Usage: $0 {start|stop|restart|reload}"
-    exit 1
+	start|stop)
+		"$1"
+		;;
+
+	restart|reload)
+		stop
+		sleep 1
+		start
+		;;
+
+	*)
+		echo "Usage: $0 {start|stop|restart|reload}"
+		exit 1
+		;;
 esac
diff --git a/general/overlay/etc/init.d/S49ntpd b/general/overlay/etc/init.d/S49ntpd
--- a/general/overlay/etc/init.d/S49ntpd
+++ b/general/overlay/etc/init.d/S49ntpd
@@ -11,43 +11,44 @@ NTPD_ARGS="-n"
 # BusyBox' ntpd does not create a pidfile, so pass "-n" in the command line
 # and use "-m" to instruct start-stop-daemon to create one.
 start() {
-  printf 'Starting %s: ' "$DAEMON"
-  # shellcheck disable=SC2086 # we need the word splitting
-  start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "/usr/sbin/$DAEMON" -- $NTPD_ARGS
-  status=$?
-  if [ "$status" -eq 0 ]; then
-    echo "OK"
-  else
-    echo "FAIL"
-  fi
-  return "$status"
+	printf 'Starting %s: ' "$DAEMON"
+	# shellcheck disable=SC2086 # we need the word splitting
+	start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "/usr/sbin/$DAEMON" -- $NTPD_ARGS
+	status=$?
+	if [ "$status" -eq 0 ]; then
+		echo "OK"
+	else
+		echo "FAIL"
+	fi
+	return "$status"
 }
 
 stop() {
-  printf 'Stopping %s: ' "$DAEMON"
-  start-stop-daemon -K -q -p "$PIDFILE"
-  status=$?
-  if [ "$status" -eq 0 ]; then
-    rm -f "$PIDFILE"
-    echo "OK"
-  else
-    echo "FAIL"
-  fi
-  return "$status"
-}
-
-restart() {
-  stop
-  sleep 1
-  start
+	printf 'Stopping %s: ' "$DAEMON"
+	start-stop-daemon -K -q -p "$PIDFILE"
+	status=$?
+	if [ "$status" -eq 0 ]; then
+		rm -f "$PIDFILE"
+		echo "OK"
+	else
+		echo "FAIL"
+	fi
+	return "$status"
 }
 
 case "$1" in
-  start|stop|restart)
-    "$1" ;;
-  reload)
-    restart ;;
-  *)
-    echo "Usage: $0 {start|stop|restart|reload}"
-    exit 1
+	start|stop)
+		"$1"
+		;;
+
+	reload)
+		stop
+		sleep 1
+		start
+		;;
+
+	*)
+		echo "Usage: $0 {start|stop|restart|reload}"
+		exit 1
+		;;
 esac
