mdev: remove dependency on common

diff --git a/overlay/usr/lib/mdev/automount b/overlay/usr/lib/mdev/automount
--- a/overlay/usr/lib/mdev/automount
+++ b/overlay/usr/lib/mdev/automount
@@ -1,15 +1,15 @@
 #!/bin/sh
 
 if [ -z "$MDEV" ]; then
-	echo "No device name to mount!" >&2
+	echo -c 160 -e "No device name to mount!" >&2
 	exit 1
 fi
 
 device_node="/dev/$MDEV"
-echo "Device node: $device_node"
+echo -c 240 -e "- Device node: $device_node"
 
 mount_point="/mnt/$MDEV"
-echo "Mount point: $mount_point"
+echo -c 240 -e "- Mount point: $mount_point"
 
 diag="$mount_point/.diag"
 run="$mount_point/run.sh"
@@ -23,12 +23,12 @@ run_once_flag="${run_once%.sh}.done"
 cleanup() {
 	if [ -d "$mount_point" ]; then
 		if rm -r "$mount_point"; then
-			echo "Removed mount point $mount_point"
+			echo -c 240 -e "- Removed mount point $mount_point"
 		else
-			echo "Failed to remove mount point $mount_point"
+			echo -c 142 -e "Failed to remove mount point $mount_point" >&2
 		fi
 	else
-		echo "No mount point $mount_point found"
+		echo -c 240 -e "- No mount point $mount_point found"
 	fi
 }
 
@@ -37,41 +37,41 @@ do_fsck() {
 	fsck_status=$?
 
 	echo "$res" | while IFS= read -r line; do
-		echo "$line"
+		echo -c 240 -e "- $line"
 	done
 
 	if [ "$fsck_status" -eq 0 ]; then
-		echo "fsck check succeeded on $device_node"
+		echo -c 240 -e "- fsck check succeeded on $device_node"
 	else
-		echo "fsck check failed on $device_node"
+		echo -c 142 -e "fsck check failed on $device_node" >&2
 
 		if [ "$fsck_status" -eq 8 ] || [ "$fsck_status" -eq 16 ] ||
 			[ "$fsck_status" -eq 32 ] || [ "$fsck_status" -eq 128 ]; then
-			echo "Critical fsck error with exit status $fsck_status, mounting process aborted"
+			echo -c 142 -e "Critical fsck error with exit status $fsck_status, mounting process aborted" >&2
 			return 1
 		else
-			echo "Non-critical fsck error with exit status $fsck_status, continuing"
+			echo -c 142 -e "Non-critical fsck error with exit status $fsck_status, continuing" >&2
 		fi
 	fi
 }
 
 do_mount() {
 	if mkdir -p "$mount_point"; then
-		echo "Created mount point $mount_point"
+		echo -c 240 -e "- Created mount point $mount_point"
 	else
-		echo "Cannot create mount point $mount_point"
+		echo -c 142 -e "Cannot create mount point $mount_point" >&2
 		return 1
 	fi
 
 	if ! do_fsck; then
-		echo "Failed to fsck $device_node"
+		echo -c 142 -e "Failed to fsck $device_node" >&2
 		return 1
 	fi
 
 	if mount -t auto -o noatime,sync "$device_node" "$mount_point"; then
-		echo "Mounted $device_node to $mount_point"
+		echo -c 240 -e "- Mounted $device_node to $mount_point"
 	else
-		echo "Failed to mount $device_node to $mount_point"
+		echo -c 142 -e "Failed to mount $device_node to $mount_point" >&2
 		cleanup
 		return 1
 	fi
@@ -83,20 +83,20 @@ do_mount() {
 
 do_umount() {
 	if lsof | grep -q "$mount_point"; then
-		echo "Killing processes that are using $mount_point"
+		echo -c 240 -e "- Killing processes that are using $mount_point"
 		lsof | awk "/$mount_point/{print \$1}" | xargs kill -9
 	else
-		echo "No processes are using $mount_point"
+		echo -c 240 -e "- No processes are using $mount_point"
 	fi
 
 	if grep -qs "^$device_node " /proc/mounts; then
 		if umount -l "$mount_point"; then
-			echo "Unmounted $mount_point"
+			echo -c 240 -e "- Unmounted $mount_point"
 		else
-			echo "Failed to unmount $mount_point"
+			echo -c 142 -e "Failed to unmount $mount_point" >&2
 		fi
 	else
-		echo "$device_node is not mounted"
+		echo -c 240 -e "- $device_node is not mounted"
 	fi
 
 	cleanup
@@ -104,9 +104,9 @@ do_umount() {
 
 do_run_always() {
 	if sh $run; then
-		echo "Executed $run script"
+		echo -c 240 -e "- Executed $run script"
 	else
-		echo "Failed to execute $run script"
+		echo -c 142 -e "Failed to execute $run script" >&2
 	fi
 }
 
@@ -120,15 +120,15 @@ do_run_diag() {
 
 do_run_once() {
 	if [ -f "$run_once_flag" ]; then
-		echo "Stop flag $run_once_flag exists"
+		echo -c 142 -e "Stop flag $run_once_flag exists" >&2
 		return 1
 	fi
 
 	if sh "$run_once"; then
 		touch "$run_once_flag"
-		echo "Executed $run_once script"
+		echo -c 240 -e "- Executed $run_once script"
 	else
-		echo "Failed to execute $run_once script"
+		echo -c 142 -e "Failed to execute $run_once script" >&2
 	fi
 }
 
