daynightd: drop dependency on common

diff --git a/package/thingino-daynightd/files/daynight b/package/thingino-daynightd/files/daynight
--- a/package/thingino-daynightd/files/daynight
+++ b/package/thingino-daynightd/files/daynight
@@ -1,6 +1,20 @@
 #!/bin/sh
 
-. /usr/share/common
+singleton() {
+	if [ -z "$1" ]; then
+		echo "Program name is missing" >&2
+		exit 1
+	fi
+
+	local appname pids
+
+	appname=$(basename "$1")
+	pids=$(pidof -o %PPID "$appname")
+	if [ -n "$pids" ]; then
+		echo "$appname is already running with PIDs $pids. Exiting" >&2
+		exit 1
+	fi
+}
 
 singleton $0
 
@@ -9,79 +23,79 @@ MODE_FILE="/tmp/nightmode.txt"
 
 controls_color() {
 	if [ "true" != "$day_night_color" ]; then
-		echo_warning "Color not enabled"
+		echo "Color not enabled"
 		return 1
 	fi
 }
 
 controls_ircut() {
 	if [ "true" != "$day_night_ircut" ]; then
-		echo_warning "IR-CUT filter not enabled"
+		echo "IR-CUT filter not enabled"
 		return 1
 	fi
 }
 
 controls_ir850() {
 	if [ "true" != "$day_night_ir850" ]; then
-		echo_warning "IR LED 850mn not enabled"
+		echo "IR LED 850mn not enabled"
 		return 1
 	fi
 
 	if [ -z "$gpio_ir850" ]; then
-		echo_warning "IR LED 850mn not configured"
+		echo "IR LED 850mn not configured"
 		return 1
 	fi
 }
 
 controls_ir940() {
 	if [ "true" != "$day_night_ir940" ]; then
-		echo_warning "IR LED 940mn not enabled"
+		echo "IR LED 940mn not enabled"
 		return 1
 	fi
 
 	if [ -z "$gpio_ir940" ]; then
-		echo_warning "IR LED 940mn not configured"
+		echo "IR LED 940mn not configured"
 		return 1
 	fi
 }
 
 controls_white() {
 	if [ "true" != "$day_night_white" ]; then
-		echo_warning "White Light not enabled"
+		echo "White Light not enabled"
 		return 1
 	fi
 
 	if [ -z "$gpio_white" ]; then
-		echo_warning "White Light not configured"
+		echo "White Light not configured"
 		return 1
 	fi
 }
 
 switch_to_day() {
-	echo_info "Switching to day mode..."
+	echo "Switching to day mode..."
 
 	if controls_ircut; then
-		echo_info "set IR-CUT filter"
+		echo "set IR-CUT filter"
 		ircut on &
 	fi
 
 	if controls_ir850; then
-		echo_info "turn IR LED 850mn OFF"
+		echo "turn IR LED 850mn OFF"
 		light ir850 off &
 	fi
 
 	if controls_ir940; then
-		echo_info "turn IR LED 940mn OFF"
+		echo "turn IR LED 940mn OFF"
 		light ir940 off &
 	fi
 
 	if controls_white; then
-		echo_info "turn White Light OFF"
+		echo "turn White Light OFF"
 		light white off &
 	fi
 
 	if controls_color; then
-		echo_info "switch to color mode"
+		echo "switch to color mode"
 		color on &
 	fi
 
@@ -89,30 +103,30 @@ switch_to_day() {
 }
 
 switch_to_night() {
-	echo_info "Switched to night mode"
+	echo "Switched to night mode"
 
 	if controls_color; then
-		echo_info "switch to monocrome mode"
+		echo "switch to monocrome mode"
 		color off &
 	fi
 
 	if controls_ircut; then
-		echo_info "remove IR-CUT filter"
+		echo "remove IR-CUT filter"
 		ircut off &
 	fi
 
 	if controls_ir850; then
-		echo_info "turn IR LED 850mn ON"
+		echo "turn IR LED 850mn ON"
 		light ir850 on &
 	fi
 
 	if controls_ir940; then
-		echo_info "- turn IR LED 940mn ON"
+		echo "- turn IR LED 940mn ON"
 		light ir940 on &
 	fi
 
 	if controls_white; then
-		echo_info "- turn White Light ON"
+		echo "- turn White Light ON"
 		light white on &
 	fi
 
@@ -146,16 +160,16 @@ case "$1" in
 		echo $state
 		;;
 	*)
-		echo_info "value: $(cat /run/daynight/value 2>/dev/null)"
-		echo_info "day_night_min: $(jct /etc/daynightd.json get brightness.threshold_low)"
-		echo_info "day_night_max: $(jct /etc/daynightd.json get brightness.threshold_high)"
-		echo_info "state: $state"
+		echo "value: $(cat /run/daynight/value 2>/dev/null)"
+		echo "day_night_min: $(jct /etc/daynightd.json get brightness.threshold_low)"
+		echo "day_night_max: $(jct /etc/daynightd.json get brightness.threshold_high)"
+		echo "state: $state"
 		if [ "day" = "$state" ]; then
-			echo_info "active range: 0-$day_night_max"
+			echo "active range: 0-$day_night_max"
 		else
-			echo_info "active range: $day_night_min-Infinity"
+			echo "active range: $day_night_min-Infinity"
 		fi
-		echo_info "value: $value"
+		echo "value: $value"
 		;;
 esac
 
