scripts: small touch ups

diff --git a/package/thingino-diag/files/usb-role b/package/thingino-diag/files/usb-role
--- a/package/thingino-diag/files/usb-role
+++ b/package/thingino-diag/files/usb-role
@@ -2,30 +2,30 @@
 
 # Function to display the help message
 show_help() {
-	echo "Usage: $0 [-m host|device]"
-	echo ""
-	echo "Options:"
-	echo "  -m    Set the USB mode to either 'host' or 'device'."
-	echo "  -h    Display this help message."
+	echo "Usage: $0 [-m host|device]
+Options:
+	-m    Set the USB mode to either 'host' or 'device'.
+	-h    Display this help message.
+" >&2
 	exit 0
 }
 
 # Function to set USB to host mode
 set_host_mode() {
-	echo "Setting USB to host mode"
+	echo "Set USB to host mode" >&2
 	devmem 0x10000040 32 0x0b000096
 }
 
 # Function to set USB to device mode for t20
 set_device_mode_t20() {
-	echo "Setting USB to device mode for t20"
+	echo "Set USB to device mode for t20" >&2
 	devmem 0x10000040 32 0x0b800096
 	devmem 0x13500000 32 0x001100cc
 }
 
 # Function to set USB to device mode for t31
 set_device_mode_t31() {
-	echo "Setting USB to device mode for t31"
+	echo "Set USB to device mode for t31" >&2
 	devmem 0x13500000 32 0x001100cc
 	devmem 0x10000040 32 0x0b000096
 	devmem 0x10000040 32 0x0b000FFF
@@ -36,13 +36,13 @@ display_current_mode() {
 	result=$(devmem 0x13500000 32)
 	case "$result" in
 		0x001900CC)
-			echo "Current mode: Device mode"
+			echo "Current mode: Device mode" >&2
 			;;
 		0x003800CC)
-			echo "Current mode: Host mode"
+			echo "Current mode: Host mode" >&2
 			;;
 		*)
-			echo "Unknown mode: $result"
+			echo "Unknown mode: $result" >&2
 			;;
 	esac
 }
@@ -93,7 +93,7 @@ case "$MODE" in
 		esac
 		;;
 	*)
-		echo "Invalid mode: $MODE"
+		echo "Invalid mode: $MODE" >&2
 		show_help
 		;;
 esac
diff --git a/package/thingino-gpio/files/S05gpio b/package/thingino-gpio/files/S05gpio
--- a/package/thingino-gpio/files/S05gpio
+++ b/package/thingino-gpio/files/S05gpio
@@ -11,7 +11,7 @@ VALID_STATES="high low input"
 MAX_GPIO=192
 
 start() {
-	echo " Setting GPIOs"
+	echo " Setting GPIOs" >&2
 
 	while IFS= read -r line; do
 		# Skip empty lines and comments
@@ -25,12 +25,14 @@ start() {
 			*"$state"*)
 				# pin is in valid range
 				if [ "$gpionum" -lt 0 ] || [ "$gpionum" -gt $MAX_GPIO ]; then
-					echo "Invalid GPIO number: $gpionum in line: $line"
+					echo "Invalid GPIO number: $gpionum in line: $line" >&2
 				else
 					gpio "$state" "$gpionum"
-					echo "GPIO $gpionum set to $state"
+					echo "GPIO $gpionum set to $state" >&2
 
-					[ -n "$3" ] && echo "Description: $3"
+					if [ -n "$3" ]; then
+						echo "Description: $3" >&2
+					fi
 				fi
 				;;
 			*)
@@ -47,8 +49,12 @@ case "$1" in
 	stop)
 		true
 		;;
+	restart)
+		start
+		;;
 	*)
-		die "Usage: $0 {start|stop}"
+		echo "Usage: $0 {start|stop|restart}"
+		exit 1
 		;;
 esac
 
