dev scripts: drop dependency on common

diff --git a/package/thingino-devscripts/files/ispmem-calc b/package/thingino-devscripts/files/ispmem-calc
--- a/package/thingino-devscripts/files/ispmem-calc
+++ b/package/thingino-devscripts/files/ispmem-calc
@@ -1,7 +1,5 @@
 #!/bin/sh
 
-. /usr/share/common
-
 cleanup() {
 	echo
 	stty sane
@@ -30,10 +28,15 @@ slider() {
 		[ "$input" = $'\e' ] && read -rsn2 input
 
 		case $input in
-			w|A) [ "$value" -lt "$max" ] && value=$(($value + $step));;
-			s|B) [ "$value" -gt "$min" ] && value=$(($value - $step));;
-			q) echo; echo "Quitting without making changes."; stty echo; exit 1;;
-			"") break;;
+			w | A) [ "$value" -lt "$max" ] && value=$(($value + $step)) ;;
+			s | B) [ "$value" -gt "$min" ] && value=$(($value - $step)) ;;
+			q)
+				echo
+				echo "Quitting without making changes."
+				stty echo
+				exit 1
+				;;
+			"") break ;;
 		esac
 	done
 
@@ -66,10 +69,15 @@ case $choice in
 	2) totalmem=64 ;;
 	3) totalmem=128 ;;
 	4) totalmem=256 ;;
-	*) echo "Invalid choice"; exit 1 ;;
+	*)
+		echo "Invalid choice"
+		exit 1
+		;;
 esac
 
-read osmem_env rmem_env < <(read_defaults)
+set -- $(read_defaults)
+osmem_env=$1
+rmem_env=$2
 
 if [ -n "$osmem_env" ] && [ -n "$rmem_env" ]; then
 	osmem_value=${osmem_env%M@*}
