init: refactor both failsafe scripts

diff --git a/package/gadget-serial/files/F02failsafe-usb b/package/gadget-serial/files/F02failsafe-usb
--- a/package/gadget-serial/files/F02failsafe-usb
+++ b/package/gadget-serial/files/F02failsafe-usb
@@ -2,24 +2,34 @@
 
 . /etc/init.d/rc.common
 
-if usb_console_en; then
-	modprobe g_serial iManufacturer="thingino" iProduct="USB Serial Console"
-	usb-role -m device
-	sleep 2
-	echo_c 208 "\nPress the [f] key to enter failsafe mode [USB Serial Console]\n" > /dev/ttyGS0
-	stty -icanon min 0 time 20 -echo < /dev/ttyGS0
-	key_gs0=$(dd bs=1 count=1 2>/dev/null < /dev/ttyGS0)
-	stty sane < /dev/ttyGS0
-	release_print > /dev/ttyGS0
+usb_console_en || exit
 
-	if [ "$key_gs0" = "f" ]; then
-		echo_c 118 "Entering failsafe mode..." > /dev/ttyGS0
-		touch /tmp/.fs
+modprobe g_serial iManufacturer="thingino" iProduct="USB Serial Console" || die "Cannot load g_serial module"
+usb-role -m device
+sleep 2
+
+echo_c 104 "\nPress the [f] key to enter failsafe mode [USB Serial Console]\n" > /dev/ttyGS0
+
+stty -icanon min 0 time 20 -echo < /dev/ttyGS0
+key=$(dd bs=1 count=1 2>/dev/null < /dev/ttyGS0)
+stty sane < /dev/ttyGS0
+
+print_release > /dev/ttyGS0
+
+if [ "$key" = "f" ]; then
+	echo_c 118 "Failsafe mode..." > /dev/ttyGS0
+	touch /tmp/.fs
+	. /etc/profile >/dev/ttyGS0 2>&1 < /dev/ttyGS0
+	while :; do setsid /sbin/getty -n -l /bin/sh ttyGS0 0 vt100; sleep 1; done &
+else
+	/etc/init.d/rcS > /dev/ttyGS0 2>&1
+	if is_debug_mode; then
 		. /etc/profile >/dev/ttyGS0 2>&1 < /dev/ttyGS0
-		while true; do setsid /sbin/getty -n -l /bin/sh ttyGS0 0 vt100; sleep 1; done &
+		cmd="-n -l /bin/sh"
 	else
-		/etc/init.d/rcS > /dev/ttyGS0 2>&1
-		[ "$(get debug)" = "1" ] && { . /etc/profile >/dev/ttyGS0 2>&1 < /dev/ttyGS0; cmd="-n -l /bin/sh"; } || cmd="-L"
-		while true; do setsid /sbin/getty $cmd ttyGS0 0 vt100; sleep 1; done &
+		cmd="-L"
 	fi
+	while :; do setsid /sbin/getty $cmd ttyGS0 0 vt100; sleep 1; done &
 fi
+
+exit 0
