init: improve jffs2 error handling

diff --git a/overlay/lower/init b/overlay/lower/init
--- a/overlay/lower/init
+++ b/overlay/lower/init
@@ -16,18 +16,23 @@ if ! grep -q 'root=.*nfs\|mmcblk\|ram' /proc/cmdline; then
 	else
 		mtdblkdev=$(awk -F ':' '/rootfs_data/ {print $1}' /proc/mtd | sed 's/mtd/mtdblock/')
 		mtdchrdev=$(grep 'rootfs_data' /proc/mtd | cut -d: -f1)
-		mount -t jffs2 /dev/${mtdblkdev} /overlay
 
-		if [ $? -ne 0 ] || { dmesg | grep "jffs2.*: Magic bitmask.*not found" >/dev/null 2>&1; }; then
-			echo "jffs2 health check error, format required!"
+		if [ "$(xxd -l 2 -p /dev/${mtdblkdev})" != "8519" ]; then
+			echo "Invalid JFFS2 header, or /dev/${mtdblkdev} is not formatted as JFFS2."
 			flash_eraseall -j /dev/${mtdchrdev}
-			echo "Done! Remounting..."
-			mount -t jffs2 /dev/${mtdblkdev} /overlay || mount -t tmpfs tmpfs /overlay || exit
-			if ! cat /proc/mounts | grep ${mtdblkdev}; then
-				echo "--------------------------------"
-				echo "Crash - your flash in the trash!"
-				echo "--------------------------------"
-			fi
+			echo "Reformatting done. Attempting to remount..."
+		fi
+
+		if mount -t jffs2 /dev/${mtdblkdev} /overlay; then
+			echo "JFFS2 filesystem mounted successfully."
+		else
+			echo "Failed to mount JFFS2, trying fallback to tmpfs..."
+			mount -t tmpfs tmpfs /overlay || exit
+		fi
+
+		if ! cat /proc/mounts | grep -q ${mtdblkdev}; then
+			echo "ERROR: Unable to mount overlay, using tmpfs..."
+			exit 1
 		fi
 	fi
 
