simplify init

diff --git a/overlay/lower/init b/overlay/lower/init
--- a/overlay/lower/init
+++ b/overlay/lower/init
@@ -2,13 +2,13 @@
 
 on_exit() {
 	mountpoint -q /proc && umount /proc
-	exec /sbin/init $*
+	exec /sbin/init "$@"
 }
 
-trap on_exit 0
+trap 'on_exit "$@"' EXIT
 
-mount -t proc proc /proc || exit
-grep -q overlay /proc/filesystems || exit
+mount -t proc proc /proc || exit 1
+grep -q overlay /proc/filesystems || exit 1
 
 if ! grep -q 'root=.*nfs\|mmcblk\|ram' /proc/cmdline; then
 	if grep -q ubifs /proc/cmdline; then
@@ -17,29 +17,25 @@ if ! grep -q 'root=.*nfs\|mmcblk\|ram' /proc/cmdline; then
 		mtdblkdev=$(awk -F ':' '/rootfs_data/ {print $1}' /proc/mtd | sed 's/mtd/mtdblock/')
 		mtdchrdev=$(grep 'rootfs_data' /proc/mtd | cut -d: -f1)
 
-		if [ "$(xxd -l 2 -p /dev/${mtdblkdev})" != "8519" ]; then
-			echo "Init: Invalid JFFS2 header, or /dev/${mtdblkdev} is not formatted as JFFS2. Formatting Overlay partition..."
+		mount -t jffs2 /dev/${mtdblkdev} /overlay
+
+		if [ $? -ne 0 ] || dmesg | grep -q "jffs2.*: Magic bitmask.*not found"; then
+			echo "Init: Invalid JFFS2 blocks detected. Formatting required."
+			umount /overlay
 			flash_eraseall -j /dev/${mtdchrdev}
-			echo "Init: Overlay formatting done. Attempting to remount..."
-		fi
+			mount -t jffs2 /dev/${mtdblkdev} /overlay || mount -t tmpfs tmpfs /overlay || exit 1
 
-		if mount -t jffs2 /dev/${mtdblkdev} /overlay; then
-			echo "Init: Overlay mounted as JFFS2 successfully."
-		else
-			echo "Init: Failed to mount Overlay as JFFS2, fallback to tmpfs..."
-			mount -t tmpfs tmpfs /overlay || exit
-		fi
-
-		if ! cat /proc/mounts | grep -q ${mtdblkdev}; then
-			echo "Init: ERROR: Unable to mount Overlay!"
-			exit 1
+			if ! grep -q ${mtdblkdev} /proc/mounts; then
+				echo "Init: ERROR: Failed to mount Overlay!"
+				exit 1
+			fi
 		fi
 	fi
 
 	if grep -q overlayfs /proc/filesystems; then
 		mount -t overlayfs overlayfs -o lowerdir=/,upperdir=/overlay,ro /mnt || {
 			umount /overlay
-			exit
+			exit 1
 		}
 	else
 		overlay_rootdir=/overlay/root
@@ -47,7 +43,7 @@ if ! grep -q 'root=.*nfs\|mmcblk\|ram' /proc/cmdline; then
 		mkdir -p ${overlay_rootdir} ${overlay_workdir}
 		mount -t overlay overlay -o lowerdir=/,upperdir=${overlay_rootdir},workdir=${overlay_workdir} /mnt || {
 			umount /overlay
-			exit
+			exit 1
 		}
 	fi
 
