init: fix config path

diff --git a/overlay/lower/init b/overlay/lower/init
--- a/overlay/lower/init
+++ b/overlay/lower/init
@@ -13,16 +13,13 @@ grep -q overlay /proc/filesystems || exit 1
 
 configfs_dev=$(awk '$4 ~ /"config"/ {gsub(":","",$1); print "/dev/mtdblock" substr($1,4)}' /proc/mtd)
 if [ -n "$configfs_dev" ]; then
-	if ! grep -q " /config " /proc/mounts; then
-		mount -t ext2 "$configfs_dev" /config
-		if ! grep -q " /config " /proc/mounts; then
-			echo "Init: Invalid config partition detected. Formatting..."
-			mkfs.ext2 -F -b 1024 -i 8192 -m 0 -L config "$configfs_dev"
-			mount -t ext2 "$configfs_dev" /config
-			if ! grep -q " /config " /proc/mounts; then
-				echo "Init: ERROR: Failed to mount config partition after format!"
-				exit 1
-			fi
+	mount -t ext2 "$configfs_dev" /etc/config
+	if ! grep -q " /etc/config " /proc/mounts; then
+		echo "Init: Invalid config partition detected. Formatting..."
+		mkfs.ext2 -F -b 1024 -i 8192 -m 0 -L config "$configfs_dev"
+		mount -t ext2 "$configfs_dev" /etc/config
+		if ! grep -q " /etc/config " /proc/mounts; then
+			echo "Init: ERROR: Failed to mount config partition after format!"
 		fi
 	fi
 fi
@@ -67,4 +64,4 @@ pivot_root /mnt /mnt/rom
 mount -o noatime,move /rom/proc /proc
 mount -o noatime,move /rom/dev /dev
 mount -o noatime,move /rom/overlay /overlay
-mount -o noatime,move /rom/config /config
+mount -o noatime,move /rom/etc/config /etc/config
