usbnet: drop dependency on common

diff --git a/package/usbnet/files/S36cdcnet b/package/usbnet/files/S36cdcnet
--- a/package/usbnet/files/S36cdcnet
+++ b/package/usbnet/files/S36cdcnet
@@ -1,8 +1,24 @@
 #!/bin/sh
 
-. /usr/share/common
-
 CNET=172.16.0.1
+
+decrement_mac() {
+	local mac last_byte_dec
+
+	mac=$ethaddr
+	if [ -z "$mac" ]; then
+		echo "Error: MAC address not found" >&2
+		exit 1
+	fi
+
+	last_byte_dec=$((0x${mac##*:} - 1))
+	if [ $last_byte_dec -lt 0 ]; then
+		echo "Error: MAC address cannot be decremented below 00" >&2
+		exit 1
+	fi
+
+	ethaddr=$(printf "%s:%02x" "${mac%:*}" "$last_byte_dec")
+}
 
 start() {
 	starting
