formatting

diff --git a/general/overlay/init b/general/overlay/init
--- a/general/overlay/init
+++ b/general/overlay/init
@@ -17,17 +17,17 @@ else
   mtdblkdev=`awk -F ':' '/rootfs_data/ {print $1}' /proc/mtd | sed 's/mtd/mtdblock/'`
   mtdchrdev=`grep 'rootfs_data' /proc/mtd | cut -d: -f1`
   mount -t jffs2 /dev/${mtdblkdev} /overlay
-  
+
   if [ $? -ne 0 ] || { dmesg | grep "jffs2.*: Magic bitmask.*not found" > /dev/null 2>&1; } then
-	echo "jffs2 health check error, format required!"
-	flash_eraseall -j /dev/${mtdchrdev}
-	echo "Done! Remounting..."
-	mount -t jffs2 /dev/${mtdblkdev} /overlay || mount -t tmpfs tmpfs /overlay || exit
-	if ! cat /proc/mounts | grep ${mtdblkdev}; then
-	  echo "--------------------------------"
-	  echo "Crash - your flash in the trash!"
-	  echo "--------------------------------"
-	fi
+    echo "jffs2 health check error, format required!"
+    flash_eraseall -j /dev/${mtdchrdev}
+    echo "Done! Remounting..."
+    mount -t jffs2 /dev/${mtdblkdev} /overlay || mount -t tmpfs tmpfs /overlay || exit
+    if ! cat /proc/mounts | grep ${mtdblkdev}; then
+      echo "--------------------------------"
+      echo "Crash - your flash in the trash!"
+      echo "--------------------------------"
+    fi
   fi
 fi
 
