simplify

diff --git a/package/prudynt-t/files/S95prudynt b/package/prudynt-t/files/S95prudynt
--- a/package/prudynt-t/files/S95prudynt
+++ b/package/prudynt-t/files/S95prudynt
@@ -8,14 +8,12 @@ load_daemon() {
 	printf 'Starting %s: ' $DAEMON
 	[ -f $DAEMON_PATH/$DAEMON ] || echo -en "DISABLED, "
 	start-stop-daemon -b -m -S -p $PIDFILE -x \
-	/usr/bin/env -- LD_PRELOAD=/usr/lib/libimp_control.so $DAEMON_PATH/$DAEMON
-	status=$?
-	if [ "$status" -eq 0 ]; then
-		echo "OK"
-	else
-		echo "FAIL"
-	fi
-	return $status
+		/usr/bin/env -- LD_PRELOAD=/usr/lib/libimp_control.so $DAEMON_PATH/$DAEMON
+	[ $? -eq 0 ] && echo "OK" || echo "FAIL"
+}
+
+restore_config() {
+
 }
 
 start() {
@@ -26,14 +24,12 @@ stop() {
 	printf 'Stopping %s: ' $DAEMON
 	[ -f "$DAEMON_PATH/$DAEMON" ] || echo -en "DISABLED, "
 	start-stop-daemon -K -q -p $PIDFILE
-	status=$?
-	if [ "$status" -eq 0 ]; then
+	if [ $? -eq 0 ]; then
 		rm -f $PIDFILE
 		echo "OK"
 	else
 		echo "FAIL"
 	fi
-	return $status
 }
 
 restart() {
