refactor to read data from new config format

diff --git a/package/prudynt-t/files/S96record b/package/prudynt-t/files/S96record
--- a/package/prudynt-t/files/S96record
+++ b/package/prudynt-t/files/S96record
@@ -3,60 +3,60 @@
 DAEMON=openRTSP
 ENABLED=false
 
-stream0fps=$(grep "fps:" /etc/prudynt.cfg | head -1 | awk '{print $2}' | tr -d ';')
-stream0width=$(grep "width:" /etc/prudynt.cfg | head -1 | awk '{print $2}' | tr -d ';')
-stream0height=$(grep "height:" /etc/prudynt.cfg | head -1 | awk '{print $2}' | tr -d ';')
-rtsp_username=$(grep "username:" /etc/prudynt.cfg | awk '{print $2}' | tr -d '";')
-rtsp_password=$(grep "password:" /etc/prudynt.cfg | awk '{print $2}' | tr -d '";')
+die() {
+	echo "$1. Exit."
+	exit 1
+}
+
+read_config() {
+	sed -nE "s/^.*$1:\s*\"?(\w+)\"?;.*$/\1/p" /etc/prudynt.cfg | head -1
+}
+
+stream0fps=$(read_config "fps")
+stream0width=$(read_config "width")
+stream0height=$(read_config "height")
+rtsp_username=$(read_config "username")
+rtsp_password=$(read_config "password")
 
 file_prefix="thingino-"
 record_path="/mnt/mmcblk0p1"
 record_interval=60
 
 start() {
-if [ "$ENABLED" = "true" ]; then
-	echo -n "Starting RTSP recorder: "
+	if [ "$ENABLED" = "true" ]; then
+		echo -n "Starting RTSP recorder: "
 
-	if [ "$record_path" = "/mnt/mmcblk0p1" ] && ! mount | grep -q "$record_path"; then
-		echo "Record path is set to /mnt/mmcblk0p1, SD card is not mounted, exit."
-		exit 1
-	fi
+		if [ "$record_path" = "/mnt/mmcblk0p1" ] && ! grep -q "$record_path" /proc/mounts; then
+			die "Record path is set to $record_path but SD card is not mounted"
+		fi
 
-	if [ ! -d "$record_path" ]; then
-		echo "Record path does not exist, exit"
-		exit 1
-	fi
+		if [ ! -d "$record_path" ]; then
+			die "Record path does not exist"
+		fi
 
-	if ! pidof prudynt >/dev/null; then
-		echo "Prudynt is not running. Unable to record RTSP stream."
-		exit 1
-	fi
+		if ! pidof prudynt >/dev/null; then
+			die "Prudynt is not running. Unable to record RTSP stream"
+		fi
 
-	if [ ! -d "$record_path" ]; then
-		mkdir -p "$record_path"
-	fi
+		[ ! -d "$record_path" ] && mkdir -p "$record_path"
+		cd "$record_path" || die "Cannot change directory to $record_path"
 
-	cd "$record_path"
+		if pidof $DAEMON >/dev/null; then
+			die "RTSP recorder already running"
+		fi
 
-	if ! pidof $DAEMON >/dev/null; then
 		sleep 2
-		start-stop-daemon -b -S -q -x ${DAEMON} -- -u "$rtsp_username" "$rtsp_password" -w "$stream0width" -h \ 
-			"$stream0height" -f "$stream0fps" -P $record_interval -q -v -b 1048576 -t -H -F "$file_prefix" "rtsp://127.0.0.1/unicast"
+		start-stop-daemon -b -S -q -x ${DAEMON} -- -u "$rtsp_username" "$rtsp_password" \
+			-w "$stream0width" -h "$stream0height" -f "$stream0fps" -P $record_interval \
+			-q -v -b 1048576 -t -H -F "$file_prefix" rtsp://127.0.0.1/ch0
 		echo "OK"
-	else
-		echo "RTSP recorder already running."
 	fi
-fi
 }
 
 stop() {
 	echo -n "Stopping RTSP recorder: "
-
-	if start-stop-daemon -K -q -s KILL -n "$DAEMON"; then
-		echo "OK"
-	else
-		echo "FAIL"
-	fi
+	start-stop-daemon -K -q -s KILL -n "$DAEMON"
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
 }
 
 case "$1" in
