no-nonsense syntax

diff --git a/overlay/usr/sbin/send2email b/overlay/usr/sbin/send2email
--- a/overlay/usr/sbin/send2email
+++ b/overlay/usr/sbin/send2email
@@ -92,7 +92,10 @@ command="${command} --user '${email_smtp_username}:${email_smtp_password}'"
 
 if [ "true" = "$email_attach_snapshot" ]; then
 	snapshot=/tmp/snapshot.jpg
-	[ ! -f "$snapshot" ] && log "Cannot find a snapshot" && exit 3
+	if [ ! -f "$snapshot" ]; then
+		log "Cannot find a snapshot"
+		exit 3
+	fi
 
 	email_body="$(date -R)"
 	command="${command} -H 'Subject: ${email_subject}'"
