simplify snapshot handling

diff --git a/overlay/usr/sbin/send2telegram b/overlay/usr/sbin/send2telegram
--- a/overlay/usr/sbin/send2telegram
+++ b/overlay/usr/sbin/send2telegram
@@ -79,18 +79,8 @@ if [ -z "$telegram_message" ]; then
 	telegram_message="$(echo "$telegram_caption" | sed "s/%hostname/$(hostname -s)/;s/%datetime/$(date +"%F %T")/")"
 
 	if [ -z "$telegram_photo" ]; then
-		if [ "true" = "$telegram_use_heif" ] && [ "h265" = "$(yaml-cli -g .video0.codec)" ]; then
-			snapshot=/tmp/snapshot4cron.heif
-			snapshot4cron -r
-		else
-			snapshot=/tmp/snapshot4cron.jpg
-			snapshot4cron
-		fi
-
-		if [ ! -f "$snapshot" ]; then
-			log "Cannot find a snapshot"
-			exit 3
-		fi
+		snapshot=/tmp/snapshot.jpg
+		[ ! -f "$snapshot" ] && log "Cannot find a snapshot" && exit 3
 
 		telegram_photo=$snapshot
 	fi
diff --git a/overlay/usr/sbin/send2yadisk b/overlay/usr/sbin/send2yadisk
--- a/overlay/usr/sbin/send2yadisk
+++ b/overlay/usr/sbin/send2yadisk
@@ -50,18 +50,8 @@ if [ "false" = "$yadisk_enabled" ]; then
 fi
 
 if [ -z "$yadisk_file" ]; then
-	if [ "true" = "$yadisk_use_heif" ] && [ "h265" = "$(yaml-cli -g .video0.codec)" ]; then
-		snapshot=/tmp/snapshot4cron.heif
-		snapshot4cron -r
-	else
-		snapshot=/tmp/snapshot4cron.jpg
-		snapshot4cron
-	fi
-
-	if [ ! -f "$snapshot" ]; then
-		log "Cannot find a snapshot"
-		exit 3
-	fi
+	snapshot=/tmp/snapshot.jpg
+	[ ! -f "$snapshot" ] && log "Cannot find a snapshot" && exit 3
 
 	yadisk_file=$snapshot
 fi
