workaround for sending snaphots to telegram

diff --git a/overlay/usr/sbin/send2telegram b/overlay/usr/sbin/send2telegram
--- a/overlay/usr/sbin/send2telegram
+++ b/overlay/usr/sbin/send2telegram
@@ -80,9 +80,14 @@ if [ -z "$telegram_message" ]; then
 
 	if [ -z "$telegram_photo" ]; then
 		snapshot=/tmp/snapshot.jpg
-		[ ! -f "$snapshot" ] && log "Cannot find a snapshot" && exit 3
+		if [ ! -f "$snapshot" ]; then
+			log "Cannot find a snapshot"
+			exit 3
+		fi
 
-		telegram_photo=$snapshot
+		telegram_photo=$(mktemp -u /tmp/snapshot-XXXXXX).jpg
+		delete_tempfile="true"
+		cp $snapshot $telegram_photo
 	fi
 fi
 
@@ -132,6 +137,7 @@ else
 	eval "$command4" >> "$LOG_FILE" 2>&1
 fi
 
+[ "true" = "$delete_tempfile" ]  && [ -f "$telegram_photo" ] && rm "$telegram_photo"
 [ "true" = "$verbose" ] && cat "$LOG_FILE"
 
 exit 0
