service: remove dependency on common

diff --git a/overlay/usr/sbin/service b/overlay/usr/sbin/service
--- a/overlay/usr/sbin/service
+++ b/overlay/usr/sbin/service
@@ -29,21 +29,21 @@ fi
 
 SCRIPT=$(ls /etc/init.d/[FKS][0-9][0-9]$SERVICE 2>/dev/null)
 if [ "list" != "$ACTION" ] && [ -z "$SCRIPT" ]; then
-	echo "Service $SERVICE not found" >&2
+	echo -c 160 -e "Service $SERVICE not found" >&2
 	exit 1
 fi
 
 case "$ACTION" in
 	start | reload | restart | force)
 		if ! $SCRIPT $ACTION; then
-			echo "Failed to $ACTION $SERVICE" >&2
+			echo -c 160 -e "Failed to $ACTION $SERVICE" >&2
 			exit 1
 		fi
 		;;
 	stop)
 		# force stop action on a disabled script
 		if ! sh -c "$SCRIPT $ACTION"; then
-			echo "Failed to $ACTION $SERVICE" >&2
+			echo -c 160 -e "Failed to $ACTION $SERVICE" >&2
 			exit 1
 		fi
 		;;
@@ -65,7 +65,7 @@ case "$ACTION" in
 		esac
 		;;
 	*)
-		echo "Invalid action: $ACTION" >&2
+		echo -c 160 -e "Invalid action: $ACTION" >&2
 		exit 1
 		;;
 esac
