handle both local and remote upgrades

diff --git a/overlay/usr/sbin/sysupgrade b/overlay/usr/sbin/sysupgrade
--- a/overlay/usr/sbin/sysupgrade
+++ b/overlay/usr/sbin/sysupgrade
@@ -1,49 +1,99 @@
 #!/bin/sh
 
-data=/etc/os-release
-profile=$(awk -F '=' '/^IMAGE_ID=/ {print $2}' $data)
+KERNEL_MAGIC="27051956"
+U_BOOT_MAGIC="06050403"
+ROOTFS_MAGIC="68737173"
 
-if [ -z "$profile" ]; then
-	echo "Building profile is not set in $data"
-	exit 1
+die() {
+	echo "$1"
+	exit ${2:-99}
+}
+
+show_help() {
+	echo "Usage: $0 <filename> | [-f | -p]
+Where:
+  -f          full upgrade with a binary from GitHub
+  -p          partial upgrade with a binary from GitHub
+  <filename>  full or partial upgrade from a local file
+"
+	exit 0
+}
+
+while getopts fp flag; do
+	case "$flag" in
+		f)
+			upgrade="full"
+			;;
+		p)
+			upgrade="part"
+			;;
+	esac
+done
+
+if [ -z "$upgrade" ]; then
+	upgrade="local"
+	[ -z "$1" ] && show_help
+	binary_file="$1"
+else
+	data=/etc/os-release
+	profile=$(awk -F '=' '/^IMAGE_ID=/ {print $2}' $data)
+	if [ -z "$profile" ]; then
+		die "Building profile is not set in $data"
+	fi
+	binary_file=$(mktemp -u)
 fi
 
-case "$1" in
-	full)
-		mtd_dev="mtd6"
-		fw_file="/thingino-${profile}.bin"
-		;;
-	part)
-		mtd_dev="mtd5"
-		fw_file="_update/thingino-${profile}-update.bin"
-		;;
-	*)
-		echo "Usage: $0 [full|part]"
-		exit 2
+case "$upgrade" in
+	local) ;;
+
+	full | part)
+		url="https://github.com/themactep/thingino-firmware/releases/download/firmware"
+		if [ "part" = "$upgrade" ]; then
+			fw_file="_update/thingino-${profile}-update.bin"
+		else
+			fw_file="/thingino-${profile}.bin"
+		fi
+		echo "Downloading firmware from ${url}${fw_file}."
+		if ! curl -# -L -f -o $binary_file ${url}${fw_file}; then
+			die "Failed to download firmware from $url. Exiting."
+		fi
 		;;
 esac
 
+[ ! -f "$binary_file" ] && die "File $1 not found"
+
+magic=$(xxd -l 4 -p $binary_file)
+case "$magic" in
+	$U_BOOT_MAGIC)
+		fsize=$(stat -c%s $binary_file)
+		if [ "$fsize" -le $((256 * 1024)) ]; then
+			mtd_dev="mtd0"
+		else
+			mtd_dev="mtd6"
+		fi
+		;;
+	$KERNEL_MAGIC)
+		mtd_dev="mtd5"
+		;;
+	$ROOTFS_MAGIC)
+		die "We cannot flash only rootfs"
+		;;
+	*)
+		die "Unknown file"
+esac
+
 if ! grep -q "$mtd_dev" /proc/mtd; then
-	echo "Please run 'fw_setenv enable_updates true' then reboot the camera. Re-run upgrade after reboot."
-	exit 3
+	die "Please run 'fw_setenv enable_updates true' then reboot the camera. Re-run upgrade after reboot."
 fi
 
-url="https://github.com/themactep/thingino-firmware/releases/download/firmware${fw_file}"
-tmp_file=$(mktemp -u)
-echo "Downloading firmware."
-if curl -# -L -f -o $tmp_file $url; then
-	echo "Performing upgrade. Do not turn off the power!"
-	if flashcp -v $tmp_file /dev/$mtd_dev; then
-		echo "Rebooting..."
-		echo 1 > /proc/jz/watchdog/reset
-	else
-		echo "Upgrade failed!"
-		echo "You have to perform a recovery flashing before rebooting the camera!"
-		exit 13
-	fi
+echo "Performing upgrade. Do not turn off the power!"
+
+if flashcp -v $binary_file /dev/$mtd_dev; then
+	echo "Rebooting..."
+	echo 1 > /proc/jz/watchdog/reset
 else
-	echo "Failed to download firmware from $url. Exiting."
-	exit 4
+	echo "Upgrade failed!"
+	die "You have to perform a recovery flashing before rebooting the camera!"
 fi
 
 exit 0
