network scripts: remove dependency on common

diff --git a/overlay/etc/network/if-up.d/odhcp6c b/overlay/etc/network/if-up.d/odhcp6c
--- a/overlay/etc/network/if-up.d/odhcp6c
+++ b/overlay/etc/network/if-up.d/odhcp6c
@@ -3,21 +3,21 @@
 PIDFILE="/var/run/odhcp6c_$IFACE.pid"
 
 if [ ! -d "/sys/class/net/$IFACE" ]; then
-	echo "$IFACE not found" >&2
+	echo -c 160 -e "$IFACE not found" >&2
 	exit 0
 fi
 
 if [ "$(sysctl -n net.ipv6.conf.all.disable_ipv6)" -ne 0 ]; then
-	echo "IPv6 disabled globally" >&2
+	echo -c 160 -e "IPv6 disabled globally" >&2
 	exit 0
 fi
 
 if [ "true" != "$IF_DHCP_V6_ENABLED" ]; then
-	echo "DHCPv6 disabled on $IFACE" >&2
+	echo -c 160 -e "DHCPv6 disabled on $IFACE" >&2
 	exit 0
 fi
 
-echo "DHCPv6 on $IFACE"
+echo -c 240 -e "- DHCPv6 on $IFACE"
 
 start_post_up() {
 	echo -c 15 "Starting odhcp6c on $IFACE"
@@ -32,15 +32,15 @@ stop_pre_down() {
 
 	if [ -f "$PIDFILE" ]; then
 		pid=$(cat $PIDFILE)
-		echo "Running service with PID $pid"
+		echo -c 240 -e "- Running service with PID $pid"
 
-		echo "kill -9 $pid"
+		echo -c 101 -e "kill -9 $pid" >&2
 		kill -9 $pid
 
-		echo "rm -f $PIDFILE"
+		echo -c 101 -e "rm -f $PIDFILE" >&2
 		rm -f "$PIDFILE"
 	else
-		echo "Nothing to stop"
+		echo -c 240 -e "- Nothing to stop"
 	fi
 }
 
