sysctl init: remove dependency on common

diff --git a/overlay/etc/init.d/S00sysctl b/overlay/etc/init.d/S00sysctl
--- a/overlay/etc/init.d/S00sysctl
+++ b/overlay/etc/init.d/S00sysctl
@@ -1,14 +1,12 @@
 #!/bin/sh
 
-. /usr/share/common
-
 start() {
-	echo_title "Applying sysctl settings"
+	echo -c 15 "Applying sysctl settings"
 
 	if sysctl -q -p; then
-		echo_info "Sysctl settings applied"
+		echo -c 240 -e "- Sysctl settings applied"
 	else
-		echo_error "Failed to apply sysctl settings"
+		echo -c 160 -e "Failed to apply sysctl settings" >&2
 		exit 1
 	fi
 }
