formatting, refactoring

diff --git a/overlay/etc/init.d/S01syslogd b/overlay/etc/init.d/S01syslogd
--- a/overlay/etc/init.d/S01syslogd
+++ b/overlay/etc/init.d/S01syslogd
@@ -1,38 +1,27 @@
 #!/bin/sh
 
 DAEMON="syslogd"
-PIDFILE="/var/run/$DAEMON.pid"
-
-SYSLOGD_ARGS="-C64 -t"
+DAEMON_ARGS="-n -C64 -t"
+PIDFILE="/run/$DAEMON.pid"
 
 start() {
-	printf 'Starting %s: ' "$DAEMON"
-	start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "/sbin/$DAEMON" -- -n $SYSLOGD_ARGS
-	status=$?
-	if [ "$status" -eq 0 ]; then
-		echo "OK"
-	else
-		echo "FAIL"
-	fi
+	printf 'Starting %s: ' $DAEMON
+	start-stop-daemon -q -p $PIDFILE -S -b -m -x /sbin/$DAEMON -- $DAEMON_ARGS
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
 	return "$status"
 }
 
 stop() {
-	printf 'Stopping %s: ' "$DAEMON"
-	start-stop-daemon -K -q -p "$PIDFILE"
-	status=$?
-	if [ "$status" -eq 0 ]; then
-		rm -f "$PIDFILE"
-		echo "OK"
-	else
-		echo "FAIL"
-	fi
+	printf 'Stopping %s: ' $DAEMON
+	start-stop-daemon -q -p $PIDFILE -K
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
+	rm -f $PIDFILE
 	return "$status"
 }
 
 case "$1" in
 	start | stop)
-		"$1"
+		$1
 		;;
 	restart | reload)
 		stop
diff --git a/overlay/etc/init.d/S21rngd b/overlay/etc/init.d/S21rngd
--- a/overlay/etc/init.d/S21rngd
+++ b/overlay/etc/init.d/S21rngd
@@ -1,23 +1,21 @@
 #!/bin/sh
 
 NAME="rngd"
-DAEMON="/usr/sbin/${NAME}"
+DAEMON="/sbin/${NAME}"
 DAEMON_ARGS="-r /dev/urandom"
+PIDFILE="/run/$NAME.pid"
 
 start() {
 	printf "Starting ${NAME}: "
-	start-stop-daemon -S -q -x "${DAEMON}" -- ${DAEMON_ARGS}
+	start-stop-daemon -q -S -x $DAEMON -- $DAEMON_ARGS
 	[ $? = 0 ] && echo "OK" || echo "FAIL"
 }
 
 stop() {
 	printf "Stopping ${NAME}: "
-	if start-stop-daemon -K -q -x $DAEMON; then
-		rm -f "${PID_FILE}"
-		echo "OK"
-	else
-		echo "FAIL"
-	fi
+	start-stop-daemon -K -q -x $DAEMON
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
+	rm -f $PIDFILE
 }
 
 case "$1" in
diff --git a/overlay/etc/init.d/S30mdev b/overlay/etc/init.d/S30mdev
--- a/overlay/etc/init.d/S30mdev
+++ b/overlay/etc/init.d/S30mdev
@@ -5,13 +5,7 @@ case "$1" in
 		echo -n "Starting mdev: "
 		echo /sbin/mdev > /proc/sys/kernel/hotplug
 		/sbin/mdev -s
-		status=$?
-		if [ "$status" -eq 0 ]; then
-				echo "OK"
-		else
-				echo "FAIL"
-		fi
-		return "$status"
+		[ $? = 0 ] && echo "OK" || echo "FAIL"
 		;;
 
 	stop | restart | reload)
diff --git a/overlay/etc/init.d/S49ntpd b/overlay/etc/init.d/S49ntpd
--- a/overlay/etc/init.d/S49ntpd
+++ b/overlay/etc/init.d/S49ntpd
@@ -1,35 +1,20 @@
 #!/bin/sh
 
 DAEMON="ntpd"
-PIDFILE="/var/run/$DAEMON.pid"
-
-NTPD_ARGS="-n"
+DAEMON_ARGS="-n"
+PIDFILE="/run/$DAEMON.pid"
 
 start() {
-	printf 'Starting %s: ' "$DAEMON"
-
-	start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "/usr/sbin/$DAEMON" -- $NTPD_ARGS
-	status=$?
-	if [ "$status" -eq 0 ]; then
-		echo "OK"
-	else
-		echo "FAIL"
-	fi
-	return "$status"
+	printf 'Starting %s: ' $DAEMON
+	start-stop-daemon -q -p $PIDFILE -S -b -m -x /sbin/$DAEMON -- $DAEMON_ARGS
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
 }
 
 stop() {
-	printf 'Stopping %s: ' "$DAEMON"
-
-	start-stop-daemon -K -q -p "$PIDFILE"
-	status=$?
-	if [ "$status" -eq 0 ]; then
-		rm -f "$PIDFILE"
-		echo "OK"
-	else
-		echo "FAIL"
-	fi
-	return "$status"
+	printf 'Stopping %s: ' $DAEMON
+	start-stop-daemon -K -q -p $PIDFILE
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
+	rm -f $PIDFILE
 }
 
 case "$1" in
diff --git a/overlay/etc/init.d/S60crond b/overlay/etc/init.d/S60crond
--- a/overlay/etc/init.d/S60crond
+++ b/overlay/etc/init.d/S60crond
@@ -1,35 +1,23 @@
 #!/bin/sh
 
 DAEMON="crond"
-PIDFILE="/var/run/$DAEMON.pid"
+PIDFILE="/run/$DAEMON.pid"
 
 CROND_ARGS="-f -c /etc/crontabs"
 
 start() {
-	printf 'Starting %s: ' "$DAEMON"
+	printf 'Starting %s: ' $DAEMON
 	[ -f /usr/sbin/$DAEMON ] || echo -en "DISABLED, "
-	start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "/usr/sbin/$DAEMON" -- $CROND_ARGS
-	status=$?
-	if [ "$status" -eq 0 ]; then
-		echo "OK"
-	else
-		echo "FAIL"
-	fi
-	return "$status"
+	start-stop-daemon -q -p $PIDFILE -S -b -m -x /sbin/$DAEMON -- $CROND_ARGS
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
 }
 
 stop() {
-	printf 'Stopping %s: ' "$DAEMON"
+	printf 'Stopping %s: ' $DAEMON
 	[ -f /usr/sbin/$DAEMON ] || echo -en "DISABLED, "
-	start-stop-daemon -K -q -p "$PIDFILE"
-	status=$?
-	if [ "$status" -eq 0 ]; then
-		rm -f "$PIDFILE"
-		echo "OK"
-	else
-		echo "FAIL"
-	fi
-	return "$status"
+	start-stop-daemon -q -p $PIDFILE -K
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
+	rm -f $PIDFILE
 }
 
 case "$1" in
diff --git a/overlay/etc/init.d/S99watchdog b/overlay/etc/init.d/S99watchdog
--- a/overlay/etc/init.d/S99watchdog
+++ b/overlay/etc/init.d/S99watchdog
@@ -10,22 +10,15 @@ start() {
 		exit 0
 	fi
 
-	echo -n "Starting ${DAEMON}: "
-	start-stop-daemon -b -S -q -x "/sbin/${DAEMON}" -- ${WATCHDOG_ARGS}
-	if [ $? = 0 ]; then
-		echo "OK"
-	else
-		echo "FAIL"
-	fi
+	echo -n "Starting $DAEMON: "
+	start-stop-daemon -q -b -S -x /sbin/$DAEMON -- $WATCHDOG_ARGS
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
 }
 
 stop() {
 	echo "Stopping ${DAEMON}: "
-	if start-stop-daemon -K -q -s KILL -n "${DAEMON}"; then
-		echo "OK"
-	else
-		echo "FAIL"
-	fi
+	start-stop-daemon -q -K -s KILL -n $DAEMON
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
 }
 
 case "$1" in
