timezone init: remove dependency on common

diff --git a/overlay/etc/init.d/S01timezone b/overlay/etc/init.d/S01timezone
--- a/overlay/etc/init.d/S01timezone
+++ b/overlay/etc/init.d/S01timezone
@@ -8,15 +8,15 @@ start() {
 	echo -c 15 "Setting timezone"
 
 	if [ ! -f "$TZNAME_FILE" ]; then
-		echo "Timezone name not found, default to GMT"
+		echo -c 240 -e "- Timezone name not found, default to GMT"
 		echo "Etc/GMT" >"$TZNAME_FILE"
 	fi
 
-	echo "Timezone name: $(cat $TZNAME_FILE)"
+	echo -c 240 -e "- Timezone name: $(cat $TZNAME_FILE)"
 	tzname=$(cat "$TZNAME_FILE")
 
 	if [ ! -f "$TZJSON_FILE" ]; then
-		echo "$TZJSON_FILE not found" >&2
+		echo -c 160 -e "$TZJSON_FILE not found" >&2
 		exit 1
 	fi
 
@@ -25,24 +25,24 @@ start() {
 		grep -F "${tzname}:" | head -1 | cut -d: -f2-)
 
 	if [ -z "$tz" ]; then
-		echo "Timezone $tzname not found in $TZJSON_FILE" >&2
+		echo -c 160 -e "Timezone $tzname not found in $TZJSON_FILE" >&2
 		exit 1
 	fi
 
 	if [ ! -f "$TZCODE_FILE" ]; then
-		echo "Timezone code not found, default to GMT0"
+		echo -c 240 -e "- Timezone code not found, default to GMT0"
 		echo "GMT0" >"$TZCODE_FILE"
 	fi
 
 	if [ "$tz" != "$(cat $TZCODE_FILE)" ]; then
-		echo "Set timezone to $tz"
+		echo -c 240 -e "- Set timezone to $tz"
 		echo "$tz" >"$TZCODE_FILE"
 	fi
 
-	echo "Set TZ to $tz"
+	echo -c 240 -e "- Set TZ to $tz"
 	TZ="$tz"
 
-	echo "Export TZ globally"
+	echo -c 240 -e "- Export TZ globally"
 	export TZ
 }
 
