formatting, refactoring

diff --git a/overlay/etc/init.d/S05gpio b/overlay/etc/init.d/S05gpio
--- a/overlay/etc/init.d/S05gpio
+++ b/overlay/etc/init.d/S05gpio
@@ -69,14 +69,9 @@ process_config_file() {
 				success=0
 				;;
 		esac
-	done < "$CONFIG_FILE"
+	done < $CONFIG_FILE
 
-	# Check success flag
-	if [ $success -eq 1 ]; then
-		echo "OK"
-	else
-		echo "Failed"
-	fi
+	[ $success -eq 1 ] && echo "OK" || echo "Failed"
 }
 
 # Main script execution
diff --git a/overlay/etc/init.d/S05ircut b/overlay/etc/init.d/S05ircut
--- a/overlay/etc/init.d/S05ircut
+++ b/overlay/etc/init.d/S05ircut
@@ -5,14 +5,7 @@ start() {
 	ircut ~ >/dev/null 2>&1
 	sleep 0.5
 	ircut ~ >/dev/null 2>&1
-
-	status=$?
-	if [ "$status" -eq 0 ]; then
-		echo "OK"
-	else
-		echo "FAIL"
-	fi
-	return "$status"
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
 }
 
 case "$1" in
diff --git a/overlay/etc/init.d/S93telegrambot b/overlay/etc/init.d/S93telegrambot
--- a/overlay/etc/init.d/S93telegrambot
+++ b/overlay/etc/init.d/S93telegrambot
@@ -2,33 +2,18 @@
 
 DAEMON=telegram-bot
 PIDFILE=/var/run/telegrambot.pid
-TELEGRAMBOT_ARGS=""
+DAEMON_ARGS=""
 
 start() {
 	printf 'Starting %s: ' "$DAEMON"
-	start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "/usr/sbin/$DAEMON" -- $TELEGRAMBOT_ARGS
-	status=$?
-	if [ "$status" -eq 0 ]; then
-		echo "OK"
-	else
-		echo "FAIL"
-	fi
-	return "$status"
+	start-stop-daemon -b -m -S -q -p "$PIDFILE" -x /sbin/$DAEMON -- $DAEMON_ARGS
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
 }
 
 stop() {
-	if [ ! -f "$PIDFILE" ]; then
-		printf 'Stopping %s: ' "$DAEMON"
-		start-stop-daemon -K -q -p "$PIDFILE"
-		status=$?
-		if [ "$status" -eq 0 ]; then
-			rm -f "$PIDFILE"
-			echo "OK"
-		else
-			echo "FAIL"
-		fi
-		return "$status"
-	fi
+	printf 'Stopping %s: ' "$DAEMON"
+	start-stop-daemon -K -q -p "$PIDFILE"
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
 }
 
 case "$1" in
