rather let non-SDIO devices to load a driver

diff --git a/overlay/etc/init.d/S38wireless b/overlay/etc/init.d/S38wireless
--- a/overlay/etc/init.d/S38wireless
+++ b/overlay/etc/init.d/S38wireless
@@ -27,17 +27,17 @@ start() {
 		fi
 	fi
 
-	# Assume that we are SDIO, and we need to insert
-	if ! mmc 1; then
-		echo "Failed to initialize SDIO device"
-		exit 1
-	fi
-
 	if [ "$wlandev" = "rndis_host" ]; then
 		if ! modprobe usbserial; then
 			echo "Failed to load usbserial module for $modulename"
 			exit 1
 		fi
+	fi
+
+	# Assume that we are SDIO, and we need to insert
+	if ! mmc 1; then
+		echo "Failed to initialize SDIO device"
+		# exit 1
 	fi
 
 	if ! lsmod | grep -q "$modulename"; then
