refactor init scripts; formatting

diff --git a/overlay/etc/init.d/S40mdev b/overlay/etc/init.d/S40mdev
--- a/overlay/etc/init.d/S40mdev
+++ b/overlay/etc/init.d/S40mdev
@@ -2,10 +2,17 @@
 
 case "$1" in
 	start)
-		echo "Starting mdev..."
+		echo -n "Starting mdev: "
 		echo /sbin/mdev > /proc/sys/kernel/hotplug
 		/sbin/mdev -s
-		;;
+		status=$?
+		if [ "$status" -eq 0 ]; then
+				echo "OK"
+		else
+				echo "FAIL"
+		fi
+		return "$status"
+			;;
 
 	stop) ;;
 
diff --git a/overlay/etc/init.d/S93telegrambot b/overlay/etc/init.d/S93telegrambot
--- a/overlay/etc/init.d/S93telegrambot
+++ b/overlay/etc/init.d/S93telegrambot
@@ -17,16 +17,18 @@ start() {
 }
 
 stop() {
-	printf 'Stopping %s: ' "$DAEMON"
-	start-stop-daemon -K -q -p "$PIDFILE"
-	status=$?
-	if [ "$status" -eq 0 ]; then
-		rm -f "$PIDFILE"
-		echo "OK"
-	else
-		echo "FAIL"
+	if [ ! -f "$PIDFILE" ]; then
+		printf 'Stopping %s: ' "$DAEMON"
+		start-stop-daemon -K -q -p "$PIDFILE"
+		status=$?
+		if [ "$status" -eq 0 ]; then
+			rm -f "$PIDFILE"
+			echo "OK"
+		else
+			echo "FAIL"
+		fi
+		return "$status"
 	fi
-	return "$status"
 }
 
 restart() {
