mounts init: remove dependency on common

diff --git a/overlay/etc/init.d/S43mounts b/overlay/etc/init.d/S43mounts
--- a/overlay/etc/init.d/S43mounts
+++ b/overlay/etc/init.d/S43mounts
@@ -8,19 +8,19 @@ start() {
 	echo -c 15 "Mount $NFS_MOUNT"
 
 	if [ -z "$nfs_share" ]; then
-		echo "Mount share is not set"
+		echo -c 240 -e "- Mount share is not set"
 		return 0
 	fi
 
 	if mountpoint -q "$NFS_MOUNT"; then
-		echo "$NFS_MOUNT already mounted" >&2
+		echo -c 160 -e "$NFS_MOUNT already mounted" >&2
 		exit 1
 	fi
 
 	if mount -o nolock "$nfs_share" "$NFS_MOUNT"; then
-		echo "Mounted $nfs_share on $NFS_MOUNT"
+		echo -c 240 -e "- Mounted $nfs_share on $NFS_MOUNT"
 	else
-		echo "Failed to mount $nfs_share on $NFS_MOUNT" >&2
+		echo -c 160 -e "Failed to mount $nfs_share on $NFS_MOUNT" >&2
 		exit 1
 	fi
 }
@@ -29,14 +29,14 @@ stop() {
 	echo -c 15 "Unmount $NFS_MOUNT"
 
 	if ! mountpoint -q "$NFS_MOUNT"; then
-		echo "$NFS_MOUNT is not mounted"
+		echo -c 240 -e "- $NFS_MOUNT is not mounted"
 		return 0
 	fi
 
 	if umount -l "$NFS_MOUNT"; then
-		echo "$NFS_MOUNT unmounted"
+		echo -c 240 -e "- $NFS_MOUNT unmounted"
 	else
-		echo "Failed to unmount $nfs_share" >&2
+		echo -c 160 -e "Failed to unmount $nfs_share" >&2
 		exit 1
 	fi
 }
