package/spi-tmi8152: update to 4d5a666
Update spi-tmi8152 from 3edf4a4 to 4d5a666

Hash change: 3edf4a47ee79ab5d06cfabd8e2062e7c099f911e -> 4d5a666b77bc2af57cd00af20a088107c60d017e

Changelog:

  1116469: fix homing behaviour. add runaway guard.
  9663f7f: define speed per axis. raise max speed to 1000.
  4d5a666: Merge pull request #1 from themactep/main

diff --git a/package/thingino-ircut/files/daynight b/package/thingino-ircut/files/daynight
--- a/package/thingino-ircut/files/daynight
+++ b/package/thingino-ircut/files/daynight
@@ -129,11 +129,11 @@ switch_to_night() {
 [ -z "$day_night_white" ] && day_night_white="false"
 
 # determine luminance of the scene
-value=$(imp-control gettotalgain)
-if [ -z "$value" ] || [ "error" = "$value" ]; then
-	echo_error "failed to get luminance"
-	exit 1
-fi
+# value=$(imp-control gettotalgain)
+# if [ -z "$value" ] || [ "error" = "$value" ]; then
+# 	echo_error "failed to get luminance"
+# 	exit 1
+# fi
 
 reversed=1
 state=$(cat "$MODE_FILE" 2>/dev/null)
