do not unload motor.ko

diff --git a/package/motors/files/S09motor b/package/motors/files/S09motor
--- a/package/motors/files/S09motor
+++ b/package/motors/files/S09motor
@@ -59,7 +59,10 @@ start() {
 }
 
 stop() {
-	rmmod motor || die "Failed to unload motor module."
+	echo -n "Stopping motors: "
+	# FIXME: motor.ko crashes on upload
+	# rmmod motor || die "Failed to unload motor module."
+	echo "OK"
 }
 
 case "$1" in
