S09motor: add shared gpio mode

diff --git a/package/motors/files/S09motor b/package/motors/files/S09motor
--- a/package/motors/files/S09motor
+++ b/package/motors/files/S09motor
@@ -45,6 +45,7 @@ start() {
 	gpio_motor_h=$(fw_printenv -n gpio_motor_h)
 	gpio_motor_v=$(fw_printenv -n gpio_motor_v)
 	gpio_motor_invert=$(fw_printenv -n gpio_motor_invert)
+	gpio_motor_switch=$(fw_printenv -n gpio_motor_switch)
 	motor_maxstep_h=$(fw_printenv -n motor_maxstep_h)
 	motor_maxstep_v=$(fw_printenv -n motor_maxstep_v)
 	motor_speed=$(fw_printenv -n motor_speed)
@@ -52,26 +53,32 @@ start() {
 	# Check if motors are supported
 	[ -z "$motors_app"      ] && die " No motors app found"
 	[ -z "$gpio_motor_h"    ] && die " Pan motor GPIO pins are not set"
-	[ -z "$gpio_motor_v"    ] && die " Tilt motor GPIO pins are not set"
+	[ -z "$gpio_motor_switch" ] && [ -z "$gpio_motor_v" ] && die " Tilt motor GPIO pins are not set"
 	[ -z "$motor_maxstep_h" ] && die " Pan motor Steps are not set"
 	[ -z "$motor_maxstep_v" ] && die " Tilt motor Steps are not set"
 	[ -z "$motor_speed"     ] && motor_speed=900
 
 	[ "$gpio_motor_invert" = "true" ] && gpio_motor_invert_opt="invert_gpio_dir=1"
 
+	[ -n "$gpio_motor_switch" ] && direction_select_gpio="shared_gpio_mode=0 direction_select_gpio=$gpio_motor_switch"
+
 	if grep -qE "^motor" /proc/modules; then
 		info "Module motor already loaded."
 	else
 		info "Set GPIO per motor phase"
 		set_motor_phases "h" "$gpio_motor_h"
-		set_motor_phases "v" "$gpio_motor_v"
+		[ -z "$gpio_motor_switch" ] && set_motor_phases "v" "$gpio_motor_v"
 
 		info "Load module with parameters"
-		modprobe motor hmaxstep=$motor_maxstep_h vmaxstep=$motor_maxstep_v \
+
+		modprobe_args="hmaxstep=$motor_maxstep_h vmaxstep=$motor_maxstep_v \
 			hst1=$hst1 hst2=$hst2 hst3=$hst3 hst4=$hst4 \
-			vst1=$vst1 vst2=$vst2 vst3=$vst3 vst4=$vst4 \
-			$gpio_motor_invert_opt \
-			|| die "Failed to load motor module"
+			$gpio_motor_invert_opt $direction_select_gpio"
+
+		[ -z "$gpio_motor_switch" ] && modprobe_args+=" vst1=$vst1 vst2=$vst2 vst3=$vst3 vst4=$vst4"
+
+		modprobe motor $modprobe_args || die "Failed to load motor module"
+
 	fi
 
 	start_daemon
