convert more daemon scripts

diff --git a/package/motors/files/S09motor b/package/motors/files/S09motor
--- a/package/motors/files/S09motor
+++ b/package/motors/files/S09motor
@@ -1,24 +1,21 @@
 #!/bin/sh
 
+. /etc/init.d/rc.common
+
 motors_app=$(which motors)
 gpio_motor_h=$(fw_printenv -n gpio_motor_h)
 gpio_motor_v=$(fw_printenv -n gpio_motor_v)
 motor_h_maxstep=$(fw_printenv -n motor_maxstep_h)
 motor_v_maxstep=$(fw_printenv -n motor_maxstep_v)
 
-die() {
-	echo -e "$1"
-	exit ${2:-1}
-}
-
 check_module_loaded() {
 	for module in "$@"; do
-		grep -qE "^$module" /proc/modules && die "Module $module already loaded." 0
+		grep -qE "^$module" /proc/modules && die 0 "Module $module already loaded."
 	done
 }
 
 set_motor_phases() {
-	[ "$(echo $2 | wc -w)" -lt 4 ] && die "Missing phase for ${1}motor"
+	[ "$(echo $2 | wc -w)" -lt 4 ] && die 1 "Missing phase for ${1}motor"
 
 	local i=1
 	for gpio in $2; do
@@ -32,17 +29,17 @@ rehome_motors() {
 }
 
 start() {
-	echo -n "Starting motors: "
+	starting
 
 	# Do not double load module
 	check_module_loaded motor sample_motor
 
 	# Check if motors are supported
-	[ -z "$motors_app" ] && die "Disabled\n\tNo motors app found"
-	[ -z "$gpio_motor_h" ] && die "Disabled\n\tPan motor GPIO are not set"
-	[ -z "$gpio_motor_v" ] && die "Disabled\n\tTilt motor GPIO are not set"
-	[ -z "$motor_h_maxstep" ] && die "Disabled\n\tPan motor Steps are not set"
-	[ -z "$motor_v_maxstep" ] && die "Disabled\n\tTilt motor Steps are not set"
+	[ -z "$motors_app" ] && die 1 "Disabled\n\tNo motors app found"
+	[ -z "$gpio_motor_h" ] && die 1 "Disabled\n\tPan motor GPIO are not set"
+	[ -z "$gpio_motor_v" ] && die 1 "Disabled\n\tTilt motor GPIO are not set"
+	[ -z "$motor_h_maxstep" ] && die 1 "Disabled\n\tPan motor Steps are not set"
+	[ -z "$motor_v_maxstep" ] && die 1 "Disabled\n\tTilt motor Steps are not set"
 
 	# Set GPIO per motor phase
 	set_motor_phases "h" "$gpio_motor_h"
@@ -52,7 +49,7 @@ start() {
 	modprobe motor hmaxstep=$motor_h_maxstep vmaxstep=$motor_v_maxstep \
 		hst1=$hst1 hst2=$hst2 hst3=$hst3 hst4=$hst4 \
 		vst1=$vst1 vst2=$vst2 vst3=$vst3 vst4=$vst4 \
-		|| die "Failed to load motor module"
+		|| die 1 "Failed to load motor module"
 
 	echo "OK"
 
@@ -61,9 +58,9 @@ start() {
 }
 
 stop() {
-	echo -n "Stopping motors: "
+	stopping
 	# FIXME: motor.ko crashes on upload
-	# rmmod motor || die "Failed to unload motor module."
+	# rmmod motor || die 1 "Failed to unload motor module."
 	echo "OK"
 }
 
@@ -77,7 +74,7 @@ case "$1" in
 		start
 		;;
 	*)
-		die "Usage: $0 {start|stop|restart|reload}"
+		die 1 "Usage: $0 {start|stop|restart|reload}"
 		;;
 esac
 
diff --git a/package/prudynt-t/files/S96record b/package/prudynt-t/files/S96record
--- a/package/prudynt-t/files/S96record
+++ b/package/prudynt-t/files/S96record
@@ -1,19 +1,20 @@
 #!/bin/sh
 
 DAEMON=openRTSP
-ENABLED=false
 
 . /etc/init.d/rc.common
+
+ENABLED=false
 
 read_config() {
 	sed -nE "s/^.*$1:\s*\"?([^\"]+)\"?;.*$/\1/p" /etc/prudynt.cfg | head -1
 }
 
-stream0fps=$(read_config "fps")
-stream0width=$(read_config "width")
-stream0height=$(read_config "height")
-rtsp_username=$(read_config "username")
-rtsp_password=$(read_config "password")
+stream0fps=$(read_config fps)
+stream0width=$(read_config width)
+stream0height=$(read_config height)
+rtsp_username=$(read_config username)
+rtsp_password=$(read_config password)
 
 file_prefix="thingino-"
 record_path="/mnt/mmcblk0p1"
@@ -23,29 +24,23 @@ start() {
 	if [ "$ENABLED" = "true" ]; then
 		echo -n "Starting RTSP recorder: "
 
-		is_streamer_disabled && { echo -e "Disabled"; exit 0; }
+		is_streamer_disabled && die 0 "Disabled"
 
-		if [ "$record_path" = "/mnt/mmcblk0p1" ] && ! grep -q "$record_path" /proc/mounts; then
-			die "Record path is set to $record_path but SD card is not mounted"
+		if [ "$record_path" = "/mnt/mmcblk0p1" ]; then
+			grep -q "$record_path" /proc/mounts || die 1 "Record path is set to $record_path but SD card is not mounted"
 		fi
 
-		if [ ! -d "$record_path" ]; then
-			die "Record path does not exist"
-		fi
+		[ -d "$record_path" ] || die 1 "Record path does not exist"
 
-		if ! pidof prudynt >/dev/null; then
-			die "Prudynt is not running. Unable to record RTSP stream"
-		fi
+		pidof prudynt > /dev/null || die 1 "Prudynt is not running. Unable to record RTSP stream"
 
-		[ ! -d "$record_path" ] && mkdir -p "$record_path"
-		cd "$record_path" || die "Cannot change directory to $record_path"
+		[ -d "$record_path" ] || mkdir -p "$record_path"
+		cd "$record_path" || die 1 "Cannot change directory to $record_path"
 
-		if pidof $DAEMON >/dev/null; then
-			die "RTSP recorder already running"
-		fi
+		pidof $DAEMON > /dev/null && die 1 "RTSP recorder already running"
 
 		sleep 2
-		COMMAND="${DAEMON} -u "$rtsp_username" "$rtsp_password" \
+		COMMAND="$DAEMON -u "$rtsp_username" "$rtsp_password" \
 				-w "$stream0width" -h "$stream0height" -f "$stream0fps" -P $record_interval \
 				-q -v -b 1048576 -t -H -F "$file_prefix" rtsp://127.0.0.1/ch0"
 		start_daemon
@@ -54,7 +49,7 @@ start() {
 
 stop() {
 	stopping
-	is_streamer_disabled && { echo -e "Disabled"; exit 0; }
+	is_streamer_disabled && die 0 "Disabled"
 	stop_daemon
 }
 
@@ -70,8 +65,7 @@ case "$1" in
 		;;
 
 	*)
-		echo "Usage: $0 {start|stop|restart|reload}" >&2
-		exit 1
+		die 1 "Usage: $0 {start|stop|restart|reload}"
 		;;
 esac
 
diff --git a/package/thingino-portal/files/S41portal b/package/thingino-portal/files/S41portal
--- a/package/thingino-portal/files/S41portal
+++ b/package/thingino-portal/files/S41portal
@@ -2,40 +2,35 @@
 
 . /etc/init.d/rc.common
 
-ENABLE=true
-HOST_IP=172.16.0
+CNET=172.16.0
 
 ssid="$(fw_printenv -n wlanssid)"
 pass="$(fw_printenv -n wlanpass)"
 
-timeout(){
+timeout() {
 	sleep 300 && /etc/init.d/S41portal stop
 }
 
 init_portal() {
-	echo -n "Starting WiFi Portal: "
-	if [ "$ENABLE" = "true" ]; then
-		wlan_check || { echo "Disabled"; exit 1; }
-		if [ -z "$ssid" ] || [ -z "$pass" ]; then
-			ip a add dev wlan0 $HOST_IP.1/24
-			ip link set wlan0 up
-			ip route add $HOST_IP.0/24 dev wlan0 > /dev/null 2>&1
-			start-stop-daemon -S -x /sbin/udhcpd -- -S -I $HOST_IP.1 /etc/udhcpd.conf 2>&1
-			start-stop-daemon -S -x /sbin/dnsd -- -i $HOST_IP.1 -c /etc/dnsd.conf -d | logger -p daemon.info -t $0
+	starting
+	wlan_check || die 1 "Disabled"
+	[ -n "$ssid" ] && [ -n "$pass" ] && die 1 "Disabled"
 
-			mac_address=$(ip link show wlan0 | awk '/ether/ {print $2}')
-			last_two=$(echo $mac_address | awk -F: '{print $(NF-1) $NF}')
-			sed -i "/ssid=\"THINGINO-\"$/ s/\"$/$last_two\"/" /etc/wpa_ap.conf
+	ip a add dev wlan0 $CNET.1/24
+	ip link set wlan0 up
+	ip route add $CNET.0/24 dev wlan0 > /dev/null 2>&1
 
-			start-stop-daemon -S -x /sbin/wpa_supplicant -- -i wlan0 -B -c /etc/wpa_ap.conf 2>&1 | logger -p daemon.info -t $0
+	start-stop-daemon -S -x /sbin/udhcpd -- -S -I $CNET.1 /etc/udhcpd.conf 2>&1
+	start-stop-daemon -S -x /sbin/dnsd -- -i $CNET.1 -c /etc/dnsd.conf -d | logger -p daemon.info -t $0
 
-			[ $? = 0 ] && echo "OK" || echo "FAIL"
+	mac_address=$(ip link show wlan0 | awk '/ether/ {print $2}')
+	last_two=$(echo $mac_address | awk -F: '{print $(NF-1) $NF}')
+	sed -i "/ssid=\"THINGINO-\"$/ s/\"$/$last_two\"/" /etc/wpa_ap.conf
 
-			timeout &
-		else
-			echo "Disabled"
-		fi
-	fi
+	start-stop-daemon -S -x /sbin/wpa_supplicant -- -i wlan0 -B -c /etc/wpa_ap.conf 2>&1 | logger -p daemon.info -t $0
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
+
+	timeout &
 }
 
 case "$1" in
@@ -46,15 +41,14 @@ case "$1" in
 		start-stop-daemon -K -q -x /sbin/udhcpd
 		start-stop-daemon -K -q -x /sbin/dnsd
 		start-stop-daemon -K -q -x /sbin/wpa_supplicant
-		ip address delete dev wlan0 $HOST_IP.1/24
+		ip address delete dev wlan0 $CNET.1/24
 		ip link set wlan0 down
 		;;
-	reload|restart)
+	reload | restart)
 		true
 		;;
 	*)
-		echo "Usage: $0 {start|stop|reload|restart}"
-		exit 1
+		die 1 "Usage: $0 {start|stop|reload|restart}"
 		;;
 esac
 
diff --git a/package/wifi/files/S36wireless b/package/wifi/files/S36wireless
--- a/package/wifi/files/S36wireless
+++ b/package/wifi/files/S36wireless
@@ -3,13 +3,13 @@
 . /etc/init.d/rc.common
 
 start() {
-	echo -n "Starting wireless: "
+	starting
 	modulename="$(fw_printenv -n wlandev)"
 	moduleopts="$(fw_printenv -n wlandevopts)"
 	gpionum="$(fw_printenv -n gpio_wlan)"
 	mac_address=$(fw_printenv -n wlanmac)
 
-	wlandev_check || { echo "Disabled"; exit 1; }
+	wlandev_check || die 1 "Disabled"
 
 	if [ -n "$gpionum" ]; then
 		num=${gpionum%[oO]}
@@ -25,12 +25,9 @@ start() {
 		esac
 
 		echo -en "\n Set GPIO $num $gpio_cmd... "
-		if gpio $gpio_cmd $num 2>&1 | logger -p daemon.info -t $0; then
-			echo "OK"
-		else
-			echo "FAIL"
-			exit 1
-		fi
+		gpio $gpio_cmd $num 2>&1 | logger -p daemon.info -t $0 || die 1 "FAIL"
+
+		echo "OK"
 	fi
 
 	#FIXME Assume that we are SDIO, and we need to insert
@@ -55,7 +52,6 @@ start() {
 	if [ -n "$mac_address" ]; then
 		ip link set dev wlan0 address $mac_address 2>&1 | logger -p daemon.info -t $0
 	fi
-
 }
 
 case "$1" in
@@ -66,8 +62,7 @@ case "$1" in
 		true
 		;;
 	*)
-		echo "Usage: $0 {start}"
-		exit 1
+		die 1 "Usage: $0 {start}"
 		;;
 esac
 
diff --git a/package/wifi/files/S38wpa_supplicant b/package/wifi/files/S38wpa_supplicant
--- a/package/wifi/files/S38wpa_supplicant
+++ b/package/wifi/files/S38wpa_supplicant
@@ -1,23 +1,26 @@
 #!/bin/sh
 
-DAEMON=wpa_supplicant
+. /etc/init.d/rc.common
+
 IFACE=wlan0
 CONFIG="/etc/$DAEMON.conf"
 PIDFILE="/run/$DAEMON.$IFACE.pid"
 
-. /etc/init.d/rc.common
+ssid_changed() {
+	current_ssid=$(grep '^ssid=' $CONFIG | cut -d= -f2- | tr -d '"')
+	[ "$ssid" != "$current_ssid" ]
+}
 
 start() {
 	starting
 	ssid="$(fw_printenv -n wlanssid)"
 	pass="$(fw_printenv -n wlanpass)"
 
-	wlan_check || { echo "Disabled"; exit 1; }
+	wlan_check || die 1 "Disabled"
 
 	if [ -z "$ssid" ] || [ -z "$pass" ]; then
-		echo "WiFi credentials missing"
 		sed -i '/^auto wlan0$/s/^/#/' /etc/network/interfaces.d/wlan0
-		exit 0
+		die 0 "WiFi credentials missing"
 	fi
 
 	generate_wpa_supplicant_conf() {
@@ -45,32 +48,22 @@ start() {
 	[ $? = 0 ] && echo "OK" || echo "FAIL"
 }
 
-ssid_changed() {
-	current_ssid=$(grep '^ssid=' $CONFIG | cut -d= -f2- | tr -d '"')
-	[ "$ssid" != "$current_ssid" ]
-}
-
 stop() {
 	printf 'Stopping %s: ' $DAEMON
 	start-stop-daemon -K -q -p "$PIDFILE" -x /sbin/$DAEMON
 	[ $? = 0 ] && echo "OK" || echo "FAIL"
 }
 
-restart() {
-	stop
-	start
-}
-
 case "$1" in
-	start | stop | restart)
+	start | stop)
 		$1
 		;;
-	reload)
-		restart
+	reload | restart)
+		stop
+		start
 		;;
 	*)
-		echo "Usage: $0 {start|stop|restart|reload}"
-		exit 1
+		die 1 "Usage: $0 {start|stop|restart|reload}"
 		;;
 esac
 
diff --git a/package/zerotier-one/files/S90zerotier b/package/zerotier-one/files/S90zerotier
--- a/package/zerotier-one/files/S90zerotier
+++ b/package/zerotier-one/files/S90zerotier
@@ -1,26 +1,24 @@
 #!/bin/sh
 
+. /etc/init.d/rc.common
+
 config_file=/etc/webui/zerotier.conf
 [ -f "$config_file" ] && . $config_file
 
 case "$1" in
 	start)
-		if [ "false" = "$zerotier_enabled" ]; then
-			echo "Zerotier-One service is disabled in $config_file"
-			exit 3
-		fi
+		[ "false" = "$zerotier_enabled" ] && die 3 "Zerotier-One service is disabled in $config_file"
 
-		echo "Starting zerotier-one daemon..."
-		modprobe tun
-		zerotier-one -d
+		starting
+		{ modprobe tun && zerotier-one -d } || die 1 "FAIL"
+		echo "OK"
 		;;
 	stop)
-		echo "Stopping zerotier-one daemon..."
-		kill -9 $(pidof zerotier-one)
-		rmmod -w tun
+		stopping
+		{ kill -9 $(pidof zerotier-one) && rmmod -w tun } || die 1 "FAIL"
+		echo "OK"
 		;;
 	*)
-		echo "Usage: $0 {start|stop}"
-		exit 1
+		die 1 "Usage: $0 {start|stop}"
 		;;
 esac
