rewrite motors daemon, add flag to disable homing

diff --git a/package/motors/files/S09motor b/package/motors/files/S09motor
--- a/package/motors/files/S09motor
+++ b/package/motors/files/S09motor
@@ -1,83 +1,78 @@
 #!/bin/sh
 
+motors_app=$(which motors)
 gpio_motor_h=$(fw_printenv -n gpio_motor_h)
 gpio_motor_v=$(fw_printenv -n gpio_motor_v)
 motor_h_maxstep=$(fw_printenv -n motor_maxstep_h)
 motor_v_maxstep=$(fw_printenv -n motor_maxstep_v)
 
-check_return() {
-	if [ $1 -ne 0 ]; then
-		echo "err: $2"
-		exit 1
-	fi
+die() {
+	echo -e "$1"
+	exit ${2:-1}
 }
 
-check_module() {
+check_module_loaded() {
 	for module in "$@"; do
-		if grep -qE "^$module" /proc/modules; then
-			echo "Module ${module} already loaded."
-			exit 0
-		fi
+		grep -qE "^$module" /proc/modules && die "Module $module already loaded." 0
 	done
 }
 
-set_gpio_vars() {
-	local gpio_string=$1
-	local motor_type=$2
-	local i=1
+set_motor_phases() {
+	[ "$(echo $2 | wc -w)" -lt 4 ] && die "Missing phase for ${1}motor"
 
-	for gpio in $gpio_string; do
-		eval "${motor_type}st${i}=${gpio}"
+	local i=1
+	for gpio in $2; do
+		eval "${1}st${i}=$gpio"
 		i=$((i + 1))
 	done
-
-	if [ $i -ne 5 ]; then
-		echo "Missing phase for ${motor_type} motor. Cannot load motor module."
-		exit 1
-	fi
 }
 
-start() {
-	echo -n "Starting motor: "
-	# Check if motors are supported
-	if [ -z "$gpio_motor_h" ] || [ -z "$gpio_motor_v" ]; then
-		echo "DISABLED"
-		exit 0
-	fi
-
-	# Check for errors after caching command results
-	check_return $? "Failed to get initial configuration"
-
-	# Set GPIO variables
-	set_gpio_vars "$gpio_motor_h" "h"
-	check_return $? "Failed to set horizontal GPIO variables"
-
-	set_gpio_vars "$gpio_motor_v" "v"
-	check_return $? "Failed to set vertical GPIO variables"
-
-	# Check if the module is already loaded
-	check_module motor sample_motor
-
-	modprobe motor hmaxstep=$motor_h_maxstep vmaxstep=$motor_v_maxstep \
-		hst1=$hst1 hst2=$hst2 hst3=$hst3 hst4=$hst4 \
-		vst1=$vst1 vst2=$vst2 vst3=$vst3 vst4=$vst4
-	check_return $? "Failed to load motor module for ingenic"
-	echo "OK"
-	# Initialize motor position upon successful module loading
+rehome_motors() {
 	motors -r > /dev/null 2>&1 &
 }
 
+start() {
+	echo -n "Starting motors: "
+
+	# Do not double load module
+	check_module_loaded motor sample_motor
+
+	# Check if motors are supported
+	[ -z "$motors_app" ] && die "DISABLED\n\tNo motors app found"
+	[ -z "$gpio_motor_h" ] && die "DISABLED\n\tPan motor GPIO are not set"
+	[ -z "$gpio_motor_v" ] && die "DISABLED\n\tTilt motor GPIO are not set"
+
+	# Set GPIO per motor phase
+	set_motor_phases "h" "$gpio_motor_h"
+	set_motor_phases "v" "$gpio_motor_v"
+
+	# Load module with parameters
+	modprobe motor hmaxstep=$motor_h_maxstep vmaxstep=$motor_v_maxstep \
+		hst1=$hst1 hst2=$hst2 hst3=$hst3 hst4=$hst4 \
+		vst1=$vst1 vst2=$vst2 vst3=$vst3 vst4=$vst4 \
+		|| die "Failed to load motor module"
+
+	echo "OK"
+
+	# Set motors zero position unless disabled
+	[ "true" != "$(fw_printenv -n disable_homing)" ] && rehome_motors
+}
+
+stop() {
+	rmmod motor || die "Failed to unload motor module."
+}
+
 case "$1" in
-	start)
+	start | stop)
+		$1
+		;;
+	restart | reload)
+		stop
+		sleep 1
 		start
 		;;
-	stop | restart | reload)
-		# Implement logic if needed
-		true
-		;;
 	*)
-		echo "Usage: $0 {start|stop|restart|reload}"
-		exit 1
+		die "Usage: $0 {start|stop|restart|reload}"
 		;;
 esac
 
