motors: get data from config file, account for shared pins and reversed shared pins order.

diff --git a/package/thingino-motors/files/S09motor b/package/thingino-motors/files/S09motor
--- a/package/thingino-motors/files/S09motor
+++ b/package/thingino-motors/files/S09motor
@@ -5,9 +5,11 @@ DAEMON_ARGS="-d -p"
 
 . /usr/share/common
 
+ensure_command "motors"
+
 set_motor_phases() {
 	if [ "$(echo $2 | wc -w)" -lt 4 ]; then
-		echo "- Missing phase for ${1}motor"
+		echo "- Missing phase for ${1}motor" >&2
 		exit 1
 	fi
 
@@ -19,12 +21,12 @@ set_motor_phases() {
 }
 
 home_motors() {
-	echo "- Home motors"
+	echo "- Home motors" >&2
 	motors -r
 }
 
 set_motors_speed() {
-	echo "- Set motors speed to $motor_speed"
+	echo "- Set motors speed to $motor_speed" >&2
 	motors -s $1
 }
 
@@ -39,39 +41,48 @@ position_motors() {
 		y=$((motor_maxstep_v / 2))
 	fi
 
-	echo "- Move to $x,$y"
+	echo "- Move to $x,$y" >&2
 	motors -d h -x $x -y $y
 }
 
 start() {
-	echo "- Setting up motors"
+	echo "- Setting up motors" >&2
 
-	motors_app=$(which motors)
-
-	# Check if motors are supported
-	if [ -z "$motors_app" ]; then
-		echo "- No motors app found"
+	if [ -z "$gpio_motor_h$gpio_motor_v" ]; then
+		echo "- No motor pins defined" >&2
 		exit 1
 	fi
 
 	if [ -z "$gpio_motor_h" ]; then
-		echo "- Pan motor GPIO pins are not set"
-		exit 1
+		echo "- Pan motor GPIO pins are not set" >&2
 	fi
 
-	if [ -z "$gpio_motor_switch" ] && [ -z "$gpio_motor_v" ]; then
-		echo "- Tilt motor GPIO pins are not set"
-		exit 1
+	if [ -z "$gpio_motor_v" ]; then
+		echo "- Tilt motor GPIO pins are not set" >&2
+	fi
+
+	if [ -z "$gpio_motor_switch" ]; then
+		echo "- gpio_motor_switch is not set" >&2
 	fi
 
 	if [ -z "$motor_maxstep_h" ]; then
-		echo "- Pan motor Steps are not set"
-		exit 1
+		echo "- Pan motor Steps are not set" >&2
+		motor_maxstep_h=4000
 	fi
 
 	if [ -z "$motor_maxstep_v" ]; then
-		echo "- Tilt motor Steps are not set"
-		exit 1
+		echo "- Tilt motor Steps are not set" >&2
+		motor_maxstep_v=2000
+	fi
+
+	if [ -z "$motor_speed_h" ]; then
+		echo "- motor_speed_h is not set, set to 900" >&2
+		motor_speed_h=900
+	fi
+
+	if [ -z "$motor_speed_v" ]; then
+		echo "- motor_speed_v is not set, set to 900" >&2
+		motor_speed_v=900
 	fi
 
 	if [ -z "$motor_speed" ]; then
@@ -79,9 +90,9 @@ start() {
 	fi
 
 	if grep -qE "^motor" /proc/modules; then
-		echo "- Module motor already loaded."
+		echo "- Module motor already loaded." >&2
 	else
-		echo "- Set GPIO per motor phase"
+		echo "- Set GPIO per motor phase" >&2
 
 		set_motor_phases "h" "$gpio_motor_h"
 		set_motor_phases "v" "$gpio_motor_v"
@@ -89,18 +100,22 @@ start() {
 		modprobe_args="hmaxstep=$motor_maxstep_h vmaxstep=$motor_maxstep_v"
 		modprobe_args="$modprobe_args hst1=$hst1 hst2=$hst2 hst3=$hst3 hst4=$hst4"
 
+		[ -z "$vst1" ] && vst1="$hst1"
+		[ -z "$vst2" ] && vst1="$hst2"
+		[ -z "$vst3" ] && vst1="$hst3"
+		[ -z "$vst4" ] && vst1="$hst4"
+
+		modprobe_args="$modprobe_args vst1=$vst1 vst2=$vst2 vst3=$vst3 vst4=$vst4"
+
 		if echo "$gpio_motor_switch" | grep -qE '^[0-9]+$'; then
-			modprobe_args="$modprobe_args vst1=$hst1 vst2=$hst2 vst3=$hst3 vst4=$hst4"
-			modprobe_args="$modprobe_args shared_gpio_mode=0 direction_select_gpio=$gpio_motor_switch"
-		else
-			modprobe_args="$modprobe_args vst1=$vst1 vst2=$vst2 vst3=$vst3 vst4=$vst4"
+			modprobe_args="$modprobe_args motor_switch_gpio=$gpio_motor_switch"
 		fi
 
 		if [ "true" = "$gpio_motor_invert" ]; then
 			modprobe_args="$modprobe_args invert_gpio_dir=1"
 		fi
 
-		echo "- Load motor module with parameters: $modprobe_args"
+		echo "- Load motor module with parameters: $modprobe_args" >&2
 
 		if ! modprobe motor $modprobe_args; then
 			echo "- Failed to load motor module"
@@ -112,10 +127,11 @@ start() {
 	# FIXME: daemon should be reporting running state from the very first moment
 	sleep 1
 
-	set_motors_speed $motor_speed
+	# FIXME: motors may have different speeds for pan and tilt
+	set_motors_speed $motor_speed_h
 
 	if [ "true" = "$motor_disable_homing" ]; then
-		echo "- Homing disabled"
+		echo "- Homing disabled" >&2
 	else
 		home_motors
 		position_motors
@@ -123,7 +139,7 @@ start() {
 }
 
 stop() {
-	echo "Stopping motors"
+	echo "Stopping motors" >&2
 
 	stop_daemon
 	# FIXME: motor.ko crashes on upload
