firstboot: add force flag

diff --git a/overlay/lower/usr/sbin/firstboot b/overlay/lower/usr/sbin/firstboot
--- a/overlay/lower/usr/sbin/firstboot
+++ b/overlay/lower/usr/sbin/firstboot
@@ -2,28 +2,41 @@
 
 erase_mtd1=true
 
-while getopts "eh" opt; do
+while getopts "efh" opt; do
 	case $opt in
 		e) erase_mtd1=false ;;
+		f) force_wipe=true ;;
 		h) echo -e "Usage: $0 [options]\n  -e    Do not erase /dev/mtd1\n  -h    Show help information"; exit 0 ;;
 		\?) echo "Invalid option. Use -h for help."; exit 1 ;;
 	esac
 done
 
-echo -e "\033[31;47m!!! Warning !!!\033[0m\n\nThis action will reset the device to defaults and erase all configurations, leaving the device like the first boot.\n\n\033[33;40mAll saved settings will be erased!\033[0m\n\nAre you sure you want to proceed? (yes/no)"
-read response
-if [ "$response" != "yes" ]; then
-	echo "Operation aborted."
-	exit 1
-fi
+wipe() {
+	rootfs_data_dev=$(awk '$4 ~ /"rootfs_data"/ {gsub(":","",$1); print $1}' /proc/mtd)
+	if [ -z "$rootfs_data_dev" ]; then
+		echo "Overlay partition not found!"
+		exit 1
+	fi
 
-rootfs_data_dev=$(awk '$4 ~ /"rootfs_data"/ {gsub(":","",$1); print $1}' /proc/mtd)
-if [ -z "$rootfs_data_dev" ]; then
-	echo "Overlay partition not found!"
-	exit 1
-fi
+	flash_eraseall -j "/dev/${rootfs_data_dev}"
+	[ "$erase_mtd1" = true ] && flash_eraseall /dev/mtd1
+	echo "Erase completed. Rebooting..."
+	reboot -f
+}
 
-flash_eraseall -j "/dev/${rootfs_data_dev}"
-[ "$erase_mtd1" = true ] && flash_eraseall /dev/mtd1
-echo "Erase completed. Rebooting..."
-reboot -f
+warn() {
+	echo -e "\033[31;47m!!! Warning !!!\033[0m\n\nThis action will reset the device to defaults and erase all configurations, leaving the device like the first boot.\n\n\033[33;40mAll saved settings will be erased!\033[0m\n\nAre you sure you want to proceed? (yes/no)"
+	read response
+	if [ "$response" != "yes" ]; then
+		echo "Operation aborted."
+		exit 1
+	else
+		wipe
+	fi
+}
+
+if [ "$force_wipe" = true ]; then
+	wipe
+else
+	warn
+fi
