scripts: expand conditions, redirect commentary to stderr

diff --git a/overlay/lower/usr/sbin/formatsd b/overlay/lower/usr/sbin/formatsd
--- a/overlay/lower/usr/sbin/formatsd
+++ b/overlay/lower/usr/sbin/formatsd
@@ -1,34 +1,34 @@
 #!/bin/sh
 
 if pidof -o %PPID $(basename $0) > /dev/null; then
-	echo "is already running"
+	echo "is already running" >&2
 	exit 1
 fi
 
 format_partition() {
 	unmount_partition $1
-	echo "Format partition"
+	echo "Format partition" >&2
 	if ! $MKFS -n thingino $1 2>&1; then
-		echo "Cannot format $1 to $POST_fstype"
+		echo "Cannot format $1 to $POST_fstype" >&2
 		exit 1
 	fi
 }
 
 mount_partitions() {
-	echo "Mount partition"
+	echo "Mount partition" >&2
 	echo /sbin/mdev > /proc/sys/kernel/hotplug
 	if ! mdev -s; then
-		echo "Cannot re-mount SD card"
+		echo "Cannot re-mount SD card" >&2
 		exit 1
 	fi
 }
 
 unmount_partition() {
-	echo "Unmount partition"
+	echo "Unmount partition" >&2
 	local limit=5
 	while mountpoint -q $1; do
 		if [ "$limit" -le 0 ]; then
-			echo "Cannot unmount $1"
+			echo "Cannot unmount $1" >&2
 			exit 1
 		fi
 		umount -l $1 2>&1
@@ -38,7 +38,7 @@ unmount_partition() {
 }
 
 reinsert_sdcard() {
-	echo "Reinsert card"
+	echo "Reinsert card" >&2
 	echo "" > /proc/sys/kernel/hotplug
 	mmc 0 -r
 	sleep 1
@@ -47,9 +47,9 @@ reinsert_sdcard() {
 }
 
 repartition_sdcard() {
-	echo "Repartition card"
+	echo "Repartition card" >&2
 	if ! echo -e "o\nn\np\n1\n\n\nt\n$FSTYPE\nw" | fdisk $1 2>&1; then
-		echo "Cannot create a partition on $1"
+		echo "Cannot create a partition on $1" >&2
 		exit 1
 	fi
 }
@@ -67,7 +67,7 @@ esac
 
 device_name="$(awk -F= '/DEVNAME/{print $2}' /sys/bus/mmc/devices/*/block/*/uevent)"
 if [ -z "$device_name" ]; then
-	echo "No SD card device found"
+	echo "No SD card device found" >&2
 	exit 1
 fi
 
diff --git a/overlay/lower/usr/sbin/odhcp6c-update b/overlay/lower/usr/sbin/odhcp6c-update
--- a/overlay/lower/usr/sbin/odhcp6c-update
+++ b/overlay/lower/usr/sbin/odhcp6c-update
@@ -1,14 +1,14 @@
 #!/bin/sh
 
 if [ -z "$2" ]; then
-	echo "Error: should be run by odhcp6c"
+	echo "Error: should be run by odhcp6c" >&2
 	exit 1
 fi
 
 # Define the base directory for tracking DHCPv6 data
 DHCP6_DATA_BASE="/var/run/odhcp6c"
 if ! mkdir -p "$DHCP6_DATA_BASE"; then
-	echo "Error: cannot create $DHCP6_DATA_BASE"
+	echo "Error: cannot create $DHCP6_DATA_BASE" >&2
 	exit 1
 fi
 
@@ -152,7 +152,7 @@ update_resolv() {
 			if ! grep -q "search $domain" /tmp/resolv.conf.tmp; then
 				echo "search $domain # added by odhcp6c" >> /tmp/resolv.conf.tmp
 			fi
-			echo "added search $domain"
+			echo "added search $domain" >&2
 		done
 
 		# Add unique DNS servers to resolv.conf
@@ -160,7 +160,7 @@ update_resolv() {
 			if ! grep -q "nameserver $c" /tmp/resolv.conf.tmp; then
 				echo "nameserver $c # added by odhcp6c" >> /tmp/resolv.conf.tmp
 			fi
-			echo "added nameserver $c"
+			echo "added nameserver $c" >&2
 		done
 
 		# Move the temporary file to /tmp/resolv.conf
@@ -190,20 +190,20 @@ add_address() {
 
 	# Check if the address already exists
 	if ip -6 address show dev "$dev_name" | grep -q "$addr"; then
-		echo "Address already exists: $addr dev $dev_name, updating lifetimes"
+		echo "Address already exists: $addr dev $dev_name, updating lifetimes" >&2
 
 		# Update the address with the new preferred and valid lifetimes
 		ip -6 address change "$addr" dev "$dev_name" preferred_lft "$pref_lft" valid_lft "$valid_lft" || {
-			echo "Failed to update address: $addr dev $dev_name preferred_lft $pref_lft valid_lft $valid_lft"
+			echo "Failed to update address: $addr dev $dev_name preferred_lft $pref_lft valid_lft $valid_lft" >&2
 			return 1
 		}
 		return 0
 	fi
 
-	echo "Adding address: $addr dev $dev_name preferred_lft $pref_lft valid_lft $valid_lft"
+	echo "Adding address: $addr dev $dev_name preferred_lft $pref_lft valid_lft $valid_lft" >&2
 
 	ip -6 address add "$addr" dev "$dev_name" preferred_lft "$pref_lft" valid_lft "$valid_lft" || {
-		echo "Failed to add address: $addr dev $dev_name preferred_lft $pref_lft valid_lft $valid_lft"
+		echo "Failed to add address: $addr dev $dev_name preferred_lft $pref_lft valid_lft $valid_lft" >&2
 		return 1
 	}
 
@@ -248,7 +248,7 @@ teardown_interface() {
 
 	# Check if the lease file exists
 	if [ -f "$lease_file" ]; then
-		echo "Attempting to remove addresses and routes from $device"
+		echo "Attempting to remove addresses and routes from $device" >&2
 
 		# Read the lease file line by line
 		while read -r line; do
@@ -261,26 +261,26 @@ teardown_interface() {
 				if [ -n "$addr" ]; then
 					# Attempt to remove the address
 					if ip -6 address del "$addr" dev "$device"; then
-						echo "Successfully removed address: $addr dev $device"
+						echo "Successfully removed address: $addr dev $device" >&2
 					else
-						echo "Failed to remove address: $addr dev $device"
+						echo "Failed to remove address: $addr dev $device" >&2
 					fi
 
 					# Attempt to remove the route for this address
 					if ip -6 route del "$addr" dev "$device"; then
-						echo "Successfully removed route: $addr dev $device"
+						echo "Successfully removed route: $addr dev $device" >&2
 					else
-						echo "Failed to remove route: $addr dev $device"
+						echo "Failed to remove route: $addr dev $device" >&2
 					fi
 				fi
 			fi
 		done < "$lease_file"
 
 		# Remove the lease file after processing
-		echo "Removing lease file: $lease_file"
+		echo "Removing lease file: $lease_file" >&2
 		rm -f "$lease_file"
 	else
-		echo "No existing lease file found for $device."
+		echo "No existing lease file found for $device" >&2
 	fi
 }
 
diff --git a/overlay/lower/usr/sbin/send2email b/overlay/lower/usr/sbin/send2email
--- a/overlay/lower/usr/sbin/send2email
+++ b/overlay/lower/usr/sbin/send2email
@@ -14,7 +14,7 @@ Where:
 	-k          Ignore SSL certificate validity.
 	-v          Verbose output.
 	-h          Show this help.
-"
+" >&2
 	exit 0
 }
 
@@ -33,35 +33,74 @@ while getopts b:f:kn:p:s:t:vh flag; do
 	esac
 done
 
-[ -z "$email_smtp_host" ] && die "SMTP host not found"
-[ -z "$email_smtp_port" ] && email_smtp_port=25
-[ -z "$email_from_address" ] && die "Sender's email address not found"
-[ -z "$email_to_address" ] && die "Recipient's email address not found"
-[ -z "$email_body" ] && die "Email body not found"
+if [ -z "$email_smtp_host" ]; then
+	echo "SMTP host not found" >&2
+	exit 1
+fi
 
-echo "$email_from_address" | grep -E -q $EMAIL_FORMAT || die "Invalid sender email address format"
-echo "$email_to_address" | grep -E -q $EMAIL_FORMAT || die "Invalid recipient email address format"
+if [ -z "$email_smtp_port" ]; then
+	email_smtp_port=25
+fi
 
-[ -z "$email_from_name" ] && email_from_name="Thingino Camera"
-[ -z "$email_to_name" ] && email_to_name="Thingino Camera Admin"
-[ -z "$email_subject" ] && email_subject="Snapshot from Thingino Camera"
+if [ -z "$email_from_address" ]; then
+	echo "Sender's email address not found" >&2
+	exit 1
+fi
+
+if [ -z "$email_to_address" ]; then
+	echo "Recipient's email address not found" >&2
+	exit 1
+fi
+
+if [ -z "$email_body" ]; then
+	echo "Email body not found" >&2
+	exit 1
+fi
+
+if ! echo "$email_from_address" | grep -E -q $EMAIL_FORMAT >/dev/null; then
+	echo "Invalid sender email address format" >&2
+	exit 1
+fi
+
+if ! echo "$email_to_address" | grep -E -q $EMAIL_FORMAT >/dev/null; then
+	echo "Invalid recipient email address format" >&2
+	exit 1
+fi
+
+if [ -z "$email_from_name" ]; then
+	email_from_name="Thingino Camera"
+fi
+
+if [ -z "$email_to_name" ]; then
+	email_to_name="Thingino Camera Admin"
+fi
+
+if [ -z "$email_subject" ]; then
+	email_subject="Snapshot from Thingino Camera"
+fi
 
 command="curl --show-error --fail --connect-timeout 10 --max-time 30 --retry 3 $verbosity"
 command="$command --mail-from $email_from_address --mail-rcpt $email_to_address"
 
-[ -n "$email_smtp_username" ] && [ -n "$email_smtp_password" ] && \
+if [ -n "$email_smtp_username" ] && [ -n "$email_smtp_password" ]; then
 	command="$command --user '$email_smtp_username:$email_smtp_password'"
+fi
 
 if [ "true" = "$email_smtp_use_ssl" ]; then
 	command="$command --url smtps://$email_smtp_host:$email_smtp_port --ssl"
-	[ "true" = "$email_insecure_ssl" ] && command="$command --insecure"
+	if [ "true" = "$email_insecure_ssl" ]; then
+		command="$command --insecure"
+	fi
 else
 	command="$command --url smtp://$email_smtp_host:$email_smtp_port"
 fi
 
 email_body=${email_body//"/\\"}
-command="$command -H 'From: \"$email_from_name\" <$email_from_address>' -H 'To: \"$email_to_name\" <$email_to_address>'"
-command="$command -H 'Subject: $email_subject' -F '=(;type=multipart/mixed' -F \"=${email_body};type=text/plain\""
+command="$command -H 'From: \"$email_from_name\" <$email_from_address>'"
+command="$command -H 'To: \"$email_to_name\" <$email_to_address>'"
+command="$command -H 'Subject: $email_subject'"
+command="$command -F '=(;type=multipart/mixed'"
+command="$command -F \"=${email_body};type=text/plain\""
 
 if [ "true" = "$email_attach_snapshot" ]; then
 	photo_attachment=$(mktemp -u).jpg
@@ -77,9 +116,17 @@ fi
 
 command="$command -F '=)'"
 
-sh -c "$command" || die "Failed to send email"
+if ! sh -c "$command"; then
+	echo "Failed to send email" >&2
+	exit 1
+fi
 
-[ -f "$photo_attachment" ] && rm "$photo_attachment"
-[ -f "$video_attachment" ] && rm "$video_attachment"
+if [ -f "$photo_attachment" ]; then
+	rm "$photo_attachment"
+fi
+
+if [ -f "$video_attachment" ]; then
+	rm "$video_attachment"
+fi
 
 exit 0
diff --git a/overlay/lower/usr/sbin/send2ftp b/overlay/lower/usr/sbin/send2ftp
--- a/overlay/lower/usr/sbin/send2ftp
+++ b/overlay/lower/usr/sbin/send2ftp
@@ -13,7 +13,7 @@ Where:
 	-P password FTP password.
 	-v          Verbose output.
 	-h          Show this help.
-"
+" >&2
 	exit 0
 }
 
@@ -32,10 +32,19 @@ while getopts d:f:p:P:s:u:vVh flag; do
 	esac
 done
 
-[ -z "$ftp_host" ] && die "FTP host not found"
+if [ -z "$ftp_host" ]; then
+	echo "FTP host not found" >&2
+	exit 1
+fi
 
-[ -z "$ftp_port" ] && ftp_port=21
-[ -z "$ftp_user" ] && ftp_user="anonymous" && ftp_password="anonymous"
+if [ -z "$ftp_port" ]; then
+	ftp_port=21
+fi
+
+if [ -z "$ftp_user" ]; then
+	ftp_user="anonymous"
+	ftp_password="anonymous"
+fi
 
 if [ -z "$ftp_file" ]; then
 	if [ "true" = "$ftp_sendvideo" ]; then
@@ -52,15 +61,22 @@ if [ -z "$ftp_file" ]; then
 fi
 
 url="ftp://"
-[ -n "$ftp_user" ] && [ -n "$ftp_password" ] && url="$url$ftp_user:$ftp_password"
+if [ -n "$ftp_user" ] && [ -n "$ftp_password" ]; then
+	url="$url$ftp_user:$ftp_password"
+fi
 url="$url@$ftp_host:$ftp_port"
-[ -n "$ftp_path" ] && url="$url/${ftp_path// /%20}"
+if [ -n "$ftp_path" ]; then
+	url="$url/${ftp_path// /%20}"
+fi
 url="$url/$ftp_filename"
 
 command="curl --show-error --fail --connect-timeout 10 --max-time 30 --retry 3 $verbosity"
 command="$command --url $url --upload-file $ftp_file --ftp-create-dirs"
 
-sh -c "$command" || die "Failed to upload file to FTP server"
+if ! sh -c "$command"; then
+	echo "Failed to upload file to FTP server" >&2
+	exit 1
+fi
 
 [ -f "$attachment" ] && rm "$attachment"
 
diff --git a/overlay/lower/usr/sbin/send2mqtt b/overlay/lower/usr/sbin/send2mqtt
--- a/overlay/lower/usr/sbin/send2mqtt
+++ b/overlay/lower/usr/sbin/send2mqtt
@@ -10,7 +10,7 @@ Where:
 	-s          Send a snapshot.
 	-v          Verbose output.
 	-h          Show this help.
-"
+" >&2
 	exit 0
 }
 
@@ -25,21 +25,46 @@ while getopts m:st:vh flag; do
 	esac
 done
 
-[ -z "$mqtt_host" ] && die "MQTT broker host not found in config"
-[ -z "$mqtt_port" ] && die "MQTT broker port not found in config"
-[ -z "$mqtt_topic" ] && die "MQTT topic not found"
-[ -z "$mqtt_message" ] && die "MQTT message template not found"
+if [ -z "$mqtt_host" ]; then
+	echo "MQTT broker host not found in config" >&2
+	exit 1
+fi
 
-[ "true" = "$mqtt_send_snap" ] && [ -z "$mqtt_snap_topic" ] && \
-	die "MQTT topic for sending snapshot not found in config"
+if [ -z "$mqtt_port" ]; then
+	echo "MQTT broker port not found in config" >&2
+	exit 1
+fi
 
-[ -z "$mqtt_client_id" ] && mqtt_client_id="$network_hostname"
+if [ -z "$mqtt_topic" ]; then
+	echo "MQTT topic not found" >&2
+	exit 1
+fi
+
+if [ -z "$mqtt_message" ]; then
+	echo "MQTT message template not found" >&2
+	exit 1
+fi
+
+if [ "true" = "$mqtt_send_snap" ] && [ -z "$mqtt_snap_topic" ]; then
+	echo "MQTT topic for sending snapshot not found in config" >&2
+	exit 1
+fi
+
+if [ -z "$mqtt_client_id" ]; then
+	mqtt_client_id="$network_hostname"
+fi
 
 mqtt_message=$(date +"$mqtt_message")
 
 command="mosquitto_pub -h $mqtt_host -p $mqtt_port -i $mqtt_client_id"
-[ -n "$mqtt_username" ] && command="$command -u $mqtt_username"
-[ -n "$mqtt_password" ] && command="$command -P $mqtt_password"
+
+if [ -n "$mqtt_username" ]; then
+	command="$command -u $mqtt_username"
+fi
+
+if [ -n "$mqtt_password" ]; then
+	command="$command -P $mqtt_password"
+fi
 
 if [ "true" = "$mqtt_send_snap" ]; then
 	attachment=$(mktemp -u).jpg
@@ -49,7 +74,10 @@ else
 	command="$command -t $mqtt_topic -m \"$mqtt_message\""
 fi
 
-sh -c "$command" || die "Failed to send MQTT message"
+if ! sh -c "$command"; then
+	echo "Failed to send MQTT message" >&2
+	exit 1
+fi
 
 [ -f "$attachment" ] && rm "$attachment"
 
diff --git a/overlay/lower/usr/sbin/send2ntfy b/overlay/lower/usr/sbin/send2ntfy
--- a/overlay/lower/usr/sbin/send2ntfy
+++ b/overlay/lower/usr/sbin/send2ntfy
@@ -18,7 +18,7 @@ Where:
 	-w password  Password.
 	-v           Verbose output.
 	-h           Show this help.
-"
+" >&2
 	exit 0
 }
 
@@ -41,24 +41,67 @@ while getopts a:c:f:i:l:m:n:p:s:t:u:vh flag; do
 	esac
 done
 
-[ -z "$ntfy_topic" ] && die "NTFY topic is not set."
+if [ -z "$ntfy_topic" ]; then
+	echo "NTFY topic is not set" >&2
+	exit 1
+fi
 
 command="curl --show-error --fail --connect-timeout 10 --max-time 30 --retry 3 $verbosity"
 command="$command -H p:${ntfy_priority:-3}"
-[ -n "$ntfy_title" ] && command="$command -H 'Title: $ntfy_title'"
-[ -n "$ntfy_tags" ] || command="$command -H 'Tags: $ntfy_tags'"
-[ -n "$ntfy_delay" ] && command="$command -H 'Delay: $ntfy_delay'"
-[ -n "$ntfy_username" ] && [ -n "$ntfy_password" ] && command="$command -u $ntfy_username:$ntfy_password"
-[ -n "$ntfy_filename" ] && [ -f "$ntfy_filename" ] && command="$command -T $ntfy_filename -H 'Filename: $ntfy_filename'"
-[ -n "$ntfy_attach" ] && command="$command -H 'Attach: $ntfy_attach'"
-[ -n "$ntfy_click" ] && command="$command -H 'Click: $ntfy_click'"
-[ -n "$ntfy_icon" ] && command="$command -H 'Icon: $ntfy_icon'"
-[ -n "$ntfy_email" ] && command="$command -H 'Email: $ntfy_email'"
-[ -n "$ntfy_actions" ] && command="$command -H 'Actions: $ntfy_actions'"
-[ -n "$ntfy_call" ] && [ -n "$ntfy_twilio_token" ] && command="$command -H 'Call: $ntfy_call' -u :$ntfy_twilio_token"
-[ -n "$ntfy_message" ] && command="$command -d '$ntfy_message'"
+
+if [ -n "$ntfy_title" ]; then
+	command="$command -H 'Title: $ntfy_title'"
+fi
+
+if [ -n "$ntfy_tags" ]; then
+	command="$command -H 'Tags: $ntfy_tags'"
+fi
+
+if [ -n "$ntfy_delay" ]; then
+	command="$command -H 'Delay: $ntfy_delay'"
+fi
+
+if [ -n "$ntfy_username" ] && [ -n "$ntfy_password" ]; then
+	command="$command -u $ntfy_username:$ntfy_password"
+fi
+
+if [ -n "$ntfy_filename" ] && [ -f "$ntfy_filename" ]; then
+	command="$command -T $ntfy_filename -H 'Filename: $ntfy_filename'"
+fi
+
+if [ -n "$ntfy_attach" ]; then
+	command="$command -H 'Attach: $ntfy_attach'"
+fi
+
+if [ -n "$ntfy_click" ]; then
+	command="$command -H 'Click: $ntfy_click'"
+fi
+
+if [ -n "$ntfy_icon" ]; then
+	command="$command -H 'Icon: $ntfy_icon'"
+fi
+
+if [ -n "$ntfy_email" ]; then
+	command="$command -H 'Email: $ntfy_email'"
+fi
+
+if [ -n "$ntfy_actions" ]; then
+	command="$command -H 'Actions: $ntfy_actions'"
+fi
+
+if [ -n "$ntfy_call" ] && [ -n "$ntfy_twilio_token" ]; then
+	command="$command -H 'Call: $ntfy_call' -u :$ntfy_twilio_token"
+fi
+
+if [ -n "$ntfy_message" ]; then
+	command="$command -d '$ntfy_message'"
+fi
+
 command="$command ${ntfy_host:-ntfy.sh}/$ntfy_topic"
 
-sh -c "$command" || die "Failed to send NTFY message"
+if ! sh -c "$command"; then
+	echo "Failed to send NTFY message" >&2
+	exit 1
+fi
 
 exit 0
diff --git a/overlay/lower/usr/sbin/send2telegram b/overlay/lower/usr/sbin/send2telegram
--- a/overlay/lower/usr/sbin/send2telegram
+++ b/overlay/lower/usr/sbin/send2telegram
@@ -13,7 +13,7 @@ Where:
 	-t token    Telegram bot token. See https://t.me/botfather if you need one.
 	-v          Verbose output.
 	-h          Show this help.
-"
+" >&2
 	exit 0
 }
 
@@ -55,14 +55,21 @@ parse_caption() {
 }
 
 copy_photo() {
-	[ -f "$SNAPSHOT_FILE" ] || die "Snapshot not found"
+	if [ ! -f "$SNAPSHOT_FILE" ]; then
+		echo "Snapshot not found" >&2
+		exit 1
+	fi
 	photo2=$(mktemp -u).jpg
 	cp -f "$SNAPSHOT_FILE" "$photo2"
 	garbage="$garbage $photo2"
 }
 
 copy_video() {
-	[ -f "$VBUFFER_FILE" ] || die "Video buffer not found"
+	if [ ! -f "$VBUFFER_FILE" ]; then
+		echo "Video buffer not found" >&2
+		exit 1
+	fi
+
 	local ext=${VBUFFER_FILE##*.}
 	video2=$(mktemp -u).$ext
 	cp -f "$VBUFFER_FILE" "$video2"
@@ -75,12 +82,23 @@ remove_tempfiles() {
 	done
 }
 
-[ -z "$telegram_token" ] && die "Telegram token not found"
-[ -z "$telegram_channel" ] && die "Telegram channel not found"
+if [ -z "$telegram_token" ]; then
+	echo "Telegram token not found" >&2
+	exit 1
+fi
+
+if [ -z "$telegram_channel" ]; then
+	echo "Telegram channel not found" >&2
+	exit 1
+fi
 
 command="curl --show-error --fail --connect-timeout 10 --max-time 30 --retry 3 $verbosity"
 command="$command -H 'Content-Type: multipart/form-data' -F 'chat_id=$telegram_channel'"
-[ "true" = "$telegram_silent" ] && command="$command -F 'disable_notification=true'"
+
+if [ "true" = "$telegram_silent" ]; then
+	command="$command -F 'disable_notification=true'"
+fi
+
 command="$command --url https://api.telegram.org/bot$telegram_token/"
 
 # no further modifications to command after this point
@@ -90,7 +108,9 @@ if [ "true" = "$telegram_attach_video" ] && [ "true" = "$telegram_attach_photo" 
 	copy_photo
 	caption=$(parse_caption $photo2)
 	command="${command}sendMediaGroup -F 'snap=@$photo2'"
-	[ -n "$telegram_message" ] && caption="$caption - $telegram_message"
+	if [ -n "$telegram_message" ]; then
+		caption="$caption - $telegram_message"
+	fi
 	media='[{"type":"photo","media":"attach://snap","caption":"'$caption'"},'
 	inode=$(stat -c%i $VBUFFER_FILE)
 	copy_video
@@ -98,7 +118,10 @@ if [ "true" = "$telegram_attach_video" ] && [ "true" = "$telegram_attach_photo" 
 	media=$media'{"type":"video","media":"attach://video1"},'
 	while [ $inode -eq $(stat -c%i $VBUFFER_FILE) ]; do
 		n=$((n + 1))
-		[ "$n" -le 10 ] || die "Give up after $n attempts."
+		if [ "$n" -ge 10 ]; then
+			echo "Give up after $n attempts." >&2
+			exit 1
+		fi
 		sleep 1
 	done
 	copy_video
@@ -108,28 +131,38 @@ if [ "true" = "$telegram_attach_video" ] && [ "true" = "$telegram_attach_photo" 
 elif [ "true" = "$telegram_attach_video" ]; then
 	# https://core.telegram.org/bots/api#sendvideo
 	copy_video
-	caption=$(parse_caption $video2)
-	[ -n "$telegram_message" ] && caption="$caption - $telegram_message"
+	caption="$(parse_caption $video2)"
+	if [ -n "$telegram_message" ]; then
+		caption="$caption - $telegram_message"
+	fi
 	command="${command}sendVideo -F 'video=@$video2' -F 'caption=$caption'"
 elif [ "true" = "$telegram_attach_photo" ]; then
 	# https://core.telegram.org/bots/api#sendphoto
 	copy_photo
-	caption=$(parse_caption $photo2)
-	[ -n "$telegram_message" ] && caption="$caption - $telegram_message"
+	caption="$(parse_caption $photo2)"
+	if [ -n "$telegram_message" ]; then
+		caption="$caption - $telegram_message"
+	fi
 	command="${command}sendPhoto -F 'photo=@$photo2' -F 'caption=$caption'"
 elif [ -n "$telegram_message" ]; then
 	# https://core.telegram.org/bots/api#sendmessage
 	command="${command}sendMessage -F 'text=$telegram_message'"
 elif [ -n "$telegram_file" ] && [ -f "$telegram_file" ]; then
 	# https://core.telegram.org/bots/api#senddocument
-	caption=$(parse_caption $telegram_file)
-	[ -n "$telegram_message" ] && caption="$caption - $telegram_message"
+	caption="$(parse_caption $telegram_file)"
+	if [ -n "$telegram_message" ]; then
+		caption="$caption - $telegram_message"
+	fi
 	command="${command}sendDocument -F 'document=@$1' -F 'caption=$caption'"
 else
-	die "Nothing to send"
+	echo "Nothing to send" >&2
+	exit 1
 fi
 
-sh -c "$command" || die "Failed to send message to Telegram"
+if ! sh -c "$command"; then
+	echo "Failed to send message to Telegram" >&2
+	exit 1
+fi
 
 remove_tempfiles
 
diff --git a/overlay/lower/usr/sbin/send2webhook b/overlay/lower/usr/sbin/send2webhook
--- a/overlay/lower/usr/sbin/send2webhook
+++ b/overlay/lower/usr/sbin/send2webhook
@@ -10,7 +10,7 @@ Where:
 	-u url      Webhook URL.
 	-v          Verbose output.
 	-h          Show this help.
-"
+" >&2
 	exit 0
 }
 
@@ -25,7 +25,10 @@ while getopts m:su:vh flag; do
 	esac
 done
 
-[ -z "$webhook_url" ] && die "Webhook URL not found"
+if [ -z "$webhook_url" ]; then
+	echo "Webhook URL not found" >&2
+	exit 1
+fi
 
 if [ "true" = "$webhook_attach_snapshot" ]; then
 	attachment=$(mktemp -u).jpg
@@ -38,7 +41,10 @@ fi
 command="curl --show-error --fail --connect-timeout 10 --max-time 30 --retry 3 $verbosity"
 command="$command $data --url $webhook_url"
 
-sh -c "$command" || die "Failed to send webhook message"
+if ! sh -c "$command"; then
+	echo "Failed to send webhook message" >&2
+	exit 1
+fi
 
 [ -f "$attachment" ] && rm "$attachment"
 
diff --git a/overlay/lower/usr/sbin/send2yadisk b/overlay/lower/usr/sbin/send2yadisk
--- a/overlay/lower/usr/sbin/send2yadisk
+++ b/overlay/lower/usr/sbin/send2yadisk
@@ -11,7 +11,7 @@ Where:
 	-P password Yandex Disk username.
 	-v          Verbose output.
 	-h          Show this help.
-"
+" >&2
 	exit 0
 }
 
@@ -27,8 +27,15 @@ while getopts d:f:P:u:vh flag; do
 	esac
 done
 
-[ -z "$yadisk_username" ] && die "Yandex Disk username not found"
-[ -z "$yadisk_password" ] && die "Yandex Disk password not found"
+if [ -z "$yadisk_username" ]; then
+	echo "Yandex Disk username not found" >&2
+	exit 1
+fi
+
+if [ -z "$yadisk_password" ]; then
+	echo "Yandex Disk password not found" >&2
+	exit 1
+fi
 
 if [ -z "$yadisk_file" ]; then
 	attachment=$(mktemp -u).jpg
@@ -50,14 +57,19 @@ subdir="${subdir// /%20}" # convert each space into %20
 for subdir in ${subdirs//\// }; do
 	subdir="${subdirs%%/*}"  # leftmost directory
 	suburl="$suburl/$subdir"
-	[ -n "$subdir" ] && sh -c "$command --request MKCOL $url$suburl"
+	if [ -n "$subdir" ]; then
+		sh -c "$command --request MKCOL $url$suburl"
+	fi
 	subdirs="${subdirs#*/}" # remove the processed directory
 done
 
 command="$command --request PUT --upload-file $yadisk_file"
 command="$command --url $url/$yadisk_path/$(TZ=$(cat /etc/TZ) date +"%G%m%d-%H%M%S").jpg"
 
-sh -c "$command" || die "Failed to upload file to Yandex Disk"
+if ! sh -c "$command"; then
+	echo "Failed to upload file to Yandex Disk" >&2
+	exit 1
+fi
 
 [ -f "$attachment" ] && rm "$attachment"
 
diff --git a/overlay/lower/usr/sbin/service b/overlay/lower/usr/sbin/service
--- a/overlay/lower/usr/sbin/service
+++ b/overlay/lower/usr/sbin/service
@@ -12,7 +12,7 @@ Where actions:
 	enable    Enable the service on boot
 	disable   Disable the service on boot
 	list      List all services
-"
+" >&2
 	exit 1
 fi
 
@@ -21,14 +21,14 @@ SERVICE=$2
 
 SCRIPT=$(ls /etc/init.d/[FKS][0-9][0-9]$SERVICE 2> /dev/null)
 if [ "$1" != "list" ] && [ -z "$SCRIPT" ]; then
-	echo "Service $SERVICE not found"
+	echo "Service $SERVICE not found" >&2
 	exit 1
 fi
 
 case "$ACTION" in
 	start | stop | reload | restart)
 		if ! $SCRIPT $ACTION; then
-			echo "Failed to $ACTION $SERVICE"
+			echo "Failed to $ACTION $SERVICE" >&2
 			exit 1
 		fi
 		;;
@@ -43,7 +43,7 @@ case "$ACTION" in
 		chmod -x $SCRIPT
 		;;
 	*)
-		echo "Invalid action: $ACTION"
+		echo "Invalid action: $ACTION" >&2
 		exit 1
 		;;
 esac
diff --git a/overlay/lower/usr/sbin/timelapse b/overlay/lower/usr/sbin/timelapse
--- a/overlay/lower/usr/sbin/timelapse
+++ b/overlay/lower/usr/sbin/timelapse
@@ -20,7 +20,7 @@ timelapse_mount=${timelapse_mount%/}
 timelapse_device_path=${timelapse_device_path%/}
 
 if [ -z "$timelapse_mount" ]; then
-	echo "'timelapse_mount' is not set"
+	echo "'timelapse_mount' is not set" >&2
 	exit 1
 fi
 
@@ -40,13 +40,13 @@ if [ ! -d "$timelapse_storage" ]; then
 	echo "Creating $timelapse_storage" >&2
 
 	if ! mkdir -vp "$timelapse_storage"; then
-		echo "Cannot create directory $timelapse_storage"
+		echo "Cannot create directory $timelapse_storage" >&2
 		exit 1
 	fi
 fi
 
 if [ ! -w "$timelapse_storage" ]; then
-	echo "Cannot write to $timelapse_storage"
+	echo "Cannot write to $timelapse_storage" >&2
 	exit 1
 fi
 
