scripts: expand and simplify conditions

diff --git a/overlay/lower/usr/sbin/odhcp6c-update b/overlay/lower/usr/sbin/odhcp6c-update
--- a/overlay/lower/usr/sbin/odhcp6c-update
+++ b/overlay/lower/usr/sbin/odhcp6c-update
@@ -7,7 +7,10 @@ fi
 
 # Define the base directory for tracking DHCPv6 data
 DHCP6_DATA_BASE="/var/run/odhcp6c"
-mkdir -p "$DHCP6_DATA_BASE" || { echo "Error: cannot create $DHCP6_DATA_BASE"; exit 1; }
+if ! mkdir -p "$DHCP6_DATA_BASE"; then
+	echo "Error: cannot create $DHCP6_DATA_BASE"
+	exit 1
+fi
 
 write_lease() {
 	local device="$1"
@@ -142,13 +145,17 @@ update_resolv() {
 
 		# Add unique search domains to resolv.conf
 		for domain in $domains; do
-			grep -q "search $domain" /tmp/resolv.conf.tmp || echo "search $domain # added by odhcp6c" >> /tmp/resolv.conf.tmp
+			if ! grep -q "search $domain" /tmp/resolv.conf.tmp; then
+				echo "search $domain # added by odhcp6c" >> /tmp/resolv.conf.tmp
+			fi
 			echo "added search $domain"
 		done
 
 		# Add unique DNS servers to resolv.conf
 		for c in $dns; do
-			grep -q "nameserver $c" /tmp/resolv.conf.tmp || echo "nameserver $c # added by odhcp6c" >> /tmp/resolv.conf.tmp
+			if ! grep -q "nameserver $c" /tmp/resolv.conf.tmp; then
+				echo "nameserver $c # added by odhcp6c" >> /tmp/resolv.conf.tmp
+			fi
 			echo "added nameserver $c"
 		done
 
@@ -217,7 +224,9 @@ setup_interface() {
 	read -r dns domains < <(extract_dns_and_domains "$lease_file")
 
 	# Call update_resolv to update resolv.conf with DNS information and search domains
-	[ -n "$dns" ] && update_resolv "$dns" "$domains"
+	if [ -n "$dns" ]; then
+		update_resolv "$dns" "$domains"
+	fi
 
 	# Write the lease information to a file
 	write_lease "$device"
@@ -285,7 +294,9 @@ teardown_interface() {
 	esac
 
 	# Execute user-defined rules if present
-	[ -f /etc/odhcp6c.user ] && . /etc/odhcp6c.user
+	if [ -f /etc/odhcp6c.user ]; then
+		. /etc/odhcp6c.user
+	fi
 ) 8>/tmp/odhcp6c.lock.$1
 
 rm -f /tmp/odhcp6c.lock.$1
diff --git a/overlay/lower/usr/sbin/timelapse b/overlay/lower/usr/sbin/timelapse
--- a/overlay/lower/usr/sbin/timelapse
+++ b/overlay/lower/usr/sbin/timelapse
@@ -19,23 +19,48 @@ hesitate() {
 timelapse_mount=${timelapse_mount%/}
 timelapse_device_path=${timelapse_device_path%/}
 
-[ -z "$timelapse_mount" ] && die "'timelapse_mount' is not set"
+if [ -z "$timelapse_mount" ]; then
+	echo "'timelapse_mount' is not set"
+	exit 1
+fi
 
 # wait for mount point
-mountpoint -q "$timelapse_mount" || hesitate "$timelapse_mount is not mounted"
-[ -w "$timelapse_mount" ] || hesitate "$timelapse_mount is not writable"
+if ! mountpoint -q "$timelapse_mount" >/dev/null; then
+	hesitate "$timelapse_mount is not mounted"
+fi
+
+if [ ! -w "$timelapse_mount" ]; then
+	hesitate "$timelapse_mount is not writable"
+fi
 
 # storage directory
 timelapse_storage="$timelapse_mount/$timelapse_device_path"
+
 if [ ! -d "$timelapse_storage" ]; then
 	echo "Creating $timelapse_storage" >&2
-	mkdir -vp "$timelapse_storage" || die "Cannot create directory $timelapse_storage"
-fi
-[ -w "$timelapse_storage" ] || die "Cannot write to $timelapse_storage"
 
-[ -z "$timelapse_depth" ] && timelapse_depth=7
-[ -z "$timelapse_filename" ] && timelapse_filename="%Y/%m/%d/%H%M.jpg"
-[ -z "$timelapse_interval" ] && timelapse_interval=1
+	if ! mkdir -vp "$timelapse_storage"; then
+		echo "Cannot create directory $timelapse_storage"
+		exit 1
+	fi
+fi
+
+if [ ! -w "$timelapse_storage" ]; then
+	echo "Cannot write to $timelapse_storage"
+	exit 1
+fi
+
+if [ -z "$timelapse_depth" ]; then
+	timelapse_depth=7
+fi
+
+if [ -z "$timelapse_filename" ]; then
+	timelapse_filename="%Y/%m/%d/%H%M.jpg"
+fi
+
+if [ -z "$timelapse_interval" ]; then
+	timelapse_interval=1
+fi
 
 # delete older files
 find "$timelapse_storage" -type f -name '*.jpg' -mtime +$timelapse_depth -exec rm {} \;
