prepare for mp4 video

diff --git a/overlay/lower/usr/sbin/send2email b/overlay/lower/usr/sbin/send2email
--- a/overlay/lower/usr/sbin/send2email
+++ b/overlay/lower/usr/sbin/send2email
@@ -18,7 +18,6 @@ Where:
 	exit 0
 }
 
-verbosity="--silent"
 while getopts b:f:kn:p:s:t:vh flag; do
 	case "$flag" in
 		b) email_body=$OPTARG ;;
@@ -28,58 +27,37 @@ while getopts b:f:kn:p:s:t:vh flag; do
 		p) email_smtp_port=$OPTARG ;;
 		s) email_subject=$OPTARG ;;
 		t) email_to_address=$OPTARG ;;
-		v) verbosity="--verbose" ;;
+		v) verbose="true" ;;
 		h | *) show_help ;;
 	esac
 done
 
-if [ -z "$email_smtp_host" ]; then
-	echo_error "SMTP host not found"
-	exit 1
+# validators
+[ -z "$email_smtp_host" ] && die "SMTP host not found"
+[ -z "$email_from_address" ] && die "Sender's email address not found"
+[ -z "$email_to_address" ] && die "Recipient's email address not found"
+[ -z "$email_body" ] && die "Email body not found"
+
+echo "$email_from_address" | grep -E -q $EMAIL_FORMAT >/dev/null || die "Invalid sender email address format"
+echo "$email_to_address" | grep -E -q $EMAIL_FORMAT >/dev/null || die "Invalid recipient email address format"
+
+# defaults
+[ -z "$email_smtp_port" ] && email_smtp_port=25
+[ -z "$email_from_name" ] && email_from_name="Thingino Camera"
+[ -z "$email_to_name" ] && email_to_name="Thingino Camera Admin"
+[ -z "$email_subject" ] && email_subject="Snapshot from Thingino Camera"
+
+# sanitizers
+email_body=${email_body//"/\\"}
+
+# command
+if [ "true" = "$verbose" ]; then
+	command="$CURL --verbose"
+else
+	command="$CURL --silent"
 fi
 
-if [ -z "$email_smtp_port" ]; then
-	email_smtp_port=25
-fi
-
-if [ -z "$email_from_address" ]; then
-	echo_error "Sender's email address not found"
-	exit 1
-fi
-
-if [ -z "$email_to_address" ]; then
-	echo_error "Recipient's email address not found"
-	exit 1
-fi
-
-if [ -z "$email_body" ]; then
-	echo_error "Email body not found"
-	exit 1
-fi
-
-if ! echo "$email_from_address" | grep -E -q $EMAIL_FORMAT >/dev/null; then
-	echo_error "Invalid sender email address format"
-	exit 1
-fi
-
-if ! echo "$email_to_address" | grep -E -q $EMAIL_FORMAT >/dev/null; then
-	echo_error "Invalid recipient email address format"
-	exit 1
-fi
-
-if [ -z "$email_from_name" ]; then
-	email_from_name="Thingino Camera"
-fi
-
-if [ -z "$email_to_name" ]; then
-	email_to_name="Thingino Camera Admin"
-fi
-
-if [ -z "$email_subject" ]; then
-	email_subject="Snapshot from Thingino Camera"
-fi
-
-command="$CURL $verbosity --mail-from $email_from_address --mail-rcpt $email_to_address"
+command="$command --mail-from $email_from_address --mail-rcpt $email_to_address"
 
 if [ -n "$email_smtp_username" ] && [ -n "$email_smtp_password" ]; then
 	command="$command --user '$email_smtp_username:$email_smtp_password'"
@@ -87,14 +65,11 @@ fi
 
 if [ "true" = "$email_smtp_use_ssl" ]; then
 	command="$command --url smtps://$email_smtp_host:$email_smtp_port --ssl"
-	if [ "true" = "$email_insecure_ssl" ]; then
-		command="$command --insecure"
-	fi
+	[ "true" = "$email_insecure_ssl" ] && command="$command --insecure"
 else
 	command="$command --url smtp://$email_smtp_host:$email_smtp_port"
 fi
 
-email_body=${email_body//"/\\"}
 command="$command -H 'From: \"$email_from_name\" <$email_from_address>'"
 command="$command -H 'To: \"$email_to_name\" <$email_to_address>'"
 command="$command -H 'Subject: $email_subject'"
@@ -107,25 +82,19 @@ if [ "true" = "$email_attach_snapshot" ]; then
 	command="$command -F 'snapshot=@$photo_attachment;type=image/jpeg;encoder=base64'"
 fi
 
-if [ "true" = "$email_attach_video" ]; then
-	video_attachment=$(mktemp -u).mov
-	cp -f "$VBUFFER_FILE" "$video_attachment"
-	command="$command -F 'video=@$video_attachment;type=video/quicktime;encoder=base64'"
+if [ "true" = "$email_attach_video" ] && [ -f "$MOTION_VIDEO_FILE" ]; then
+	video_attachment="$(mktemp -u).mp4"
+	cp -f "$MOTION_VIDEO_FILE" "$video_attachment"
+	command="$command -F 'video=@$video_attachment;type=video/mp4;encoder=base64'"
 fi
 
 command="$command -F '=)'"
 
-if ! sh -c "$command"; then
-	echo_error "Failed to send email"
-	exit 1
-fi
+[ "true" = "$verbose" ] && echo_command "$command"
 
-if [ -f "$photo_attachment" ]; then
-	rm "$photo_attachment"
-fi
+sh -c "$command" || die "Failed to send email"
 
-if [ -f "$video_attachment" ]; then
-	rm "$video_attachment"
-fi
+[ -f "$photo_attachment" ] && rm "$photo_attachment"
+[ -f "$video_attachment" ] && rm "$video_attachment"
 
 exit 0
diff --git a/overlay/lower/usr/sbin/send2ftp b/overlay/lower/usr/sbin/send2ftp
--- a/overlay/lower/usr/sbin/send2ftp
+++ b/overlay/lower/usr/sbin/send2ftp
@@ -17,7 +17,6 @@ Where:
 	exit 0
 }
 
-verbosity="--silent"
 while getopts d:f:p:P:s:u:vVh flag; do
 	case "$flag" in
 		d) ftp_path=$OPTARG ;;
@@ -26,55 +25,53 @@ while getopts d:f:p:P:s:u:vVh flag; do
 		P) ftp_password=$OPTARG ;;
 		s) ftp_host=$OPTARG ;;
 		u) ftp_user=$OPTARG ;;
-		v) verbosity="--verbose" ;;
+		v) verbose="true" ;;
 		V) ftp_sendvideo="true" ;;
 		h | *) show_help ;;
 	esac
 done
 
-if [ -z "$ftp_host" ]; then
-	echo_error "FTP host not found"
-	exit 1
-fi
+# validators
+[ -z "$ftp_host" ] && die "FTP host not found"
 
-if [ -z "$ftp_port" ]; then
-	ftp_port=21
-fi
+# defaults
+[ -z "$ftp_port" ] && ftp_port=21
+[ -z "$ftp_user" ] && ftp_user="anonymous" && ftp_password="anonymous"
 
-if [ -z "$ftp_user" ]; then
-	ftp_user="anonymous"
-	ftp_password="anonymous"
-fi
-
+# attachments
 if [ -z "$ftp_file" ]; then
-	if [ "true" = "$ftp_sendvideo" ]; then
-		attachment=$(mktemp -u).mov
-		cp -f "$VBUFFER_FILE" "$attachment"
-		ftp_filename=$(date +"$ftp_template").mov
-	else
+	if [ "true" = "$ftp_sendvideo" ] && [ -f "$MOTION_VIDEO_FILE" ]; then
+		cp -f $MOTION_VIDEO_FILE "$video_attachment"
+		ftp_filename=$(date +"$ftp_template").mp4
+	fi
+
+	if [ "true" = "$ftp_sendphoto" ] && [ -f "$SNAPSHOT_FILE" ]; then
 		attachment=$(mktemp -u).jpg
-		cp -f "$SNAPSHOT_FILE" "$attachment"
+		cp -f "$SNAPSHOT_FILE" "$photo_attachment"
 		ftp_filename=$(date +"$ftp_template").jpg
 	fi
 
 	ftp_file=$attachment
 fi
 
+# ftp url
 url="ftp://"
-if [ -n "$ftp_user" ] && [ -n "$ftp_password" ]; then
-	url="$url$ftp_user:$ftp_password"
-fi
+[ -n "$ftp_user" ] && [ -n "$ftp_password" ] && url="$url$ftp_user:$ftp_password"
 url="$url@$ftp_host:$ftp_port"
-if [ -n "$ftp_path" ]; then
-	url="$url/${ftp_path// /%20}"
-fi
+[ -n "$ftp_path" ] && url="$url/${ftp_path// /%20}"
 url="$url/$ftp_filename"
 
-command="$CURL $verbosity --url $url --upload-file $ftp_file --ftp-create-dirs"
-if ! sh -c "$command"; then
-	echo_error "Failed to upload file to FTP server"
-	exit 1
+# command
+if [ "true" = "$verbose" ]; then
+	command="$CURL --verbose"
+else
+	command="$CURL --silent"
 fi
+command="$command --url $url --upload-file $ftp_file --ftp-create-dirs"
+
+[ "true" = "$verbose" ] && echo_command "$command"
+
+sh -c "$command" || die "Failed to upload file to FTP server"
 
 [ -f "$attachment" ] && rm "$attachment"
 
diff --git a/overlay/lower/usr/sbin/send2mqtt b/overlay/lower/usr/sbin/send2mqtt
--- a/overlay/lower/usr/sbin/send2mqtt
+++ b/overlay/lower/usr/sbin/send2mqtt
@@ -20,7 +20,6 @@ Where:
 	exit 0
 }
 
-verbosity="false"
 while getopts h:jm:st:u:w:v flag; do
 	case "$flag" in
 		h) mqtt_host=$OPTARG ;;
@@ -30,54 +29,30 @@ while getopts h:jm:st:u:w:v flag; do
 		t) mqtt_topic=$OPTARG ;;
 		u) mqtt_username=$OPTARG ;;
 		w) mqtt_password=$OPTARG ;;
-		v) verbosity="true" ;;
+		v) verbose="true" ;;
 		*) show_help ;;
 	esac
 done
 
-if [ -z "$mqtt_host" ]; then
-	echo_error "MQTT broker host is not set"
-	exit 1
-fi
+# validators
+[ -z "$mqtt_host" ] && die "MQTT broker host is not set"
+[ -z "$mqtt_port" ] && die "MQTT broker port is not set"
+[ -z "$mqtt_topic" ] && die "MQTT topic not found"
+[ -z "$mqtt_message" ] && die "MQTT message template not found"
+[ "true" = "$mqtt_send_snap" ] && \
+[ -z "$mqtt_snap_topic" ] && die "MQTT topic for sending snapshot not found in config"
 
-if [ -z "$mqtt_port" ]; then
-	echo_error "MQTT broker port is not set"
-	exit 1
-fi
+# defaults
+[ -z "$mqtt_client_id" ] && mqtt_client_id="$network_hostname"
 
-if [ -z "$mqtt_topic" ]; then
-	echo_error "MQTT topic not found"
-	exit 1
-fi
-
-if [ -z "$mqtt_message" ]; then
-	echo_error "MQTT message template not found"
-	exit 1
-fi
-
-if [ "true" = "$mqtt_send_snap" ] && [ -z "$mqtt_snap_topic" ]; then
-	echo_error "MQTT topic for sending snapshot not found in config"
-	exit 1
-fi
-
-if [ -z "$mqtt_client_id" ]; then
-	mqtt_client_id="$network_hostname"
-fi
-
+# sanitizers
 mqtt_message=$(date +"$mqtt_message")
 
+# command
 command="mosquitto_pub -h $mqtt_host -p $mqtt_port -i $mqtt_client_id"
-if [ "true" = "$verbosity" ]; then
-	command="$command -d"
-fi
-
-if [ -n "$mqtt_username" ]; then
-	command="$command -u $mqtt_username"
-fi
-
-if [ -n "$mqtt_password" ]; then
-	command="$command -P $mqtt_password"
-fi
+[ "true" = "$verbose" ] && command="$command -d"
+[ -n "$mqtt_username" ] && command="$command -u $mqtt_username"
+[ -n "$mqtt_password" ] && command="$command -P $mqtt_password"
 
 if [ "true" = "$mqtt_send_snap" ]; then
 	attachment=$(mktemp -u).jpg
@@ -93,21 +68,11 @@ else
 	fi
 fi
 
-if [ "true" = "$verbosity" ]; then
-	echo_command "$command"
-fi
+[ "true" = "$verbose" ] && echo_command "$command"
 
-if ! sh -c "$command"; then
-	echo_error "Failed to send MQTT message"
-	exit 1
-fi
+sh -c "$command" || die "Failed to send MQTT message"
 
-if [ -f "$tmpfile" ]; then
-	rm "$tmpfile"
-fi
-
-if [ -f "$attachment" ]; then
-	rm "$attachment"
-fi
+[ -f "$tmpfile" ] && rm "$tmpfile"
+[ -f "$attachment" ] && rm "$attachment"
 
 exit 0
diff --git a/overlay/lower/usr/sbin/send2ntfy b/overlay/lower/usr/sbin/send2ntfy
--- a/overlay/lower/usr/sbin/send2ntfy
+++ b/overlay/lower/usr/sbin/send2ntfy
@@ -24,7 +24,6 @@ Where:
 	exit 0
 }
 
-verbosity="false"
 while getopts a:c:f:h:i:l:m:n:p:st:u:w:vh flag; do
 	case "$flag" in
 		a) ntfy_attach=$OPTARG ;;
@@ -39,57 +38,41 @@ while getopts a:c:f:h:i:l:m:n:p:st:u:w:vh flag; do
 		t) ntfy_topic=$OPTARG ;;
 		u) ntfy_username=$OPTARG ;;
 		w) ntfy_password=$OPTARG ;;
-		v) verbosity="true" ;;
+		v) verbose="true" ;;
 		*) show_help ;;
 	esac
 done
 
-if [ -z "$ntfy_host" ]; then
-	ntfy_host="ntfy.sh"
-	#echo_warning "NFTY host is not set"
-fi
+# validators
+[ -z "$ntfy_topic" ] && die "NTFY topic is not set"
 
-if [ -z "$ntfy_port" ]; then
-	ntfy_port=80
-	#echo_error "NTFY port is not set"
-fi
+# defaults
+[ -z "$ntfy_host" ] && ntfy_host="ntfy.sh"
+[ -z "$ntfy_port" ] && ntfy_port=80
 
-if [ -z "$ntfy_topic" ]; then
-	echo_error "NTFY topic is not set"
-	exit 1
-fi
-
+# attachments
 remove_ntfy_file="false"
 
-# Prepare snapshot as attachment
 if [ "true" = "$ntfy_send_snap" ]; then
 	ntfy_filename=$(mktemp -u).jpg
 	cp -f "$SNAPSHOT_FILE" "$ntfy_filename"
 	remove_ntfy_file="true"
 fi
 
-command="$CURL -X POST -H p:${ntfy_priority:-3}"
-if [ "true" = "$verbosity" ]; then
-	command="$command --verbose"
+# command
+if [ "true" = "$verbose" ]; then
+	command="$CURL --verbose"
 else
-	command="$command --silent"
+	command="$CURL --silent"
 fi
 
-if [ -n "$ntfy_title" ]; then
-	command="$command -H 'Title: $ntfy_title'"
-fi
+command="$command -X POST -H p:${ntfy_priority:-3}"
 
-if [ -n "$ntfy_tags" ]; then
-	command="$command -H 'Tags: $ntfy_tags'"
-fi
-
-if [ -n "$ntfy_delay" ]; then
-	command="$command -H 'Delay: $ntfy_delay'"
-fi
-
-if [ -n "$ntfy_username" ] && [ -n "$ntfy_password" ]; then
-	command="$command -u $ntfy_username:$ntfy_password"
-fi
+[ -n "$ntfy_title" ] && command="$command -H 'Title: $ntfy_title'"
+[ -n "$ntfy_tags" ] && command="$command -H 'Tags: $ntfy_tags'"
+[ -n "$ntfy_delay" ] && command="$command -H 'Delay: $ntfy_delay'"
+[ -n "$ntfy_username" ] && \
+[ -n "$ntfy_password" ] && command="$command -u $ntfy_username:$ntfy_password"
 
 if [ "true" = "$ntfy_send_snap" ]; then
 	attachment=$(mktemp -u).jpg
@@ -97,33 +80,15 @@ if [ "true" = "$ntfy_send_snap" ]; then
 	command="$command -T $attachment -H 'Filename: $attachment'"
 fi
 
-if [ -n "$ntfy_filename" ] && [ -f "$ntfy_filename" ]; then
-	command="$command -T $ntfy_filename -H 'Filename: $ntfy_filename'"
-fi
-
-if [ -n "$ntfy_attach" ]; then
-	command="$command -H 'Attach: $ntfy_attach'"
-fi
-
-if [ -n "$ntfy_click" ]; then
-	command="$command -H 'Click: $ntfy_click'"
-fi
-
-if [ -n "$ntfy_icon" ]; then
-	command="$command -H 'Icon: $ntfy_icon'"
-fi
-
-if [ -n "$ntfy_email" ]; then
-	command="$command -H 'Email: $ntfy_email'"
-fi
-
-if [ -n "$ntfy_actions" ]; then
-	command="$command -H 'Actions: $ntfy_actions'"
-fi
-
-if [ -n "$ntfy_call" ] && [ -n "$ntfy_twilio_token" ]; then
-	command="$command -H 'Call: $ntfy_call' -u :$ntfy_twilio_token"
-fi
+[ -n "$ntfy_filename" ] && \
+[ -f "$ntfy_filename" ] && command="$command -T $ntfy_filename -H 'Filename: $ntfy_filename'"
+[ -n "$ntfy_attach"   ] && command="$command -H 'Attach: $ntfy_attach'"
+[ -n "$ntfy_click"    ] && command="$command -H 'Click: $ntfy_click'"
+[ -n "$ntfy_icon"     ] && command="$command -H 'Icon: $ntfy_icon'"
+[ -n "$ntfy_email"    ] && command="$command -H 'Email: $ntfy_email'"
+[ -n "$ntfy_actions"  ] && command="$command -H 'Actions: $ntfy_actions'"
+[ -n "$ntfy_twilio_token" ] && \
+[ -n "$ntfy_call"     ] && command="$command -H 'Call: $ntfy_call' -u :$ntfy_twilio_token"
 
 if [ -n "$ntfy_message" ]; then
 	ntfy_message="$(date +"$ntfy_message")"
@@ -132,17 +97,10 @@ fi
 
 command="$command ${ntfy_host:-ntfy.sh}/$ntfy_topic"
 
-if [ "true" = "$verbosity" ]; then
-	echo_command "$command"
-fi
+[ "true" = "$verbose" ] && echo_command "$command"
 
-if ! sh -c "$command"; then
-	echo_error "Failed to send NTFY message"
-	exit 1
-fi
+sh -c "$command" || die "Failed to send NTFY message"
 
-if [ "true" = "$remove_ntfy_file" ] && [ -f "$ntfy_filename" ]; then
-	rm "$ntfy_filename"
-fi
+[ "true" = "$remove_ntfy_file" ] && [ -f "$ntfy_filename" ] && rm "$ntfy_filename"
 
 exit 0
diff --git a/overlay/lower/usr/sbin/send2telegram b/overlay/lower/usr/sbin/send2telegram
--- a/overlay/lower/usr/sbin/send2telegram
+++ b/overlay/lower/usr/sbin/send2telegram
@@ -54,49 +54,39 @@ parse_caption() {
 }
 
 copy_photo() {
-	if [ ! -f "$SNAPSHOT_FILE" ]; then
-		echo_error "Snapshot not found"
-		exit 1
-	fi
+	[ -f "$SNAPSHOT_FILE" ] || die "Snapshot not found"
 	photo2=$(mktemp -u).jpg
 	cp -f "$SNAPSHOT_FILE" "$photo2"
 	garbage="$garbage $photo2"
 }
 
 copy_video() {
-	if [ ! -f "$VBUFFER_FILE" ]; then
-		echo_error "Video buffer not found"
-		exit 1
-	fi
-
-	local ext=${VBUFFER_FILE##*.}
-	video2=$(mktemp -u).$ext
-	cp -f "$VBUFFER_FILE" "$video2"
+	[ -f "$MOTION_VIDEO_FILE" ] || die "Video not found"
+	video2=$(mktemp -u).mp4
+	cp -f "$MOTION_VIDEO_FILE" "$video2"
 	garbage="$garbage $video2"
 }
 
-remove_tempfiles() {
+cleanup() {
 	for f in $garbage; do
 		[ -f "$f" ] && rm "$f"
 	done
 }
 
-if [ -z "$telegram_token" ]; then
-	echo_error "Telegram token not found"
-	exit 1
+# validators
+[ -z "$telegram_token" ] && die "Telegram token not found"
+[ -z "$telegram_channel" ] && die "Telegram channel not found"
+
+# command
+if [ "true" = "$verbose" ]; then
+	command="$CURL --verbose"
+else
+	command="$CURL --silent"
 fi
 
-if [ -z "$telegram_channel" ]; then
-	echo_error "Telegram channel not found"
-	exit 1
-fi
+command="$command -H 'Content-Type: multipart/form-data' -F 'chat_id=$telegram_channel'"
 
-[ "true" = "$verbose" ] && verbosity="--verbose" || verbosity="--silent"
-command="$CURL $verbosity -H 'Content-Type: multipart/form-data' -F 'chat_id=$telegram_channel'"
-
-if [ "true" = "$telegram_silent" ]; then
-	command="$command -F 'disable_notification=true'"
-fi
+[ "true" = "$telegram_silent" ] && command="$command -F 'disable_notification=true'"
 
 command="$command --url https://api.telegram.org/bot$telegram_token/"
 
@@ -107,23 +97,8 @@ if [ "true" = "$telegram_attach_video" ] && [ "true" = "$telegram_attach_photo" 
 	copy_photo
 	caption=$(parse_caption $photo2)
 	command="${command}sendMediaGroup -F 'snap=@$photo2'"
-	if [ -n "$telegram_message" ]; then
-		caption="$caption - $telegram_message"
-	fi
+	[ -n "$telegram_message" ] && caption="$caption - $telegram_message"
 	media='[{"type":"photo","media":"attach://snap","caption":"'$caption'"},'
-	inode=$(stat -c%i $VBUFFER_FILE)
-	copy_video
-	command="$command -F 'video1=@$video2'"
-	media=$media'{"type":"video","media":"attach://video1"},'
-	while [ $inode -eq $(stat -c%i $VBUFFER_FILE) ]; do
-		n=$((n + 1))
-		if [ "$n" -ge 10 ]; then
-			echo_error "Give up after $n attempts."
-			remove_tempfiles
-			exit 1
-		fi
-		sleep 1
-	done
 	copy_video
 	command="$command -F 'video2=@$video2'"
 	media=$media'{"type":"video","media":"attach://video2"}]'
@@ -132,17 +107,13 @@ elif [ "true" = "$telegram_attach_video" ]; then
 	# https://core.telegram.org/bots/api#sendvideo
 	copy_video
 	caption="$(parse_caption $video2)"
-	if [ -n "$telegram_message" ]; then
-		caption="$caption - $telegram_message"
-	fi
+	[ -n "$telegram_message" ] && caption="$caption - $telegram_message"
 	command="${command}sendVideo -F 'video=@$video2' -F 'caption=$caption'"
 elif [ "true" = "$telegram_attach_photo" ]; then
 	# https://core.telegram.org/bots/api#sendphoto
 	copy_photo
 	caption="$(parse_caption $photo2)"
-	if [ -n "$telegram_message" ]; then
-		caption="$caption - $telegram_message"
-	fi
+	[ -n "$telegram_message" ] && caption="$caption - $telegram_message"
 	command="${command}sendPhoto -F 'photo=@$photo2' -F 'caption=$caption'"
 elif [ -n "$telegram_message" ]; then
 	# https://core.telegram.org/bots/api#sendmessage
@@ -150,22 +121,19 @@ elif [ -n "$telegram_message" ]; then
 elif [ -n "$telegram_file" ] && [ -f "$telegram_file" ]; then
 	# https://core.telegram.org/bots/api#senddocument
 	caption="$(parse_caption $telegram_file)"
-	if [ -n "$telegram_message" ]; then
-		caption="$caption - $telegram_message"
-	fi
+	[ -n "$telegram_message" ] && caption="$caption - $telegram_message"
 	command="${command}sendDocument -F 'document=@$1' -F 'caption=$caption'"
 else
-	echo_error "Nothing to send"
-	exit 1
+	die "Nothing to send"
 fi
 
-echo_command "$command"
+[ "true" = "$verbose" ] && echo_command "$command"
+
 if ! sh -c "$command" >/dev/null; then
-	echo_error "Failed to send message to Telegram"
-	remove_tempfiles
-	exit 1
+	cleanup
+	die "Failed to send message to Telegram"
 fi
 
-remove_tempfiles
+cleanup
 
 exit 0
