send2webhook: add support for videoclip

diff --git a/overlay/lower/usr/sbin/send2webhook b/overlay/lower/usr/sbin/send2webhook
--- a/overlay/lower/usr/sbin/send2webhook
+++ b/overlay/lower/usr/sbin/send2webhook
@@ -7,6 +7,7 @@ show_help() {
 Where:
 	-m message  Message to send to webhook.
 	-s          Attach snapshot to the webhook.
+	-c          Attach videoclip to the webhook.
 	-u url      Webhook URL.
 	-v          Verbose output.
 	-h          Show this help.
@@ -14,10 +15,11 @@ Where:
 	exit 0
 }
 
-while getopts m:su:vh flag; do
+while getopts m:scu:vh flag; do
 	case "$flag" in
 		m) webhook_message=$OPTARG ;;
 		s) webhook_attach_snapshot="true" ;;
+		c) webhook_attach_videoclip="true" ;;
 		u) webhook_url=$OPTARG ;;
 		v) verbose="true" ;;
 		h | *) show_help ;;
@@ -35,15 +37,27 @@ else
 	command="$CURL --silent"
 fi
 
+# Handle snapshot attachment
 if [ "true" = "$webhook_attach_snapshot" ]; then
-	attachment=$(mktemp -u).jpg
-	cp -f "$SNAPSHOT_FILE" "$attachment"
-	command="$command -F \"message=$webhook_message\" -F \"image=@$attachment\""
-else
-	command="$command -d \"$webhook_message\""
+	snapshot_attachment=$(mktemp -u).jpg
+	cp -f "$SNAPSHOT_FILE" "$snapshot_attachment"
+	command="$command -F \"image=@$snapshot_attachment\""
 fi
 
-command="$command --url $webhook_url"
+# Handle videoclip attachment
+if [ "true" = "$webhook_attach_videoclip" ]; then
+	if [ -f "$VBUFFER_FILE" ]; then
+		videoclip_attachment=$(mktemp -u).mp4
+		cp -f "$VBUFFER_FILE" "$videoclip_attachment"
+		command="$command -F \"videoclip=@$videoclip_attachment\""
+	else
+		echo_error "Videoclip not found: $VBUFFER_FILE"
+		exit 1
+	fi
+fi
+
+# Add message and url to the command
+command="$command -F \"message=$webhook_message\" --url \"$webhook_url\""
 
 if [ "true" = "$verbose" ]; then
 	echo_command "$command"
@@ -59,6 +73,8 @@ else
 	exit 1
 fi
 
-[ -f "$attachment" ] && rm "$attachment"
+# Cleanup temporary files
+[ -f "$snapshot_attachment" ] && rm "$snapshot_attachment"
+[ -f "$videoclip_attachment" ] && rm "$videoclip_attachment"
 
 exit 0
