scripts: rewrite service script, add actions to enable/disable a service

diff --git a/overlay/lower/usr/sbin/service b/overlay/lower/usr/sbin/service
--- a/overlay/lower/usr/sbin/service
+++ b/overlay/lower/usr/sbin/service
@@ -1,19 +1,44 @@
 #!/bin/sh
 
-. /etc/init.d/rc.common
-
-[ "$#" -ne 2 ] && die "Usage: service <start|stop|restart|reload> <servicename>"
+if [ "$#" -ne 2 ]; then
+	echo "Usage: service <action> <servicename>
+Where actions:
+	start     Start the service
+	stop      Stop the service
+	restart   Restart the service
+	reload    Reload the service
+	enable    Enable the service on boot
+	disable   Disable the service on boot
+"
+	exit 1
+fi
 
 ACTION=$1
 SERVICE=$2
 
+SCRIPT=$(ls /etc/init.d/[FKS][0-9][0-9]$SERVICE 2> /dev/null)
+if [ -z "$SCRIPT" ]; then
+	echo "Service $SERVICE not found"
+	exit 1
+fi
+
 case "$ACTION" in
-	start | stop | reload | restart) true ;;
-	*) die "Invalid action: $ACTION" ;;
+	start | stop | reload | restart)
+		if ! $SCRIPT $ACTION; then
+			echo "Failed to $ACTION $SERVICE"
+			exit 1
+		fi
+		;;
+	enable)
+		chmod +x $SCRIPT
+		;;
+	disable)
+		chmod -x $SCRIPT
+		;;
+	*)
+		echo "Invalid action: $ACTION"
+		exit 1
+		;;
 esac
 
-SCRIPT=$(ls /etc/init.d/[FKS][0-9][0-9]$SERVICE 2> /dev/null)
-
-[ -z "$SCRIPT" ] && die "Service $SERVICE not found"
-
-$SCRIPT $ACTION || die "Failed to $ACTION $SERVICE"
+exit 0
