sysupgrade: download & flash given url

diff --git a/overlay/lower/usr/sbin/sysupgrade b/overlay/lower/usr/sbin/sysupgrade
--- a/overlay/lower/usr/sbin/sysupgrade
+++ b/overlay/lower/usr/sbin/sysupgrade
@@ -10,16 +10,17 @@ die() {
 }
 
 show_help() {
-	echo "Usage: $0 <filename> | [-f | -p]
+	echo "Usage: $0 <filename> | [-f | -p] | <URL>
 Where:
   -f          full upgrade with a binary from GitHub
   -p          partial upgrade with a binary from GitHub
   <filename>  full or partial upgrade from a local file
+  <URL>       download and upgrade from the specified URL
 "
 	exit 0
 }
 
-while getopts fp flag; do
+while getopts "fp" flag; do
 	case "$flag" in
 		f)
 			upgrade="full"
@@ -29,6 +30,8 @@ while getopts fp flag; do
 			;;
 	esac
 done
+
+shift $(($OPTIND - 1))
 
 if [ -z "$upgrade" ]; then
 	upgrade="local"
@@ -41,6 +44,14 @@ else
 		die "Building profile is not set in $data"
 	fi
 	binary_file=$(mktemp -u)
+fi
+
+if [[ "$1" =~ ^https?:// ]]; then
+	echo "Downloading firmware from $1."
+	binary_file=$(mktemp)  # Create a temporary file
+	if ! curl -# -L -f -o $binary_file $1; then
+		die "Failed to download firmware from $1. Exiting."
+	fi
 fi
 
 if ! grep -q -e "mtd6" -e "mtd5" /proc/mtd; then
