Another one

diff --git a/overlay/lower/usr/sbin/sysupgrade b/overlay/lower/usr/sbin/sysupgrade
--- a/overlay/lower/usr/sbin/sysupgrade
+++ b/overlay/lower/usr/sbin/sysupgrade
@@ -248,13 +248,13 @@ if [ -z "$upgrade" ]; then
 		say "Upgrade from a remote file"
 		url="$file_or_url"
 	else
-		say "Upgrade from a local file $fw_file"
+		say "Upgrade from a local file"
 		if [ -f "$fw_file" ]; then
 			say "Found $fw_file"
 		else
 			if ufile="$(realpath "$file_or_url")" && [ -r "$ufile" ]; then
 				say "Found $ufile"
-				mv -v "$ufile" "$fw_file"
+				mv -v "$ufile" "$fw_file" || die "Cannot move $ufile to $fw_file"
 			else
 				die "Cannot find file $file_or_url"
 			fi
