sysupgrade: drop rc.common

diff --git a/overlay/lower/usr/sbin/sysupgrade b/overlay/lower/usr/sbin/sysupgrade
--- a/overlay/lower/usr/sbin/sysupgrade
+++ b/overlay/lower/usr/sbin/sysupgrade
@@ -1,7 +1,5 @@
 #!/bin/sh
 
-. /etc/init.d/rc.common
-
 KERNEL_MAGIC="27051956"
 U_BOOT_MAGIC="06050403"
 ROOTFS_MAGIC="68737173"
@@ -34,7 +32,7 @@ Where:
 
 stop_service() {
 	if [ ! -f "/etc/init.d/$1" ]; then
-		info "Not found"
+		echo "Not found"
 		return
 	fi
 	/etc/init.d/"$1" stop
@@ -45,17 +43,21 @@ verify_checksum() {
 	firmware_file="$2"
 
 	checksum_file=$(mktemp)
-	info "Downloading SHA-256 checksum from $checksum_url"
-	curl -# -L -f -o "$checksum_file" "$checksum_url" || die "Failed to download checksum from $checksum_url"
+	echo "Downloading SHA-256 checksum from $checksum_url"
+	if ! curl -# -L -f -o "$checksum_file" "$checksum_url"; then
+		echo "Failed to download checksum from $checksum_url"
+		exit 1
+	fi
 
 	# Extract the expected checksum (first field) from the downloaded file
 	expected_checksum=$(awk '{print $1}' "$checksum_file")
 	actual_checksum=$($BB_BINARY sha256sum "$firmware_file" | awk '{print $1}')
 
 	if [ "$expected_checksum" = "$actual_checksum" ]; then
-		info "SHA-256 checksum verification succeeded."
+		echo "SHA-256 checksum verification succeeded."
 	else
-		die "SHA-256 checksum verification failed! Firmware file might be corrupted."
+		echo "SHA-256 checksum verification failed! Firmware file might be corrupted."
+		exit 1
 	fi
 }
 
@@ -73,11 +75,11 @@ stop_services() {
 }
 
 flush_memory(){
-	info "Sync changes"
-	run "sync"
+	echo "Sync changes"
+	sync
 
-	info "Drop caches"
-	run "echo 3 > /proc/sys/vm/drop_caches"
+	echo "Drop caches"
+	echo 3 > /proc/sys/vm/drop_caches
 }
 
 flash_firmware() {
@@ -85,35 +87,40 @@ flash_firmware() {
 	device="$2"
 	is_gzip="$3"
 
+	echo "if $command $file | $BB_BINARY flash_sysupgrade -v - /dev/$device"
+
 	if [ "$is_gzip" = "true" ]; then
-		if $BB_BINARY zcat "$file" | $BB_BINARY flash_sysupgrade -v - /dev/"$device"; then
-			if [ "$device" = "mtd5" ]; then
+		if $command $file | $BB_BINARY flash_sysupgrade -v - /dev/$device; then
+			if [ "mtd5" = "$device" ]; then
 				/tmp/fw_setenv sysupgrade_complete false
 			fi
-			info "Upgrade complete."
+			echo "Upgrade complete."
 			reboot_func
 		else
-			die "Caution: You may need to perform a recovery flash restore before rebooting the camera!"
+			echo "Caution: You may need to perform a recovery flash restore before rebooting the camera!"
+			exit 1
 		fi
 	else
-		if $BB_BINARY flashcp -v "$file" /dev/"$device"; then
-			if [ "$device" = "mtd5" ]; then
+		if $BB_BINARY flashcp -v $file /dev/$device; then
+			if [ "mtd5" = "$device" ]; then
 				/tmp/fw_setenv sysupgrade_complete false
 			fi
-			info "Upgrade complete."
+			echo "Upgrade complete."
 			reboot_func
 		else
-			die "Caution: You may need to perform a recovery flash restore before rebooting the camera!"
+			echo "Caution: You may need to perform a recovery flash restore before rebooting the camera!"
+			exit 1
 		fi
 	fi
 }
 
 cleanup() {
+	echo "Clean up temporary files."
+
 	# Only delete files that were downloaded (flag = 1)
 	[ "$downloaded_file" -eq 1 ] && [ -n "$binary_file" ] && [ -f "$binary_file" ] && rm -f "$binary_file"
 	[ -n "$checksum_file" ] && [ -f "$checksum_file" ] && rm -f "$checksum_file"
 	rm -f /tmp/busybox /tmp/fw_setenv /tmp/fw_printenv /tmp/sysupgrade
-	info "Cleaned up temporary files."
 }
 
 # Trap signals to ensure cleanup on exit
@@ -139,22 +146,28 @@ shift $((OPTIND-1))
 
 if [ "$upgrade" != "local" ] || [ -n "$1" ]; then
 	# Only stop services and remove snapshot if performing an upgrade
-	info "Stop services"
+	echo "Stop services"
 	stop_services
 
-	info "Remove snapshot"
-	run "rm -f /tmp/snapshot.jpg"
+	echo "Remove snapshot"
+	rm -f /tmp/snapshot.jpg
 
 	flush_memory
 fi
 
 if [ "local" = "$upgrade" ]; then
-	[ -z "$1" ] && { show_help; exit 1; }
+	if [ -z "$1" ]; then
+		show_help
+		exit 1
+	fi
 
 	if echo "$1" | grep -qE '^https?://'; then
 		binary_file=$(mktemp)
-		info "Downloading firmware from $1"
-		curl -# -L -f -o "$binary_file" "$1" || die "Failed to download firmware from $1"
+		echo "Downloading firmware from $1"
+		if ! curl -# -L -f -o "$binary_file" "$1"; then
+			echo "Failed to download firmware from $1"
+			exit 1
+		fi
 		downloaded_file=1  # Set flag indicating the file was downloaded
 	else
 		binary_file="$1"
@@ -163,7 +176,10 @@ if [ "local" = "$upgrade" ]; then
 else
 	data=/etc/os-release
 	profile=$(awk -F '=' '/^IMAGE_ID=/ {print $2}' $data)
-	[ -z "$profile" ] && die "Building profile is not set in $data"
+	if [ -z "$profile" ]; then
+		echo "Building profile is not set in $data"
+		exit 1
+	fi
 
 	url="https://github.com/themactep/thingino-firmware/releases/download/firmware"
 	checksum_url="https://github.com/themactep/thingino-firmware/releases/download/verify"
@@ -177,8 +193,11 @@ else
 	fi
 
 	binary_file=$(mktemp) # Create a temporary file to hold the firmware
-	info "Downloading firmware from ${url}${fw_file}."
-	curl -# -L -f -o "$binary_file" ${url}"${fw_file}" || die "Failed to download firmware from ${url}${fw_file}"
+	echo "Downloading firmware from ${url}${fw_file}."
+	if ! curl -# -L -f -o "$binary_file" ${url}"${fw_file}"; then
+		echo "Failed to download firmware from ${url}${fw_file}"
+		exit 1
+	fi
 
 	downloaded_file=1  # Set flag indicating the file was downloaded
 
@@ -189,7 +208,7 @@ fi
 # Detect if the file is gzipped
 magic=$(xxd -l 3 -p "$binary_file")
 if [ "$magic" = "$GZIP_MAGIC" ]; then
-	info "Detected gzip compressed binary."
+	echo "Detected gzip compressed binary."
 	# Check magic inside the gzipped file
 	internal_magic=$(zcat "$binary_file" | xxd -l 4 -p - | head -n 1)
 	is_gzip="true"
@@ -212,27 +231,33 @@ case "$internal_magic" in
 		mtd_dev="mtd5"
 		;;
 	"$ROOTFS_MAGIC")
-		die "We cannot flash only rootfs"
+		echo "We cannot flash only rootfs"
+		exit 1
 		;;
 	*)
-		die "Unknown file"
+		echo "Unknown file"
+		exit 1
 		;;
 esac
 
-grep -q -e "mtd6" -e "mtd5" /proc/mtd || die "Please run 'fw_setenv enable_updates true' then reboot the camera. Re-run upgrade after reboot."
+if ! grep -q -e "mtd6" -e "mtd5" /proc/mtd; then
+	echo "Please run 'fw_setenv enable_updates true' then reboot the camera. Re-run upgrade after reboot."
+	exit 1
+fi
 
-info "Unmount overlay"
-run "umount /overlay"
+echo "Unmount overlay"
+umount /overlay
 
-info "Unmount rootfs"
-run "umount /"
+echo "Unmount rootfs"
+umount /
 
 flush_memory
 
 echo
 
-info "Performing upgrade"
-warn "Do not turn off the power!"
+echo "Performing upgrade"
+echo
+echo "Do not turn off the power!"
 
 # Flash the firmware
 flash_firmware "$binary_file" "$mtd_dev" "$is_gzip"
