sysupgrade: remove old release logic to match workflow

diff --git a/overlay/lower/usr/sbin/sysupgrade b/overlay/lower/usr/sbin/sysupgrade
--- a/overlay/lower/usr/sbin/sysupgrade
+++ b/overlay/lower/usr/sbin/sysupgrade
@@ -76,11 +76,6 @@ expand_bb() {
 	ln -s $workdir/busybox $workdir/$1
 }
 
-get_previous_release() {
-	curl -s https://api.github.com/repos/themactep/thingino-firmware/releases | \
-	jsonfilter -e '@[*].tag_name' | grep '^firmware-' | head -2 | tail -1
-}
-
 handle_payload() {
 	if [ "local" = "$upgrade" ]; then
 		say "Upgrading from a provided file"
@@ -113,18 +108,10 @@ handle_payload() {
 
 		check_free_space $bin_url $offset
 
-		say "Download firmware and checksum"
-		if ! download "$bin_url" "$bin_file" "-C $offset"; then
-			say "Latest firmware not found. Trying the previous release."
-			previous_release=$(get_previous_release)
-			[ -z "$previous_release" ] && die "Failed to retrieve the previous release tag."
-
-			bin_url="$gh_url/releases/download/$previous_release/thingino-$profile.bin"
-			sha_url="$gh_url/releases/download/$previous_release/$bin_file.sha256sum"
-
-			download "$bin_url" "$bin_file" "-C $offset" || die "Cannot download firmware from fallback URL."
-		fi
-
+		#\n- $bin_url\n- $sha_url"
+		say "Downloading firmware from:\n$bin_url"
+		download "$bin_url" "$bin_file" "-C $offset" || die "Cannot download firmware from specified URL."
+		say "Downloading checksum from:\n$sha_url"
 		download "$sha_url" "$sha_file" || die "Cannot download checksum file."
 
 		say "Verifying downloaded file"
