Fix issue with handle_payload

diff --git a/overlay/lower/usr/sbin/sysupgrade b/overlay/lower/usr/sbin/sysupgrade
--- a/overlay/lower/usr/sbin/sysupgrade
+++ b/overlay/lower/usr/sbin/sysupgrade
@@ -85,11 +85,10 @@ extract_bootloader() {
 
 handle_payload() {
 	if [ "local" = "$upgrade" ]; then
-		say "Upgrading from a provided file"
-		if echo "$1" | grep -qE '^https?://'; then
-			say "Download firmware from\n$1"
-			check_free_space "$1"
-			download "$1" || die "Cannot download $1 to $fw_file"
+		if [ -n "$url" ]; then
+			say "Download firmware from\n$url"
+			check_free_space "$url"
+			download "$url" || die "Cannot download $url to $fw_file"
 		else
 			[ -f "$fw_file" ] || die "Cannot find $fw_file"
 		fi
@@ -245,18 +244,18 @@ if [ -z "$upgrade" ]; then
 
 	upgrade="local"
 	if echo "$file_or_url" | grep -qE '^https?://'; then
-		say "Upgrade from a remote file"
+		say "Upgrading from a remote file"
 		url="$file_or_url"
 	else
-		say "Upgrade from a local file"
+		say "Upgrading from a local file"
 		if [ -f "$fw_file" ]; then
 			say "Found $fw_file"
 		else
-			if ufile="$(realpath "$file_or_url")" && [ -r "$ufile" ]; then
+			if ufile="$(realpath "$file_or_url" 2>/dev/null)" && [ -r "$ufile" ]; then
 				say "Found $ufile"
 				mv -v "$ufile" "$fw_file" || die "Cannot move $ufile to $fw_file"
 			else
-				die "Cannot find file $file_or_url"
+				die "Cannot find file $file_or_url (from $(pwd))"
 			fi
 		fi
 	fi
@@ -314,7 +313,7 @@ trap cleanup 2 6 15
 
 [ -n "$url" ] && check_network "$url"
 
-handle_payload "$@"
+handle_payload
 
 case "$(xxd -l 4 -p $fw_file)" in
 "$U_BOOT_MAGIC") [ "$(stat -c%s $fw_file)" -le 262144 ] && mtd_dev="mtd0" || mtd_dev="mtd6" ;;
