sysupgrade: refactor and split to stages

diff --git a/overlay/lower/usr/sbin/sysupgrade b/overlay/lower/usr/sbin/sysupgrade
--- a/overlay/lower/usr/sbin/sysupgrade
+++ b/overlay/lower/usr/sbin/sysupgrade
@@ -3,85 +3,115 @@
 KERNEL_MAGIC="27051956"
 U_BOOT_MAGIC="06050403"
 ROOTFS_MAGIC="68737173"
-BB_BINARY=/tmp/busybox
 
-downloaded_file=0  # Flag to track if the file was downloaded
-trap_signal_received=0  # Flag to track if a signal was received
-
-if [ -z "$RUNNING_WITH_TMP_BUSYBOX" ]; then
-	if [ ! -f /tmp/busybox ]; then
-		cp /bin/busybox /tmp/busybox
-		cp $0 /tmp/sysupgrade
-		cp /sbin/fw_printenv /tmp/fw_printenv
-		ln -s /tmp/fw_printenv /tmp/fw_setenv
-		cp /etc/fw_env.config /tmp/fw_env.config
-	fi
-
-	RUNNING_WITH_TMP_BUSYBOX=1 exec /tmp/busybox sh /tmp/sysupgrade "$@"
-fi
+trap_signal_received=0  # flag to track if a signal was received
 
 cleanup() {
-	# Only perform cleanup if a signal (Ctrl+C or kill) was received
-	if [ "$trap_signal_received" -eq 1 ]; then
-		$BB_BINARY echo "Clean up temporary files."
-
-		# Only delete files that were downloaded (flag = 1)
-		[ "$downloaded_file" -eq 1 ] && [ -n "$binary_file" ] && [ -f "$binary_file" ] && $BB_BINARY rm -f "$binary_file"
-		[ -n "$checksum_file" ] && [ -f "$checksum_file" ] && $BB_BINARY rm -f "$checksum_file"
-		$BB_BINARY rm -f /tmp/fw_setenv /tmp/fw_printenv /tmp/sysupgrade
-
-		# Ensure no further commands are executed after removing busybox
-		/tmp/busybox rm -f /tmp/busybox
-		exit 0  # Immediately exit after cleanup to prevent any further commands or error output
-	fi
+	# Perform cleanup when a signal is received or an error occurs
+	echo "Cleaning up temporary files..."
+	# Delete all temporary files that start with 'tmp.' in the /tmp directory
+	rm -f /tmp/tmp.*
+	exit 0
 }
 
 # Trap INT and TERM signals to ensure cleanup when the script is interrupted or killed
 trap 'trap_signal_received=1; cleanup' INT TERM
 
 show_help() {
-	$BB_BINARY echo "Usage: $0 <filename> | [-f | -p] | <URL>
+	echo "Usage: $0 <filename> | [-f | -p] | <URL>
 Where:
-  -f          full upgrade with a binary from GitHub
-  -p          partial upgrade with a binary from GitHub
-  <filename>  full or partial upgrade from a local file
-  <URL>       full or partial upgrade from a URL
-  -h          this help
-"
+-f          full upgrade with a binary from GitHub
+-p          partial upgrade with a binary from GitHub
+<filename>  full or partial upgrade from a local file
+<URL>       full or partial upgrade from a URL
+-h          this help"
 }
 
-stop_service() {
-	if [ -f "/etc/init.d/$1" ]; then
-		$BB_BINARY sh /etc/init.d/"$1" stop
+download_file() {
+	local url=$1
+	local file_dest=$2
+
+	if ! curl -# -L -f -o "$file_dest" "$url"; then
+		echo -e "Failed to download: $url"
+		cleanup  # Clean up if download fails...
 	fi
 }
 
 verify_checksum() {
-	checksum_url="${checksum_url}/${sha256_file}"
+	local checksum_url=$1
+	local binary_file=$2
 
-	checksum_file=$($BB_BINARY mktemp)
-	$BB_BINARY echo -e "Downloading SHA-256 checksum from: \n$checksum_url"
-	if ! curl -# -L -f -o "$checksum_file" "$checksum_url"; then
-		$BB_BINARY echo -e "Failed to download checksum from: \n$checksum_url"
-		exit 1
+	checksum_file=$(mktemp -p /tmp tmp.XXXXXX)
+	echo "Downloading SHA-256 checksum from: $checksum_url"
+	download_file "$checksum_url" "$checksum_file"
+
+	expected_checksum=$(awk '{print $1}' "$checksum_file")
+	actual_checksum=$(sha256sum "$binary_file" | awk '{print $1}')
+
+	if [ "$expected_checksum" != "$actual_checksum" ]; then
+		echo "SHA-256 checksum verification failed! Firmware might be corrupted."
+		cleanup  # lets clean up if the checksum verification fails
 	fi
+}
 
-	# Extract the expected checksum (first field) from the downloaded file
-	expected_checksum=$($BB_BINARY awk '{print $1}' "$checksum_file")
-	actual_checksum=$($BB_BINARY sha256sum "$binary_file" | $BB_BINARY awk '{print $1}')
-
-	if [ "$expected_checksum" = "$actual_checksum" ]; then
-		$BB_BINARY echo "SHA-256 checksum verification succeeded."
-	else
-		$BB_BINARY echo "SHA-256 checksum verification failed! Firmware file might be corrupted."
+confirm_full_upgrade() {
+	echo "Warning: You are about to perform a full upgrade, which will replace the existing bootloader (U-Boot)."
+	echo "This is a risky operation, and if something goes wrong, you may need to perform a recovery to restore the system."
+	echo "Are you sure you want to proceed? (yes/no)"
+	read -r confirmation
+	if [ "$confirmation" != "yes" ]; then
+		echo "Full upgrade canceled."
 		exit 1
 	fi
 }
 
-reboot_func() {
-	$BB_BINARY echo "Rebooting in 5 seconds..."
-	$BB_BINARY sleep 5
-	$BB_BINARY echo wdt > /proc/jz/reset/reset
+download_and_verify() {
+	local fw_file="$1"
+	local checksum_file="$2"
+	local fw_url="$3"
+	local checksum_url="$4"
+
+	binary_file=$(mktemp -p /tmp tmp.XXXXXX)
+	echo
+	echo "Downloading firmware from: $fw_url"
+	download_file "$fw_url" "$binary_file"
+	verify_checksum "$checksum_url" "$binary_file"
+}
+
+prepare_flash() {
+	echo "Stopping services..."
+	stop_services
+
+	echo "Removing snapshots"
+	rm -f /tmp/snapshot.jpg
+	flush_memory
+
+	# Copy busybox to /tmp and make it executable
+	if ! cp /bin/busybox /tmp/busybox; then
+		echo "Error: Failed to copy busybox to /tmp"
+		cleanup  # Clean up if busybox cannot be copied
+	fi
+	chmod +x /tmp/busybox
+
+	# Copy stage2 script to /tmp and make it executable
+	if ! cp /usr/sbin/stage2 /tmp/tmp.stage2; then
+		echo "Error: Failed to copy stage2 to /tmp"
+		cleanup  # Clean up if stage2 cannot be copied
+	fi
+	chmod +x /tmp/tmp.stage2
+
+	# Use the copied busybox to run stage2
+	echo "Prepare for sysupgrade stage 2..."
+	if ! exec /tmp/busybox sh /tmp/tmp.stage2 "$binary_file" "$mtd_dev"; then
+		echo "Error: Failed to execute sysupgrade stage 2 using busybox"
+		cleanup  # Clean up if stage2 execution fails
+	fi
+}
+
+stop_service() {
+	if [ -f "/etc/init.d/$1" ]; then
+		sh /etc/init.d/"$1" stop
+	fi
 }
 
 stop_services() {
@@ -91,33 +121,18 @@ stop_services() {
 	done
 }
 
-flush_memory(){
-	$BB_BINARY echo "Sync changes"
-	$BB_BINARY sync
-
-	$BB_BINARY echo "Drop caches"
-	$BB_BINARY echo 3 > /proc/sys/vm/drop_caches
+flush_memory() {
+	echo "Sync changes"
+	sync
+	echo "Drop caches"
+	echo 3 > /proc/sys/vm/drop_caches
 }
 
-flash_firmware() {
-	$BB_BINARY echo "Erasing [First Pass] /dev/$mtd_dev"
-	$BB_BINARY flash_eraseall /dev/$mtd_dev
-	$BB_BINARY echo "Flashing firmware to /dev/$mtd_dev"
-	$BB_BINARY flashcp -v $binary_file /dev/$mtd_dev
-	$BB_BINARY echo -n
+# main logic
+force_upgrade=0
+upgrade=""
 
-	if [ $? -ne 0 ]; then
-		$BB_BINARY echo "Caution: You may need to perform a recovery flash restore before rebooting the camera!"
-		exit 1
-	fi
-
-	[ "mtd5" = "$mtd_dev" ] && /tmp/fw_setenv -c /tmp/fw_env.config sysupgrade_complete false
-
-	$BB_BINARY echo "Upgrade complete."
-	reboot_func
-}
-
-while getopts "fhp" flag; do
+while getopts "fhpy" flag; do
 	case "$flag" in
 		f)
 			upgrade="full"
@@ -125,12 +140,24 @@ while getopts "fhp" flag; do
 		p)
 			upgrade="part"
 			;;
+		y)
+			if [ "$upgrade" = "full" ]; then
+				force_upgrade=1
+			else
+				echo "Error: -y can only be used with -f (full upgrade)"
+				exit 1
+			fi
+			;;
 		h|*)
 			show_help
 			exit 1
 			;;
 	esac
 done
+
+if [ "$upgrade" = "full" ]; then
+	confirm_full_upgrade
+fi
 
 if [ -z "$upgrade" ]; then
 	if [ -z "$1" ]; then
@@ -142,37 +169,25 @@ fi
 
 shift $((OPTIND-1))
 
-$BB_BINARY echo "Stop services"
-stop_services
-
-$BB_BINARY echo "Remove snapshot"
-$BB_BINARY rm -f /tmp/snapshot.jpg
-
-flush_memory
-
-if [ "local" = "$upgrade" ]; then
-	$BB_BINARY echo "Upgrading from a provided file"
+if [ "$upgrade" = "local" ]; then
+	echo "Upgrading from a provided file"
 	if echo "$1" | grep -qE '^https?://'; then
-		binary_file=$($BB_BINARY mktemp)
-		$BB_BINARY echo -e "Downloading firmware from: \n$1"
-		if ! curl -# -L -f -o "$binary_file" "$1"; then
-			$BB_BINARY echo -e "Failed to download firmware from: \n$1"
-			exit 1
-		fi
-		downloaded_file=1  # Set flag indicating the file was downloaded
+		binary_file=$(mktemp -p /tmp tmp.XXXXXX)
+		echo "Downloading firmware from: $1"
+		download_file "$1" "$binary_file"
 	else
 		binary_file="$1"
 	fi
 else
-	$BB_BINARY echo "Upgrading from GitHub"
+	echo "Upgrading from GitHub"
 	data=/etc/os-release
-	profile=$($BB_BINARY awk -F '=' '/^IMAGE_ID=/ {print $2}' $data)
+	profile=$(awk -F '=' '/^IMAGE_ID=/ {print $2}' $data)
 	if [ -z "$profile" ]; then
-		$BB_BINARY echo "Building profile is not set in $data"
+		echo "Building profile is not set in $data"
 		exit 1
 	fi
 
-	url="https://github.com/themactep/thingino-firmware/releases/download/firmware"
+	fw_url="https://github.com/themactep/thingino-firmware/releases/download/firmware"
 	checksum_url="https://github.com/themactep/thingino-firmware/releases/download/verify"
 
 	if [ "$upgrade" = "part" ]; then
@@ -183,24 +198,14 @@ else
 		sha256_file="thingino-${profile}.bin.sha256sum"
 	fi
 
-	binary_file=$($BB_BINARY mktemp) # Create a temporary file to hold the firmware
-	$BB_BINARY echo -e "Downloading firmware from: \n${url}${fw_file}"
-	if !  curl -# -L -f -o "$binary_file" ${url}"${fw_file}"; then
-		$BB_BINARY echo -e "Failed to download firmware from: \n${url}${fw_file}"
-		exit 1
-	fi
-
-	downloaded_file=1  # Set flag indicating the file was downloaded
-
-	verify_checksum
+	download_and_verify "$fw_file" "$sha256_file" "${fw_url}${fw_file}" "${checksum_url}/${sha256_file}"
 fi
 
-# Detect magic directly from the binary file
-internal_magic=$($BB_BINARY xxd -l 4 -p "$binary_file")
+internal_magic=$(xxd -l 4 -p "$binary_file")
 
 case "$internal_magic" in
 	"$U_BOOT_MAGIC")
-		fsize=$($BB_BINARY stat -c%s "$binary_file")
+		fsize=$(stat -c%s "$binary_file")
 		if [ "$fsize" -le $((256 * 1024)) ]; then
 			mtd_dev="mtd0"
 		else
@@ -211,29 +216,16 @@ case "$internal_magic" in
 		mtd_dev="mtd5"
 		;;
 	"$ROOTFS_MAGIC")
-		$BB_BINARY echo "We cannot flash only rootfs"
+		echo "We cannot flash only rootfs"
 		exit 1
 		;;
 	*)
-		$BB_BINARY echo "Unknown file"
+		echo "Unknown file"
 		exit 1
 		;;
 esac
 
-if ! $BB_BINARY grep -q -e "mtd6" -e "mtd5" /proc/mtd; then
-	$BB_BINARY echo "Please run 'fw_setenv enable_updates true' then reboot the camera. Re-run upgrade after reboot."
-	exit 1
-fi
-
-$BB_BINARY echo "Unmount overlay"
-$BB_BINARY umount /overlay
-
-$BB_BINARY echo "Unmount rootfs"
-$BB_BINARY umount /
-
-flush_memory
-$BB_BINARY echo -e "\nPerforming upgrade\nDo not turn off the power!\n"
-flash_firmware
+prepare_flash
 
 # If we complete successfully, do not clean up
 trap - INT TERM
