sysupgrade: refactor check for target virtual partitions presence dynamically construct download url based on type of upgrade simplify verification of downloaded firmware check for internet access check for free space replace the message with consent by a message with timeout stop all services with the list of exclusions rather than a list to stop restore busybox applets in working directory remove whole working directory rather than individual files on cleanup stage 2: run from a constrained environment check for firmware and mtd device in arguments colorize the output

diff --git a/overlay/lower/usr/sbin/sysupgrade b/overlay/lower/usr/sbin/sysupgrade
--- a/overlay/lower/usr/sbin/sysupgrade
+++ b/overlay/lower/usr/sbin/sysupgrade
@@ -1,233 +1,247 @@
 #!/bin/sh
 
+# mandate virtual partitions
+grep -q "mtd[56]" /proc/mtd || die "Please run 'fw_setenv enable_updates true' then reboot the camera. Re-run upgrade after reboot."
+
 KERNEL_MAGIC="27051956"
 U_BOOT_MAGIC="06050403"
 ROOTFS_MAGIC="68737173"
+GH="https://github.com/"
+PAD="\t\t\t    "
 
-trap_signal_received=0  # flag to track if a signal was received
+workdir="/tmp/sysupgrade"
+stage2app="sysupgrade-stage2"
+[ -d $workdir ] || mkdir -p $workdir
+fw_file="$workdir/fw.bin"
+
+self=$(realpath $0)
+bbapplets="echo flash_eraseall flashcp reboot sh sleep"
+upgrade=""
+
+# work in $workdir
+cd $workdir
+
+bye() {
+	die "\n\n\tMaybe next time..."
+}
+
+check_network() {
+	curl -m 5 -I $1 >/dev/null 2>&1 && return
+	echo_c 160 "No internet?\n"
+	ip a
+	exit 1
+}
+
+check_free_space() {
+	local dl_size=$(curl -sIL $1 | awk '/Content-Length/{fs=$2}END{print fs}')
+	local free_space=$(df -m /tmp | tail -1 | awk '{print $4}')
+	free_space=$((free_space * 1024 * 1024))
+	[ "$dl_size" -gt "$free_space" ] && die "Not enough free space to download firmware: $dl_size > $free_space"
+}
 
 cleanup() {
-	# Perform cleanup when a signal is received or an error occurs
-	echo "Cleaning up temporary files..."
-	# Delete all temporary files that start with 'tmp.' in the /tmp directory
-	rm -f /tmp/tmp.*
+	say "Clean up temporary files."
+	rm -rf $workdir
 	exit 0
 }
 
-# Trap INT and TERM signals to ensure cleanup when the script is interrupted or killed
-trap 'trap_signal_received=1; cleanup' INT TERM
-
-show_help() {
-	echo "Usage: $0 <filename> | [-f | -p] | <URL>
-Where:
--f          full upgrade with a binary from GitHub
--p          partial upgrade with a binary from GitHub
-<filename>  full or partial upgrade from a local file
-<URL>       full or partial upgrade from a URL
--h          this help"
+clone_app() {
+	local target="$2"
+	[ -z "$target" ] && target="$(basename $1)"
+	if ! cp -vf "$1" "$workdir/$target"; then
+		say "Error: Failed to copy $1 to $workdir/$target"
+		cleanup
+	fi
+	chmod +x $workdir/$target
 }
 
-download_file() {
-	local url=$1
-	local file_dest=$2
-
-	if ! curl -# -L -f -o "$file_dest" "$url"; then
-		echo -e "Failed to download: $url"
-		cleanup  # Clean up if download fails...
-	fi
+die() {
+	say "$1"
+	exit 1
 }
 
-verify_checksum() {
-	local checksum_url=$1
-	local binary_file=$2
-
-	checksum_file=$(mktemp -p /tmp tmp.XXXXXX)
-	echo "Downloading SHA-256 checksum from: $checksum_url"
-	download_file "$checksum_url" "$checksum_file"
-
-	expected_checksum=$(awk '{print $1}' "$checksum_file")
-	actual_checksum=$(sha256sum "$binary_file" | awk '{print $1}')
-
-	if [ "$expected_checksum" != "$actual_checksum" ]; then
-		echo "SHA-256 checksum verification failed! Firmware might be corrupted."
-		cleanup  # lets clean up if the checksum verification fails
-	fi
+download() {
+	curl -fL# -o $fw_file $1 || die "Download failed!"
 }
 
-confirm_full_upgrade() {
-	echo "Warning: You are about to perform a full upgrade, which will replace the existing bootloader (U-Boot)."
-	echo "This is a risky operation, and if something goes wrong, you may need to perform a recovery to restore the system."
-	echo "Are you sure you want to proceed? (yes/no)"
-	read -r confirmation
-	if [ "$confirmation" != "yes" ]; then
-		echo "Full upgrade canceled."
-		exit 1
-	fi
+expand_bb() {
+	echo "set up $1"
+	ln -s $workdir/busybox $workdir/$1
 }
 
-download_and_verify() {
-	local fw_file="$1"
-	local checksum_file="$2"
-	local fw_url="$3"
-	local checksum_url="$4"
+handle_payload() {
+	if [ "local" = "$upgrade" ]; then
+		say "Upgrading from a provided file"
+		if echo "$1" | grep -qE '^https?://'; then
+			say "Download firmware from\n$1"
+			check_free_space $1
+			download $1
+		else
+			mv $1 $fw_file
+		fi
+	else
+		say "Upgrading from GitHub"
+		data=/etc/os-release
+		profile=$(awk -F= '/^IMAGE_ID=/ {print $2}' $data)
+		[ -z "$profile" ] && die "Building profile is not set in $data"
 
-	binary_file=$(mktemp -p /tmp tmp.XXXXXX)
-	echo
-	echo "Downloading firmware from: $fw_url"
-	download_file "$fw_url" "$binary_file"
-	verify_checksum "$checksum_url" "$binary_file"
-}
+		gh_url="$GH/themactep/thingino-firmware/releases/download"
+		bin_url="$gh_url/firmware"
+		sha_url="$gh_url/verify/"
 
-prepare_flash() {
-	echo "Stopping services..."
-	stop_services
+		if [ "part" = "$upgrade" ]; then
+			bin_url="${bin_url}_update/thingino-${profile}-update.bin"
+			sha_url="${sha_url}thingino-${profile}-update.bin.sha256sum"
+		else
+			bin_url="${bin_url}/thingino-${profile}.bin"
+			sha_url="${sha_url}thingino-${profile}.bin.sha256sum"
+		fi
+		bin_file=$(basename $bin_url)
+		sha_file=$(basename $sha_url)
 
-	echo "Removing snapshots"
-	rm -f /tmp/snapshot.jpg
-	flush_memory
+		check_free_space $bin_url
 
-	# Copy busybox to /tmp and make it executable
-	if ! cp /bin/busybox /tmp/busybox; then
-		echo "Error: Failed to copy busybox to /tmp"
-		cleanup  # Clean up if busybox cannot be copied
+		say "Download firmware\n$bin_url"
+		echo "curl -LO# $bin_url"
+		curl -LO# $bin_url || die "Failed to download firmware!"
+
+		say "Download checksum file\n$sha_url"
+		curl -LO# $sha_url || die "Failed to download checksum file!"
+
+		sha256sum -c $sha_file || die "Checksum does not match!"
+
+		rm $sha_file
+		mv $bin_file $fw_file
 	fi
-	chmod +x /tmp/busybox
-
-	# Copy stage2 script to /tmp and make it executable
-	if ! cp /usr/sbin/stage2 /tmp/tmp.stage2; then
-		echo "Error: Failed to copy stage2 to /tmp"
-		cleanup  # Clean up if stage2 cannot be copied
-	fi
-	chmod +x /tmp/tmp.stage2
-
-	# Use the copied busybox to run stage2
-	echo "Prepare for sysupgrade stage 2..."
-	if ! exec /tmp/busybox sh /tmp/tmp.stage2 "$binary_file" "$mtd_dev"; then
-		echo "Error: Failed to execute sysupgrade stage 2 using busybox"
-		cleanup  # Clean up if stage2 execution fails
-	fi
-}
-
-stop_service() {
-	if [ -f "/etc/init.d/$1" ]; then
-		sh /etc/init.d/"$1" stop
-	fi
-}
-
-stop_services() {
-	services="S01syslogd S09motor S15thingino-button S49ntpd S50httpd S50crond S50mdnsd S50mosquitto S93telegrambot S95prudynt S96iad S96onvif_discovery S97onvif_notify"
-	for service in $services; do
-		stop_service "$service"
-	done
 }
 
 flush_memory() {
-	echo "Sync changes"
+	say "Sync changes"
 	sync
-	echo "Drop caches"
+	say "Drop caches"
 	echo 3 > /proc/sys/vm/drop_caches
 }
 
-# main logic
-force_upgrade=0
-upgrade=""
+remove_snapshot() {
+	say "Remove snapshot"
+	rm -f /tmp/snapshot.jpg
+}
 
-while getopts "fhpy" flag; do
+say() {
+	echo -e "$1"
+}
+
+show_help() {
+	die "Usage: $0 [ -f | -p | <filename> | <URL> ]
+Where:
+  -f          full upgrade with a binary from GitHub
+  -p          partial upgrade with a binary from GitHub
+  <filename>  full or partial upgrade from a local file
+  <URL>       full or partial upgrade from a URL
+  -h          this help"
+}
+
+stop_services() {
+	say "Stop services"
+	for i in $(find /etc/init.d/ -name "[KS]*" -executable | sort -nr); do
+		case "$(basename $i)" in
+			S36wireless | S38wpa_supplicant | S40network | S50dropbear)
+				continue
+				;;
+			*)
+				sh -c "$i stop"
+				;;
+		esac
+	done
+}
+
+while getopts "fhp" flag; do
 	case "$flag" in
 		f)
+			say "Full upgrade from GitHub"
 			upgrade="full"
+			url="$GH"
 			;;
 		p)
+			say "Partial upgrade from GitHub"
 			upgrade="part"
+			url="$GH"
 			;;
-		y)
-			if [ "$upgrade" = "full" ]; then
-				force_upgrade=1
-			else
-				echo "Error: -y can only be used with -f (full upgrade)"
-				exit 1
-			fi
-			;;
-		h|*)
+		h | *)
 			show_help
-			exit 1
 			;;
 	esac
 done
 
-if [ "$upgrade" = "full" ]; then
-	confirm_full_upgrade
-fi
-
 if [ -z "$upgrade" ]; then
-	if [ -z "$1" ]; then
-		show_help
-		exit 1
-	fi
+	[ -z "$1" ] && show_help
+
 	upgrade="local"
-fi
-
-shift $((OPTIND-1))
-
-if [ "$upgrade" = "local" ]; then
-	echo "Upgrading from a provided file"
 	if echo "$1" | grep -qE '^https?://'; then
-		binary_file=$(mktemp -p /tmp tmp.XXXXXX)
-		echo "Downloading firmware from: $1"
-		download_file "$1" "$binary_file"
+		echo "Upgrade from a remote file"
+		url="$1"
 	else
-		binary_file="$1"
+		echo "Upgrade from a local file"
+		[ -r "$1" ] || die "Cannot find file $1"
 	fi
-else
-	echo "Upgrading from GitHub"
-	data=/etc/os-release
-	profile=$(awk -F '=' '/^IMAGE_ID=/ {print $2}' $data)
-	if [ -z "$profile" ]; then
-		echo "Building profile is not set in $data"
-		exit 1
-	fi
-
-	fw_url="https://github.com/themactep/thingino-firmware/releases/download/firmware"
-	checksum_url="https://github.com/themactep/thingino-firmware/releases/download/verify"
-
-	if [ "$upgrade" = "part" ]; then
-		fw_file="_update/thingino-${profile}-update.bin"
-		sha256_file="thingino-${profile}-update.bin.sha256sum"
-	else
-		fw_file="/thingino-${profile}.bin"
-		sha256_file="thingino-${profile}.bin.sha256sum"
-	fi
-
-	download_and_verify "$fw_file" "$sha256_file" "${fw_url}${fw_file}" "${checksum_url}/${sha256_file}"
 fi
 
-internal_magic=$(xxd -l 4 -p "$binary_file")
+if [ "full" = "$upgrade" ]; then
+	clear
+	echo_c 160 "
+$PAD ____ _____ ___  ____
+$PAD/ ___|_   _/ _ \|  _ \\
+$PAD\___ \ | || | | | |_) |
+$PAD ___) || || |_| |  __/
+$PAD|____/ |_| \___/|_|
+"
+	say "\tYou have requested to perform a full firmware upgrade,"
+	say "\twhich is a risky operation replacing the existing bootloader.\n"
+	say "\tIn the event of an error, the camera will become inoperable,"
+	say "\tand you will need to perform a recovery restore the system.\n"
+	echo_c 160 "\tYou have ten seconds to cancel the upgrade by pressing Ctrl-C."
+	echo -en "\n\n\t    "
 
-case "$internal_magic" in
-	"$U_BOOT_MAGIC")
-		fsize=$(stat -c%s "$binary_file")
-		if [ "$fsize" -le $((256 * 1024)) ]; then
-			mtd_dev="mtd0"
-		else
-			mtd_dev="mtd6"
-		fi
-		;;
-	"$KERNEL_MAGIC")
-		mtd_dev="mtd5"
-		;;
-	"$ROOTFS_MAGIC")
-		echo "We cannot flash only rootfs"
-		exit 1
-		;;
-	*)
-		echo "Unknown file"
-		exit 1
-		;;
+	trap bye 2 15
+	i=10
+	while :; do
+		[ "$i" -lt 0 ] && break
+		echo -n "$i"
+		[ "$i" -gt 0 ] && echo -n " .. "
+		i=$((i-1))
+		sleep 1
+	done
+	clear
+fi
+
+trap cleanup 2 6 15
+
+[ -n "$url" ] && check_network "$url"
+
+handle_payload "$@"
+
+case "$(xxd -l 4 -p $fw_file)" in
+	"$U_BOOT_MAGIC") [ "$(stat -c%s $fw_file)" -le 262144 ] && mtd_dev="mtd0" || mtd_dev="mtd6" ;;
+	"$KERNEL_MAGIC") mtd_dev="mtd5" ;;
+	"$ROOTFS_MAGIC") die "We cannot flash only rootfs" ;;
+	*) die "Unknown file" ;;
 esac
 
-prepare_flash
+stop_services
+remove_snapshot
+flush_memory
 
-# If we complete successfully, do not clean up
+clone_app /bin/busybox
+clone_app /sbin/$stage2app
+for a in $bbapplets; do expand_bb $a; done
+
+echo_c 208 "Switching to Stage 2.\n"
+if ! exec $workdir/busybox sh $workdir/$stage2app "$fw_file" "$mtd_dev"; then
+	say "Error: Failed to execute $workdir/$stage2app"
+	cleanup
+fi
+
+# If succeeded, do not clean up
 trap - INT TERM
 
 exit 0
