telegrambot: add thigino-diag to command presets.

diff --git a/overlay/lower/usr/sbin/thingino-diag b/overlay/lower/usr/sbin/thingino-diag
--- a/overlay/lower/usr/sbin/thingino-diag
+++ b/overlay/lower/usr/sbin/thingino-diag
@@ -1,17 +1,13 @@
 #!/bin/sh
 
+. /sbin/common
+
 show_help() {
+	echo -e "Thingino Diagnostics Script\n"
+	echo -e "Generate diagnostics log shared via termbin.com\n"
 	echo "Usage: $0 [-l]"
-	echo
-	echo "Thingino Diagnostics Script"
-	echo
-	echo "This script generates diagnostic logs to help developers troubleshoot issues with Thingino devices."
-	echo "The logs may contain sensitive or personal information, so please review them before sharing."
-	echo
-	echo "Options:"
-	echo "  -l    Save the diagnostics output to a local file instead of sharing it via termbin."
-	echo
-	echo "Without the -l option, the script will generate a link using termbin to share the diagnostics log."
+	echo "Where:"
+	echo "  -l    Save the log to a local file instead."
 	exit 0
 }
 
@@ -47,24 +43,24 @@ while getopts ":lh" opt; do
 			show_help
 			;;
 		\?)
-			echo "Invalid option: -$OPTARG" >&2
+			echo_c 160 "Invalid option: -$OPTARG" >&2
 			show_help
 			;;
 	esac
 done
 
-echo "thingino diagnostics"
-if [ -z "$local_file" ]; then
-	echo "This script requires network access."
-fi
-echo "It is designed to generate log information to share with developers for diagnostic issues."
-echo "It may contain sensitive or personal information, so make sure to review the log before sharing the link!"
-echo "We use termbin to share the log. Please review their acceptable use policy at https://www.termbin.com/"
-echo
-read -p "Do you wish to proceed? (yes/no): " response
-if [ "yes" != "$response" ]; then
-	echo "Operation aborted by the user."
-	exit 1
+if is_interactive_shell; then
+	echo_c 208 "Thingino Diagnostics"
+	[ -z "$local_file" ] && echo_c 11 "This script requires network access."
+	echo -e "\nThis script generates a log file for sharing with developers \
+for diagnostic issues.\nThe log may contain sensitive or personal information, \
+make sure to review it before sending the link!\nWe use termbin to share the log. \
+Please review their use policy at https://www.termbin.com/\n"
+	read -p "Do you wish to proceed? (yes/no): " response
+	if [ "yes" != "$response" ]; then
+		echo_c 160 "Operation aborted by the user."
+		exit 1
+	fi
 fi
 
 if [ -n "$local_file" ]; then
@@ -119,16 +115,11 @@ if [ -z "$local_file" ]; then
 	url=$(cat "$output_file" | send2termbin)
 	rm -f "$output_file"
 
-	echo
-	if [ -z "$url" ]; then
-		echo "There was an error."
-		exit 1
-	fi
+	[ -z "$url" ] && die "\nThere was an error."
 
-	echo "Your diagnostics log link:"
-	echo "$url"
+	echo -e "\nYour diagnostics log link:\n$url"
 else
-	echo "Diagnostics log saved locally at: $output_file"
+	echo "Diagnostics log saved locally at $output_file"
 fi
 
 exit 0
