automount: refactor. fix logger overriding exit codes.

diff --git a/overlay/lower/usr/lib/mdev/automount b/overlay/lower/usr/lib/mdev/automount
--- a/overlay/lower/usr/lib/mdev/automount
+++ b/overlay/lower/usr/lib/mdev/automount
@@ -1,69 +1,80 @@
 #!/bin/sh
 
-destdir=/mnt
-run="${destdir}/${MDEV}/run.sh"
-run_once="${destdir}/${MDEV}/runonce.sh"
-run_once_flag="${runonce/.sh/.done}"
+if [ -z "$MDEV" ]; then
+	echo "No device name to mount!"
+	exit 1
+fi
+
+devicenode="/dev/$MDEV"
+mountpoint="/mnt/$MDEV"
+
+run="$mountpoint/run.sh"
+run_once="$mountpoint/runonce.sh"
+run_once_flag="${run_once/.sh/.done}"
 
 log() {
-	logger -s -t automount -p daemon.info "$1"
+	logger -p daemon.info -t automount[$$] -s "$1"
 }
 
 cleanup() {
-	if [ -d "${destdir}/${MDEV}" ]; then
-		if rmdir "${destdir}/${MDEV}" 2>&1; then
-			log "Removed ${destdir}/${MDEV} mountpoint."
+	if [ -d "$mountpoint" ]; then
+		if rmdir "$mountpoint"; then
+			log "Removed $mountpoint mountpoint."
 		else
-			log "Failed to remove ${destdir}/${MDEV} mountpoint."
+			log "Failed to remove $mountpoint mountpoint."
 		fi
+	else
+		log "No $mountpoint mountpoint found."
 	fi
 }
 
 do_fsck() {
-	if fsck -a "/dev/${MDEV}" 2>&1 | logger -t automount -p daemon.warning; then
-		log "fsck check succeeded on /dev/${MDEV}"
+	if fsck "$devicenode"; then
+		log "fsck check succeeded on $devicenode"
 	else
-		log "fsck check failed on /dev/${MDEV}. Mounting process aborted."
+		log "fsck check failed on $devicenode, mounting process aborted."
 		return 1
 	fi
 }
 
 do_mount() {
-	if ! mkdir -p "${destdir}/${MDEV}" 2>&1; then
-		log "Cannot create ${destdir}/${MDEV} mountpoint."
+	if mkdir -p "$mountpoint"; then
+		log "Created $mountpoint mountpoint."
+	else
+		log "Cannot create $mountpoint mountpoint."
 		return 1
 	fi
 
 	do_fsck || return 1
 
-	if ! mount -t auto -o sync "/dev/${MDEV}" "${destdir}/${MDEV}" 2>&1; then
-		log "Failed to mount /dev/${MDEV} at ${destdir}/${MDEV} mountpoint."
+	if mount -t auto -o sync "$devicenode" "$mountpoint"; then
+		log "Mounted $devicenode to $mountpoint mountpoint."
+	else
+		log "Failed to mount $devicenode to $mountpoint mountpoint."
 		cleanup
 		return 1
 	fi
-
-	log "Mounted /dev/${MDEV} at ${destdir}/${MDEV} mountpoint."
 
 	[ -f "$run_once" ] && do_run_once
 	[ -f "$run" ] && do_run_always
 }
 
 do_umount() {
-	if grep -qs "^/dev/${MDEV} " /proc/mounts; then
-		if umount "${destdir}/${MDEV}" 2>&1; then
-			log "Unmounted ${destdir}/${MDEV} mountpoint."
+	if grep -qs "^$devicenode " /proc/mounts; then
+		if umount "$mountpoint"; then
+			log "Unmounted $mountpoint mountpoint."
 		else
-			log "Failed to unmount ${destdir}/${MDEV} mountpoint."
+			log "Failed to unmount $mountpoint mountpoint."
 		fi
 	else
-		log "/dev/${MDEV} is not mounted."
+		log "$devicenode is not mounted."
 	fi
 
 	cleanup
 }
 
 do_run_always() {
-	if sh $run 2>&1; then
+	if sh $run; then
 		log "Executed $run script."
 	else
 		log "Failed to execute $run script."
@@ -76,18 +87,13 @@ do_run_once() {
 		return 1
 	fi
 
-	if sh $run_once 2>&1; then
-		touch $run_once_flag
+	if sh "$run_once"; then
+		touch "$run_once_flag"
 		log "Executed $run_once script."
 	else
 		log "Failed to execute $run_once script."
 	fi
 }
-
-if [ -z "$MDEV" ]; then
-	log "No device name to mount!"
-	exit 1
-fi
 
 case "$ACTION" in
 	add | "")
